project:
  type: book
  output-dir: _book

execute: 
  cache: true
  freeze: auto

book:
  google-analytics: G-6LLMGL3T2Q
  title: "Biostatistiques appliquées avec R"
  subtitle: "Manuel de laboratoire pour le cours BIO4558"
  description: "Contient de l'information supplémentaire et des exercises"
  author: Julien Martin
  date: today
  date-format: iso #"`r format(Sys.Date(), '%d-%m-%Y')`"
  reader-mode: true
  search: true
  page-footer:
    left: |
     Par Julien Martin.
    right: |
      Ce livre a été crée avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/blue_dragon.jpg
  favicon: cover.jpg
  site-url: https://biostats-uottawa.github.io/bio4558_manuel/
  repo-url: https://github.com/biostats-uottawa/bio4558_manuel/
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  navbar:
    background: light
#    logo: quarto.png
#    logo-alt: "Quarto logo."
    collapse-below: lg
    title: "BIO4558: Labo"
    left:
      - text: Cours
        href: https://biostats-uottawa.github.io/bio4558_cours/
      - text: Données
        href: https://biostats-uottawa.github.io/bio4558_coure/dataset.html
      - text: Autres ressources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Advanced biostats and open science (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/
          - text: R-way to hell (R book)
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R (livre R)
            href: https://biostats-uottawa.github.io/R/fr/

  chapters:
    - index.Rmd
    - 01-introR.Rmd
    - 02-Gpower.Rmd
    - 03-reg_lin.Rmd
    - 04-t_test.Rmd
    - 05-anova.Rmd
    - 06-anova_mult.Rmd
    - 07-reg_mult.Rmd
    - 08-ancova_glm.Rmd
#    - 09-model_freq.Rmd
    - 99-references.qmd
  appendices:
#    - 10-software.Rmd
    - 10-notebook.Rmd

bibliography: [book.bib, grateful-refs.bib]
biblio-style: apalike
csl: ecology.csl

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
      #- r4ds.scss
    css: css/style.css
    code-link: true

    author-meta: "Julien Martin"
    callout-appearance: simple

  pdf:
    documentclass: scrbook
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    toc-depth: 2

  epub:
    dev: svglite
    stylesheet: css/epub.css
    toc: true

editor: visual