<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.2 ANOVA à un critère de classification et comparaisons multiples | BIO4558 Biostatistiques appliquées avec R</title>
  <meta name="description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="5.2 ANOVA à un critère de classification et comparaisons multiples | BIO4558 Biostatistiques appliquées avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/missing.png" />
  <meta property="og:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="github-repo" content="JulienGAMartin/BIO4558_uOttawa_lab_manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.2 ANOVA à un critère de classification et comparaisons multiples | BIO4558 Biostatistiques appliquées avec R" />
  
  <meta name="twitter:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="twitter:image" content="images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="set-ano.html"/>
<link rel="next" href="transformations-de-données-et-anova-non-paramétrique.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4558 Manuel de laboratoire</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a><ul>
<li class="chapter" data-level="" data-path="quelques-points-importants-à-retenir.html"><a href="quelques-points-importants-à-retenir.html"><i class="fa fa-check"></i>Quelques points importants à retenir</a></li>
<li class="chapter" data-level="" data-path="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><a href="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><i class="fa fa-check"></i>Qu’est-ce que R et pourquoi l’utiliser dans ce cours?</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html"><i class="fa fa-check"></i>Installation des logiciels nécessaires</a><ul>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#rstudio"><i class="fa fa-check"></i>Rstudio</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#paquets-pour-r"><i class="fa fa-check"></i>Paquets pour R</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="instructions-générales-pour-les-laboratoires.html"><a href="instructions-générales-pour-les-laboratoires.html"><i class="fa fa-check"></i>Instructions générales pour les laboratoires</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html"><i class="fa fa-check"></i>Notes sur le manuel</a><ul>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#licence"><i class="fa fa-check"></i>Licence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-à-r.html"><a href="introduction-à-r.html"><i class="fa fa-check"></i><b>1</b> Introduction à R</a><ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="1.2" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html"><i class="fa fa-check"></i><b>1.2</b> Premier pas avec R</a><ul>
<li class="chapter" data-level="1.2.1" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#la-console"><i class="fa fa-check"></i><b>1.2.1</b> La console</a></li>
<li class="chapter" data-level="1.2.2" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#objets"><i class="fa fa-check"></i><b>1.2.2</b> Objets</a></li>
<li class="chapter" data-level="1.2.3" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#vecteurs"><i class="fa fa-check"></i><b>1.2.3</b> Vecteurs</a></li>
<li class="chapter" data-level="1.2.4" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#fonctions"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions</a></li>
<li class="chapter" data-level="1.2.5" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#regrouper-ses-commandes-dans-des-scripts"><i class="fa fa-check"></i><b>1.2.5</b> Regrouper ses commandes dans des scripts</a></li>
<li class="chapter" data-level="1.2.6" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#packages"><i class="fa fa-check"></i><b>1.2.6</b> Installer et charger des extensions (<em>packages</em>)</a></li>
<li class="chapter" data-level="1.2.7" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#ex-introR"><i class="fa fa-check"></i><b>1.2.7</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html"><i class="fa fa-check"></i><b>1.3</b> Premier travail avec des données</a><ul>
<li class="chapter" data-level="1.3.1" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#jeu-de-données-dexemple"><i class="fa fa-check"></i><b>1.3.1</b> Jeu de données d’exemple</a></li>
<li class="chapter" data-level="1.3.2" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#tableau-de-données-data-frame"><i class="fa fa-check"></i><b>1.3.2</b> Tableau de données (<em>data frame</em>)</a></li>
<li class="chapter" data-level="1.3.3" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#analyse-univariée"><i class="fa fa-check"></i><b>1.3.3</b> Analyse univariée</a></li>
<li class="chapter" data-level="1.3.4" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#ex-introR-univ"><i class="fa fa-check"></i><b>1.3.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html"><i class="fa fa-check"></i><b>1.4</b> Analyse de 2 variables</a><ul>
<li class="chapter" data-level="1.4.1" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-de-deux-variables-qualitatives"><i class="fa fa-check"></i><b>1.4.1</b> Croisement de deux variables qualitatives</a></li>
<li class="chapter" data-level="1.4.2" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-dune-variable-quantitative-et-dune-variable-qualitative"><i class="fa fa-check"></i><b>1.4.2</b> Croisement d’une variable quantitative et d’une variable qualitative</a></li>
<li class="chapter" data-level="1.4.3" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-de-deux-variables-quantitatives"><i class="fa fa-check"></i><b>1.4.3</b> Croisement de deux variables quantitatives</a></li>
<li class="chapter" data-level="1.4.4" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#ex-introR-biv"><i class="fa fa-check"></i><b>1.4.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="gérer-les-données.html"><a href="gérer-les-données.html"><i class="fa fa-check"></i><b>1.5</b> Gérer les données</a><ul>
<li class="chapter" data-level="1.5.1" data-path="gérer-les-données.html"><a href="gérer-les-données.html#importer-et-exporter-des-données"><i class="fa fa-check"></i><b>1.5.1</b> Importer et exporter des données</a></li>
<li class="chapter" data-level="1.5.2" data-path="gérer-les-données.html"><a href="gérer-les-données.html#examen-préliminaire-des-données"><i class="fa fa-check"></i><b>1.5.2</b> Examen préliminaire des données</a></li>
<li class="chapter" data-level="1.5.3" data-path="gérer-les-données.html"><a href="gérer-les-données.html#créer-des-sous-ensembles-de-cas"><i class="fa fa-check"></i><b>1.5.3</b> Créer des sous-ensembles de cas</a></li>
<li class="chapter" data-level="1.5.4" data-path="gérer-les-données.html"><a href="gérer-les-données.html#transformations-de-données"><i class="fa fa-check"></i><b>1.5.4</b> Transformations de données</a></li>
<li class="chapter" data-level="1.5.5" data-path="gérer-les-données.html"><a href="gérer-les-données.html#exercice-sur-r"><i class="fa fa-check"></i><b>1.5.5</b> Exercice sur R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html"><i class="fa fa-check"></i><b>2</b> Analyse de puissance avec R et G*Power</a><ul>
<li class="chapter" data-level="2.1" data-path="la-théorie.html"><a href="la-théorie.html"><i class="fa fa-check"></i><b>2.1</b> La théorie</a><ul>
<li class="chapter" data-level="2.1.1" data-path="la-théorie.html"><a href="la-théorie.html#quest-ce-que-la-puissance"><i class="fa fa-check"></i><b>2.1.1</b> Qu’est-ce que la puissance?</a></li>
<li class="chapter" data-level="2.1.2" data-path="la-théorie.html"><a href="la-théorie.html#pourquoi-faire-une-analyse-de-puissance"><i class="fa fa-check"></i><b>2.1.2</b> Pourquoi faire une analyse de puissance?</a></li>
<li class="chapter" data-level="2.1.3" data-path="la-théorie.html"><a href="la-théorie.html#facteurs-qui-affectent-la-puissance"><i class="fa fa-check"></i><b>2.1.3</b> Facteurs qui affectent la puissance</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="quest-ce-que-gpower.html"><a href="quest-ce-que-gpower.html"><i class="fa fa-check"></i><b>2.2</b> Qu’est ce que G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html"><i class="fa fa-check"></i><b>2.3</b> Comment utiliser G*Power</a><ul>
<li class="chapter" data-level="2.3.1" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#principe-général"><i class="fa fa-check"></i><b>2.3.1</b> Principe général</a></li>
<li class="chapter" data-level="2.3.2" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#types-danalyses-de-puissance-disponibles"><i class="fa fa-check"></i><b>2.3.2</b> Types d’analyses de puissance disponibles</a></li>
<li class="chapter" data-level="2.3.3" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#comment-calculer-la-taille-de-leffet-gpower-permet-de-faire-une-analyse-de-puissance-pour-de-nombreux-tests-statistiques"><i class="fa fa-check"></i><b>2.3.3</b> Comment calculer la taille de l’effet G*Power permet de faire une analyse de puissance pour de nombreux tests statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><i class="fa fa-check"></i><b>2.4</b> Puissance pour un test de t comparant deux moyennes</a><ul>
<li class="chapter" data-level="2.4.1" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-post-hoc"><i class="fa fa-check"></i><b>2.4.1</b> Analyse post-hoc</a></li>
<li class="chapter" data-level="2.4.2" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-à-priori"><i class="fa fa-check"></i><b>2.4.2</b> Analyse à priori</a></li>
<li class="chapter" data-level="2.4.3" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-de-sensitivité---calculer-la-taille-deffet-détectable"><i class="fa fa-check"></i><b>2.4.3</b> Analyse de sensitivité - Calculer la taille d’effet détectable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="points-à-retenir.html"><a href="points-à-retenir.html"><i class="fa fa-check"></i><b>2.5</b> Points à retenir</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html"><i class="fa fa-check"></i><b>3</b> Corrélation et régression linéaire simple</a><ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> Extensions R et données requises pour le labo</a></li>
<li class="chapter" data-level="3.2" data-path="diagrammes-de-dispersion.html"><a href="diagrammes-de-dispersion.html"><i class="fa fa-check"></i><b>3.2</b> Diagrammes de dispersion</a></li>
<li class="chapter" data-level="3.3" data-path="transformations-et-le-coefficient-de-corrélation.html"><a href="transformations-et-le-coefficient-de-corrélation.html"><i class="fa fa-check"></i><b>3.3</b> Transformations et le coefficient de corrélation</a></li>
<li class="chapter" data-level="3.4" data-path="matrices-de-corrélations-et-correction-de-bonferroni.html"><a href="matrices-de-corrélations-et-correction-de-bonferroni.html"><i class="fa fa-check"></i><b>3.4</b> Matrices de corrélations et correction de Bonferroni</a></li>
<li class="chapter" data-level="3.5" data-path="corrélations-non-paramétriques-r-de-spearman-et-tau-de-kendall.html"><a href="corrélations-non-paramétriques-r-de-spearman-et-tau-de-kendall.html"><i class="fa fa-check"></i><b>3.5</b> Corrélations non paramétriques: <em>r</em> de Spearman et <span class="math inline">\(\tau\)</span> de Kendall</a></li>
<li class="chapter" data-level="3.6" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html"><i class="fa fa-check"></i><b>3.6</b> Régression linéaire simple</a><ul>
<li class="chapter" data-level="3.6.1" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html#vérifier-les-conditions-dapplication-de-la-régression"><i class="fa fa-check"></i><b>3.6.1</b> Vérifier les conditions d’application de la régression</a></li>
<li class="chapter" data-level="3.6.2" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html#tests-formels-des-conditions-dapplication-pour-la-régression"><i class="fa fa-check"></i><b>3.6.2</b> Tests formels des conditions d’application pour la régression</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="transformation-des-données-en-régression.html"><a href="transformation-des-données-en-régression.html"><i class="fa fa-check"></i><b>3.7</b> Transformation des données en régression</a></li>
<li class="chapter" data-level="3.8" data-path="traitement-des-valeurs-extrèmes.html"><a href="traitement-des-valeurs-extrèmes.html"><i class="fa fa-check"></i><b>3.8</b> Traitement des valeurs extrèmes</a></li>
<li class="chapter" data-level="3.9" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><i class="fa fa-check"></i><b>3.9</b> Quantifier la taille d’effet et analyse de puissance en régression</a><ul>
<li class="chapter" data-level="3.9.1" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html#puissance-de-détecter-une-pente-donnée"><i class="fa fa-check"></i><b>3.9.1</b> Puissance de détecter une pente donnée</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html#effectif-requis-pour-atteindre-une-puissance-désirée-test-a-priori"><i class="fa fa-check"></i><b>3.9.2</b> Effectif requis pour atteindre une puissance désirée (test A-priori)</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrap-en-régression-simple-avec-r.html"><a href="bootstrap-en-régression-simple-avec-r.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrap en régression simple avec R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html"><i class="fa fa-check"></i><b>4</b> Comparaison de deux échantillons</a><ul>
<li class="chapter" data-level="4.1" data-path="set-t.html"><a href="set-t.html"><i class="fa fa-check"></i><b>4.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="4.2" data-path="examen-visuel-des-données.html"><a href="examen-visuel-des-données.html"><i class="fa fa-check"></i><b>4.2</b> Examen visuel des données</a></li>
<li class="chapter" data-level="4.3" data-path="comparer-les-moyennes-de-deux-échantillons-indépendants.html"><a href="comparer-les-moyennes-de-deux-échantillons-indépendants.html"><i class="fa fa-check"></i><b>4.3</b> Comparer les moyennes de deux échantillons indépendants</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap et tests de permutation pour comparer deux moyennes</a><ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparer-les-moyennes-de-deux-échantillons-appariés.html"><a href="comparer-les-moyennes-de-deux-échantillons-appariés.html"><i class="fa fa-check"></i><b>4.5</b> Comparer les moyennes de deux échantillons appariés</a></li>
<li class="chapter" data-level="4.6" data-path="références.html"><a href="références.html"><i class="fa fa-check"></i><b>4.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html"><i class="fa fa-check"></i><b>5</b> ANOVA à un critère de classification</a><ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="5.2" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><i class="fa fa-check"></i><b>5.2</b> ANOVA à un critère de classification et comparaisons multiples</a><ul>
<li class="chapter" data-level="5.2.1" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#vérifier-les-conditions-dapplication-de-lanova-paramétrique"><i class="fa fa-check"></i><b>5.2.2</b> Vérifier les conditions d’application de l’ANOVA paramétrique</a></li>
<li class="chapter" data-level="5.2.3" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#faire-lanova"><i class="fa fa-check"></i><b>5.2.3</b> Faire l’ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#les-comparaisons-multiples"><i class="fa fa-check"></i><b>5.2.4</b> Les comparaisons multiples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="transformations-de-données-et-anova-non-paramétrique.html"><a href="transformations-de-données-et-anova-non-paramétrique.html"><i class="fa fa-check"></i><b>5.3</b> Transformations de données et ANOVA non-paramétrique</a></li>
<li class="chapter" data-level="5.4" data-path="examen-des-valeurs-extrêmes.html"><a href="examen-des-valeurs-extrêmes.html"><i class="fa fa-check"></i><b>5.4</b> Examen des valeurs extrêmes</a></li>
<li class="chapter" data-level="5.5" data-path="test-de-permutation.html"><a href="test-de-permutation.html"><i class="fa fa-check"></i><b>5.5</b> Test de permutation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova-à-critères-multiples-plans-factoriels-et-hiérarchiques.html"><a href="anova-à-critères-multiples-plans-factoriels-et-hiérarchiques.html"><i class="fa fa-check"></i><b>6</b> ANOVA à critères multiples : plans factoriels et hiérarchiques</a><ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="6.2" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><i class="fa fa-check"></i><b>6.2</b> Plan factoriel à deux facteurs de classification et réplication</a><ul>
<li class="chapter" data-level="6.2.1" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html#anova-à-effets-fixes"><i class="fa fa-check"></i><b>6.2.1</b> ANOVA à effets fixes</a></li>
<li class="chapter" data-level="6.2.2" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html#anova-à-effets-mixtes"><i class="fa fa-check"></i><b>6.2.2</b> ANOVA à effets mixtes</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html"><i class="fa fa-check"></i><b>6.3</b> Plan factoriel à deux facteurs de classification sans réplication</a></li>
<li class="chapter" data-level="6.4" data-path="plans-hiérarchiques.html"><a href="plans-hiérarchiques.html"><i class="fa fa-check"></i><b>6.4</b> Plans hiérarchiques</a></li>
<li class="chapter" data-level="6.5" data-path="anova-non-paramétrique-avec-deux-facteurs-de-classification.html"><a href="anova-non-paramétrique-avec-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.5</b> ANOVA non paramétrique avec deux facteurs de classification</a></li>
<li class="chapter" data-level="6.6" data-path="comparaisons-multiples.html"><a href="comparaisons-multiples.html"><i class="fa fa-check"></i><b>6.6</b> Comparaisons multiples</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-pour-lanova-à-deux-facteurs-de-classification.html"><a href="bootstrap-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap pour l’ANOVA à deux facteurs de classification</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="régression-multiple.html"><a href="régression-multiple.html"><i class="fa fa-check"></i><b>7</b> Régression multiple</a><ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="7.2" data-path="conseils-généraux.html"><a href="conseils-généraux.html"><i class="fa fa-check"></i><b>7.2</b> Conseils généraux</a></li>
<li class="chapter" data-level="7.3" data-path="premières-régressions-multiples.html"><a href="premières-régressions-multiples.html"><i class="fa fa-check"></i><b>7.3</b> Premières régressions multiples</a></li>
<li class="chapter" data-level="7.4" data-path="régression-multiple-pas-à-pas-stepwise.html"><a href="régression-multiple-pas-à-pas-stepwise.html"><i class="fa fa-check"></i><b>7.4</b> Régression multiple pas-à-pas (stepwise)</a></li>
<li class="chapter" data-level="7.5" data-path="détecter-la-multicolinéarité.html"><a href="détecter-la-multicolinéarité.html"><i class="fa fa-check"></i><b>7.5</b> Détecter la multicolinéarité</a></li>
<li class="chapter" data-level="7.6" data-path="régression-polynomiale.html"><a href="régression-polynomiale.html"><i class="fa fa-check"></i><b>7.6</b> Régression polynomiale</a></li>
<li class="chapter" data-level="7.7" data-path="vérifier-les-conditions-dapplication-de-modèles-de-régression-multiple.html"><a href="vérifier-les-conditions-dapplication-de-modèles-de-régression-multiple.html"><i class="fa fa-check"></i><b>7.7</b> Vérifier les conditions d’application de modèles de régression multiple</a></li>
<li class="chapter" data-level="7.8" data-path="visualiser-la-taille-deffet.html"><a href="visualiser-la-taille-deffet.html"><i class="fa fa-check"></i><b>7.8</b> Visualiser la taille d’effet</a></li>
<li class="chapter" data-level="7.9" data-path="tester-la-présence-dinteractions.html"><a href="tester-la-présence-dinteractions.html"><i class="fa fa-check"></i><b>7.9</b> Tester la présence d’interactions</a></li>
<li class="chapter" data-level="7.10" data-path="recherche-du-meilleur-modèle-fondée-sur-la-théorie-de-linformation.html"><a href="recherche-du-meilleur-modèle-fondée-sur-la-théorie-de-linformation.html"><i class="fa fa-check"></i><b>7.10</b> Recherche du meilleur modèle fondée sur la théorie de l’information</a></li>
<li class="chapter" data-level="7.11" data-path="bootstrap-et-régression-multiple.html"><a href="bootstrap-et-régression-multiple.html"><i class="fa fa-check"></i><b>7.11</b> Bootstrap et régression multiple</a></li>
<li class="chapter" data-level="7.12" data-path="perm-reg-mult.html"><a href="perm-reg-mult.html"><i class="fa fa-check"></i><b>7.12</b> Test de permutation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-et-modèle-linéaire-général.html"><a href="ancova-et-modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8</b> ANCOVA et modèle linéaire général</a><ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="8.2" data-path="modèle-linéaire-général.html"><a href="modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8.2</b> Modèle linéaire général</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html"><i class="fa fa-check"></i><b>8.4</b> Homogénéité des pentes</a><ul>
<li class="chapter" data-level="8.4.1" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html#cas-1---la-taille-en-fonction-de-lâge-exemple-avec-pente-commune"><i class="fa fa-check"></i><b>8.4.1</b> Cas 1 - La taille en fonction de l’âge (exemple avec pente commune)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html#cas-2---taille-en-fonction-de-lâge-exemple-avec-des-pentes-différentes"><i class="fa fa-check"></i><b>8.4.2</b> Cas 2 - Taille en fonction de l’âge (exemple avec des pentes différentes)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="le-modèle-dancova.html"><a href="le-modèle-dancova.html"><i class="fa fa-check"></i><b>8.5</b> Le modèle d’ANCOVA</a></li>
<li class="chapter" data-level="8.6" data-path="comparer-lajustement-de-modèles.html"><a href="comparer-lajustement-de-modèles.html"><i class="fa fa-check"></i><b>8.6</b> Comparer l’ajustement de modèles</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analyse-de-données-de-fréquence-tableaux-de-contingence-modèles-log-linéaires-et-régression-de-poisson.html"><a href="analyse-de-données-de-fréquence-tableaux-de-contingence-modèles-log-linéaires-et-régression-de-poisson.html"><i class="fa fa-check"></i><b>9</b> Analyse de données de fréquence: Tableaux de contingence, modèles log-linéaires et régression de Poisson</a><ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="9.2" data-path="organisation-des-données-3-formats.html"><a href="organisation-des-données-3-formats.html"><i class="fa fa-check"></i><b>9.2</b> Organisation des données: 3 formats</a></li>
<li class="chapter" data-level="9.3" data-path="visualiser-graphiquement-les-tableaux-de-contingence-et-test-dindépendance.html"><a href="visualiser-graphiquement-les-tableaux-de-contingence-et-test-dindépendance.html"><i class="fa fa-check"></i><b>9.3</b> Visualiser graphiquement les tableaux de contingence et test d’indépendance</a></li>
<li class="chapter" data-level="9.4" data-path="régression-de-poisson-une-alternative-au-test-de-chi-carré-pour-les-tableaux-de-contingence.html"><a href="régression-de-poisson-une-alternative-au-test-de-chi-carré-pour-les-tableaux-de-contingence.html"><i class="fa fa-check"></i><b>9.4</b> Régression de Poisson: une alternative au test de Chi carré pour les tableaux de contingence</a></li>
<li class="chapter" data-level="9.5" data-path="tester-une-hypothèse-extrinsèque.html"><a href="tester-une-hypothèse-extrinsèque.html"><i class="fa fa-check"></i><b>9.5</b> Tester une hypothèse extrinsèque</a></li>
<li class="chapter" data-level="9.6" data-path="régression-de-poisson-pour-lanalyse-de-tableaux-de-contingence-à-plusieurs-critères.html"><a href="régression-de-poisson-pour-lanalyse-de-tableaux-de-contingence-à-plusieurs-critères.html"><i class="fa fa-check"></i><b>9.6</b> Régression de Poisson pour l’analyse de tableaux de contingence à plusieurs critères</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendice</b></span></li>
<li class="chapter" data-level="A" data-path="note-sur-les-devoirs-et-rmarkdown.html"><a href="note-sur-les-devoirs-et-rmarkdown.html"><i class="fa fa-check"></i><b>A</b> Note sur les devoirs et Rmarkdown</a></li>
<li class="chapter" data-level="B" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html"><i class="fa fa-check"></i><b>B</b> Petit guide pour Rmarkdown</a><ul>
<li class="chapter" data-level="B.1" data-path="syntaxe-markdown.html"><a href="syntaxe-markdown.html"><i class="fa fa-check"></i><b>B.1</b> Syntaxe Markdown</a><ul>
<li class="chapter" data-level="B.1.1" data-path="syntaxe-markdown.html"><a href="syntaxe-markdown.html#titre-3"><i class="fa fa-check"></i><b>B.1.1</b> Titre 3</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="à-propos-de-latex.html"><a href="à-propos-de-latex.html"><i class="fa fa-check"></i><b>B.2</b> À propos de LaTex</a></li>
<li class="chapter" data-level="B.3" data-path="concernant-le-code-dans-notebook.html"><a href="concernant-le-code-dans-notebook.html"><i class="fa fa-check"></i><b>B.3</b> Concernant le code dans notebook</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><a href="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><i class="fa fa-check"></i><b>C</b> Resources pour en apprendre plus sur rmarkdown</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4558 Biostatistiques appliquées avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova-à-un-critère-de-classification-et-comparaisons-multiples" class="section level2">
<h2><span class="header-section-number">5.2</span> ANOVA à un critère de classification et comparaisons multiples</h2>
<p>L’ANOVA à un critère de classification est l’analogue du test de t pour des comparaisons de moyennes de plus de deux échantillons. Les conditions d’application du test sont essentiellement les mêmes, et lorsque appliqué à deux échantillons ce test est mathématiquement équivalent au test de t.</p>
<p>En 1961-1962, le barrage Grand Rapids était construit sur la rivière Saskatchewan en amont de Cumberland House. On croit que durant la construction plusieurs gros esturgeons restèrent prisonniers dans des sections peu profondes et moururent. Des inventaires de la population d’esturgeons furent faits en 1954, 1958, 1965 et 1966. Au cours de ces inventaires, la longueur à la fourche (frklngth) furent mesurées (pas nécessairement sur chaque poisson cependant). Ces données sont dans le fichier <code>Dam10dat.csv</code>.</p>
<div id="visualiser-les-données" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Visualiser les données</h3>
<ul>
<li>À partir des données, vous devez d’abord changer le type de donnée de la variable <code>year</code>, pour que R traite <code>year</code> comme une variable discontinue (factor) plutôt que continue.</li>
</ul>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb369-1" title="1">Dam10dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Dam10dat.csv&quot;</span>)</a>
<a class="sourceLine" id="cb369-2" title="2">Dam10dat<span class="op">$</span>year &lt;-<span class="st"> </span><span class="kw">as.factor</span>(Dam10dat<span class="op">$</span>year)</a>
<a class="sourceLine" id="cb369-3" title="3"><span class="kw">str</span>(Dam10dat)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    118 obs. of  21 variables:
##  $ year    : Factor w/ 4 levels &quot;1954&quot;,&quot;1958&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ fklngth : num  45 50 39 46 54.5 49 42.5 49 56 54 ...
##  $ totlngth: num  49 NA 43 50.5 NA 51.7 45.5 52 60.2 58.5 ...
##  $ drlngth : logi  NA NA NA NA NA NA ...
##  $ drwght  : num  16 20.5 10 17.5 19.7 21.3 9.5 23.7 31 27.3 ...
##  $ rdwght  : num  24.5 33 15.5 28.5 32.5 35.5 15.3 40.5 51.5 43 ...
##  $ sex     : int  1 1 1 2 1 2 1 1 1 1 ...
##  $ age     : int  24 33 17 31 37 44 23 34 33 47 ...
##  $ lfkl    : num  1.65 1.7 1.59 1.66 1.74 ...
##  $ ltotl   : num  1.69 NA 1.63 1.7 NA ...
##  $ ldrl    : logi  NA NA NA NA NA NA ...
##  $ ldrwght : num  1.2 1.31 1 1.24 1.29 ...
##  $ lrdwght : num  1.39 1.52 1.19 1.45 1.51 ...
##  $ lage    : num  1.38 1.52 1.23 1.49 1.57 ...
##  $ rage    : int  4 6 3 6 7 7 4 6 6 7 ...
##  $ ryear   : int  1954 1954 1954 1954 1954 1954 1954 1954 1954 1954 ...
##  $ ryear2  : int  1958 1958 1958 1958 1958 1958 1958 1958 1958 1958 ...
##  $ ryear3  : int  1966 1966 1966 1966 1966 1966 1966 1966 1966 1966 ...
##  $ location: int  1 1 1 1 1 1 1 1 1 1 ...
##  $ girth   : logi  NA NA NA NA NA NA ...
##  $ lgirth  : logi  NA NA NA NA NA NA ...</code></pre>
<ul>
<li>Ensuite, visualisez les données comme dans le labo pour les tests de t. Créez un histogramme avec ligne de densité et un Box plot par année. Que vous révèlent ces données?</li>
</ul>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" title="1">mygraph &lt;-<span class="st"> </span><span class="kw">ggplot</span>(Dam10dat, <span class="kw">aes</span>(<span class="dt">x =</span> fklngth)) <span class="op">+</span></a>
<a class="sourceLine" id="cb371-2" title="2"><span class="st">  </span><span class="kw">labs</span> (<span class="dt">x =</span> <span class="st">&quot;Fork length (cm)&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb371-3" title="3"><span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb371-4" title="4"><span class="st">  </span><span class="kw">geom_rug</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb371-5" title="5"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..),</a>
<a class="sourceLine" id="cb371-6" title="6">    <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>,</a>
<a class="sourceLine" id="cb371-7" title="7">    <span class="dt">alpha =</span> <span class="fl">0.3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb371-8" title="8"><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> dnorm,</a>
<a class="sourceLine" id="cb371-9" title="9">    <span class="dt">args =</span> <span class="kw">list</span>(</a>
<a class="sourceLine" id="cb371-10" title="10">      <span class="dt">mean =</span> <span class="kw">mean</span>(Dam10dat<span class="op">$</span>fklngth),</a>
<a class="sourceLine" id="cb371-11" title="11">      <span class="dt">sd =</span> <span class="kw">sd</span>(Dam10dat<span class="op">$</span>fklngth)),</a>
<a class="sourceLine" id="cb371-12" title="12">    <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb371-13" title="13"></a>
<a class="sourceLine" id="cb371-14" title="14"><span class="co">#display graph, by year</span></a>
<a class="sourceLine" id="cb371-15" title="15">mygraph<span class="op">+</span><span class="kw">facet_wrap</span>(<span class="op">~</span>year,<span class="dt">ncol=</span><span class="dv">2</span>)</a></code></pre></div>
<div class="figure"><span id="fig:ano-2"></span>
<img src="Labo_BIO4558_files/figure-html/ano-2-1.svg" alt="Distribution de la longueur des esturgeons par année" width="672" />
<p class="caption">
Figure 5.1: Distribution de la longueur des esturgeons par année
</p>
</div>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb372-1" title="1"><span class="kw">boxplot</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> Dam10dat)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-203"></span>
<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-203-1.svg" alt="Boxplot de la longueur pas annéee" width="672" />
<p class="caption">
Figure 5.2: Boxplot de la longueur pas annéee
</p>
</div>
<p>Il semble que la taille des esturgeons est un peu plus petite après la construction du barrage, mais les données sont très variables et les effets ne sont pas parfaitement clairs. Il y a peut-être des problèmes de normalité avec les échantillons de 1954 et 1966, et il y a probablement des valeurs extrêmes dans les échantillons de 1958 et 1966. On va continuer en testant les conditions d’application de l’ANOVA. Il faut d’abord faire l’analyse et examiner les résidus.</p>
</div>
<div id="vérifier-les-conditions-dapplication-de-lanova-paramétrique" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Vérifier les conditions d’application de l’ANOVA paramétrique</h3>
<p>L’ANOVA paramétrique a trois conditions principales d’application : 1) les résidus sont normalement distribués, 2) la variance des résidus est égale dans tous les traitements (homoscédasticité) et 3) les résidus sont indépendants les uns des autres. Ces conditions doivent être remplies avant qu’on puisse se fier aux résultats de l’ANOVA paramétrique.</p>
<ul>
<li>Faites une ANOVA à un critère de classification sur fklngth par année et produisez les graphiques diagnostiques</li>
</ul>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" title="1"><span class="co"># Fit anova model and plot residual diagnostics</span></a>
<a class="sourceLine" id="cb373-2" title="2">anova.model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data=</span>Dam10dat)</a>
<a class="sourceLine" id="cb373-3" title="3"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb373-4" title="4"><span class="kw">plot</span>(anova.model1)</a></code></pre></div>
<div class="figure"><span id="fig:ano-3"></span>
<img src="Labo_BIO4558_files/figure-html/ano-3-1.svg" alt="Conditions d'applications de l'ANOVA" width="672" />
<p class="caption">
Figure 5.3: Conditions d’applications de l’ANOVA
</p>
</div>

<div class="rmdwarning">
<p>Faire attention dans le cadre d’une ANOVA à ce que la variable indépendante soit bien un facteur <strong>factor</strong>. Si la variable indépendante est reconnu comme du texte <strong>character</strong> alors vous n’obtiendrez que 3 graphiques et un message d’erreur du type:</p>
<p>`hat values (leverages) are all = 0.1</p>
and there are no factor predictors; no plot no. 5`
</div>

<p>D’après les graphiques, on peut douter de la normalité et de l’homogénéité des variances. Notez qu’il y a un point qui ressort vraiment avec une forte valeur résiduelle (cas numéro 59) et qu’il ne s’aligne pas bien avec les autres valeurs: c’est la valeur extrême qui avait été détectée plus tôt. Ce point fera sans doute gonfler la variance résiduelle du groupe auquel il appartient.</p>
<p>Des tests formels nous confirmeront ou infirmeront nos conclusions faites à partir de ces graphiques.</p>
<ul>
<li>Faites un test de normalité sur les résidus de l’ANOVA.</li>
</ul>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb374-1" title="1"><span class="kw">shapiro.test</span>(<span class="kw">residuals</span>(anova.model1))</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(anova.model1)
## W = 0.91571, p-value = 1.63e-06</code></pre>
<p>Ce test confirme nos soupçons: les résidus ne sont pas distribués normalement. Il faut cependant garder à l’esprit que la puissance est grande et que même de petites déviations de la normalité sont suffisantes pour rejeter l’hypothèse nulle.</p>
<ul>
<li>Ensuite, éprouvez l’hypothèse d’égalité des variances (homoscedasticité):</li>
</ul>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" title="1"><span class="kw">leveneTest</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data=</span>Dam10dat)</a></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value  Pr(&gt;F)  
## group   3  2.8159 0.04234 *
##       114                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La valeur de p vous dit que vous pouvez rejeter l’hypothèse nulle qu’il n’y a aucune différence dans les variances entre les années. Alors, nous concluons que les variances ne sont pas homogènes.</p>
</div>
<div id="faire-lanova" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Faire l’ANOVA</h3>
<ul>
<li>Faites une ANOVA de fklnght en choisissant / en présumant pour l’instant que les conditions d’application sont suffisamment remplies. Que concluez-vous?</li>
</ul>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb378-1" title="1"><span class="kw">summary</span>(anova.model1)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fklngth ~ year, data = Dam10dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.2116  -2.6866  -0.7116   2.2103  26.7885 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  48.0243     0.8566  56.061  &lt; 2e-16 ***
## year1958      0.1872     1.3335   0.140  0.88859    
## year1965     -5.5077     1.7310  -3.182  0.00189 ** 
## year1966     -3.3127     1.1684  -2.835  0.00542 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.211 on 114 degrees of freedom
## Multiple R-squared:  0.1355, Adjusted R-squared:  0.1128 
## F-statistic: 5.957 on 3 and 114 DF,  p-value: 0.0008246</code></pre>
<ul>
<li><em>Coefficients: Estimates</em> Les 4 coefficients peuvent être utilisés pour obtenir les valeurs prédites par le modèle (i.e. les moyennes de chaque groupe). La fklngth moyenne de la première année (1954) est 48.0243. Les coefficients pour les 3 autres années sont la différence entre la moyenne de l’année en question et la moyenne de 1954. La moyenne pour 1965 est 48.0243-5.5077=42.5166. Pour chaque coefficient, on a également accès à l’erreur-type, une valeur de t et la probabilité qui lui est associée (H0 que le coefficient est 0). Les poissons étaient plus petits après la construction du barrage qu’en 1954. Vous devez prendre ces p-valeurs avec un grain de sel, car elles ne sont pas corrigées pour les comparaisons multiples et. En général, je porte peu d’attention à cette partie des résultats imprimés et me concentre sur ce qui suit.</li>
<li><em>Residual standard error</em>: La racine carrée de la variance des résidus (valeurs observées moins valeurs prédites) qui correspond à la variabilité inexpliquée par le modèle (variation de la taille des poissons capturés la même année).</li>
<li><em>Mutiple R-squared</em> Le R-carré est la proportion de la variabilité de la variable dépendante qui peut être expliquée par le modèle. Ici, le modèle explique 13.5% de la variabilité. Les différences de taille d’une année à l’autre sont relativement petites lorsqu’on les compare à la variation de taille entre les poissons capturés la même année.</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li><em>F-Statistic</em> La p-valeur associée au test “omnibus” que toutes les moyennes sont égales. Ici, p est beaucoup plus petit que 0.05 et on rejetterait H0 pour conclure que fklngth varie selon les années.</li>
</ol>
<p>La commande <code>anova()</code> produit le tableau d’ANOVA standard qui contient la plupart de cette information:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" title="1"><span class="kw">anova</span>(anova.model1)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: fklngth
##            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## year        3  485.26 161.755  5.9574 0.0008246 ***
## Residuals 114 3095.30  27.152                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La variabilité totale de <code>fklngth</code>, mesurée par la somme des carrés des écarts (Sum sq) est partitionnée en ce qui peut être expliqué par l’année (485.26) et la variabilité résiduelle inexpliquée (3095.30). L’année explique bien (485.26/(3095.30+485.26)=.1355 or 13.55% de la variabilité). Le carré moyen des résidus (Residual Mean Sq) est leur variance.</p>
</div>
<div id="les-comparaisons-multiples" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Les comparaisons multiples</h3>
<ul>
<li>La fonction <code>pairwise.t.test()</code> peut être utilisée pour comparer des moyennes et ajuster (ou non, si désiré) les probabilités pour le nombre de comparaisons en utilisant l’une des options pour p.adj:</li>
</ul>
<p>Compare toutes les moyennes sans ajuster les probabilités</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb382-1" title="1"><span class="kw">pairwise.t.test</span>(Dam10dat<span class="op">$</span>fklngth, Dam10dat<span class="op">$</span>year,</a>
<a class="sourceLine" id="cb382-2" title="2">  <span class="dt">p.adj =</span> <span class="st">&quot;none&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Dam10dat$fklngth and Dam10dat$year 
## 
##      1954   1958   1965  
## 1958 0.8886 -      -     
## 1965 0.0019 0.0022 -     
## 1966 0.0054 0.0079 0.1996
## 
## P value adjustment method: none</code></pre>
<p>Option <code>bonf</code> ajuste les p-valeurs avec la correction de Bonferroni. Ici, il y a 6 valeurs de p calculées, et la correction de Bonferroni revient à simplement multiplier la p-valeur par 6 (sauf si le résultat est supérieur à 1. Si tel est le cas, la <code>p-value</code> ajustée est 1).</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb384-1" title="1"><span class="kw">pairwise.t.test</span>(Dam10dat<span class="op">$</span>fklngth, Dam10dat<span class="op">$</span>year,</a>
<a class="sourceLine" id="cb384-2" title="2">  <span class="dt">p.adj =</span> <span class="st">&quot;bonf&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Dam10dat$fklngth and Dam10dat$year 
## 
##      1954  1958  1965 
## 1958 1.000 -     -    
## 1965 0.011 0.013 -    
## 1966 0.033 0.047 1.000
## 
## P value adjustment method: bonferroni</code></pre>
<p>Option “holm” is est la correction séquentielle de Bonferroni dans laquelle les p-valeurs sont ordonnées de (i=1) la plus faible à (N) la plus grande. La correction pour les p-valeurs est (N-i+1). Ici, il y a N=6 paires de moyennes qui sont comparées. La plus petite valeur de p non corrigée est 0.0019 pour 1954 vs 1965. La p-valeur corrigée est donc <span class="math inline">\(0.0019*(6-1+1)=0.011\)</span>. La seconde plus petite p-valeur est 0.0022. Sa p-valeur corrigée est 0.0022*(6-2+1)=0.011. Pour la p-valeur la plus élevée, la correction est (N-N+1)=1, donc la p-valeur corrigée est égale à la p-valeur brute.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb386-1" title="1"><span class="kw">pairwise.t.test</span>(Dam10dat<span class="op">$</span>fklngth, Dam10dat<span class="op">$</span>year,</a>
<a class="sourceLine" id="cb386-2" title="2">  <span class="dt">p.adj =</span> <span class="st">&quot;holm&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Dam10dat$fklngth and Dam10dat$year 
## 
##      1954  1958  1965 
## 1958 0.889 -     -    
## 1965 0.011 0.011 -    
## 1966 0.022 0.024 0.399
## 
## P value adjustment method: holm</code></pre>
<p>L’option “fdr” sert à contrôler le “false discovery rate”.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb388-1" title="1"><span class="kw">pairwise.t.test</span>(Dam10dat<span class="op">$</span>fklngth, Dam10dat<span class="op">$</span>year,</a>
<a class="sourceLine" id="cb388-2" title="2">  <span class="dt">p.adj =</span> <span class="st">&quot;fdr&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Dam10dat$fklngth and Dam10dat$year 
## 
##      1954   1958   1965  
## 1958 0.8886 -      -     
## 1965 0.0066 0.0066 -     
## 1966 0.0108 0.0119 0.2395
## 
## P value adjustment method: fdr</code></pre>
<p>Les quatre méthodes mènent ici à la même conclusion: les poissons sont plus gros après la construction du barrage et toutes les comparaisons entre les années 50 et 60 sont significatives alors que les différences entre 54 et 58 ou 65 et 66 ne le sont pas. La conclusion ne dépend pas du choix de méthode.</p>
<p>Dans d’autres situations, vous pourriez obtenir des résultats contradictoires. Alors, quelle méthode choisir? Les p-valeurs qui ne sont pas corrigées sont certainement suspectes lorsqu’il y a plusieurs comparaisons. D’un autre coté, la correction de Bonferroni est conservatrice et le devient encore plus lorsqu’il y a de très nombreuses comparaisons. Des travaux récents suggèrent que la correction fdr est un bon compromis lorsqu’il y a beaucoup de comparaisons.</p>
<p>La méthode de Tukey est l’une des plus populaires et est facile à utiliser en R (notez cependant qu’il y a un petit bug qui se manifeste quand la variable indépendante peut ressembler à un nombre plutôt qu’un facteur, ce qui explique la petite pirouette avec <code>paste0</code> dans le code):</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb390-1" title="1">Dam10dat<span class="op">$</span>myyear &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">paste0</span>(<span class="st">&quot;m&quot;</span>, Dam10dat<span class="op">$</span>year))</a>
<a class="sourceLine" id="cb390-2" title="2"><span class="kw">TukeyHSD</span>(<span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> Dam10dat))</a></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = fklngth ~ myyear, data = Dam10dat)
## 
## $myyear
##                   diff        lwr        upr     p adj
## m1958-m1954  0.1872141  -3.289570  3.6639986 0.9990071
## m1965-m1954 -5.5076577 -10.021034 -0.9942809 0.0100528
## m1966-m1954 -3.3126964  -6.359223 -0.2661701 0.0274077
## m1965-m1958 -5.6948718 -10.436304 -0.9534397 0.0116943
## m1966-m1958 -3.4999106  -6.875104 -0.1247171 0.0390011
## m1966-m1965  2.1949612  -2.240630  6.6305526 0.5710111</code></pre>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" title="1"><span class="kw">plot</span>(<span class="kw">TukeyHSD</span>(<span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> Dam10dat)))</a></code></pre></div>
<div class="figure"><span id="fig:ano-13"></span>
<img src="Labo_BIO4558_files/figure-html/ano-13-1.svg" alt="Différence anuelles dans la longueur des esturgeons" width="672" />
<p class="caption">
Figure 5.4: Différence anuelles dans la longueur des esturgeons
</p>
</div>
<p>Les intervalles de confiance, corrigés pour les comparaisons multiples par la méthode de Tukey, sont illustrés pour les différences entre années. Malheureusement les légendes ne sont pas complètes, mais l’ordre est le même que dans le tableau précédent.</p>
<p>Le package multcomp peut produire de meilleurs graphiques, mais requiert un peu plus de code:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb393-1" title="1"><span class="co"># Alternative way to compute Tukey multiple comparisons</span></a>
<a class="sourceLine" id="cb393-2" title="2"><span class="co"># set up a one-way ANOVA</span></a>
<a class="sourceLine" id="cb393-3" title="3">anova.fkl.vs.year &lt;-<span class="st"> </span><span class="kw">aov</span>(<span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> Dam10dat))</a>
<a class="sourceLine" id="cb393-4" title="4"><span class="co"># set up all-pairs comparisons for factor `year&#39;</span></a>
<a class="sourceLine" id="cb393-5" title="5"></a>
<a class="sourceLine" id="cb393-6" title="6">meandiff &lt;-<span class="st"> </span><span class="kw">glht</span>(anova.fkl.vs.year, <span class="dt">linfct =</span> <span class="kw">mcp</span>(<span class="dt">myyear =</span></a>
<a class="sourceLine" id="cb393-7" title="7"><span class="st">&quot;Tukey&quot;</span>))</a>
<a class="sourceLine" id="cb393-8" title="8"><span class="kw">confint</span>(meandiff)</a></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = aov(fklngth ~ myyear, data = Dam10dat))
## 
## Quantile = 2.5941
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                    Estimate lwr      upr     
## m1958 - m1954 == 0   0.1872  -3.2720   3.6464
## m1965 - m1954 == 0  -5.5077  -9.9982  -1.0171
## m1966 - m1954 == 0  -3.3127  -6.3438  -0.2816
## m1965 - m1958 == 0  -5.6949 -10.4123  -0.9774
## m1966 - m1958 == 0  -3.4999  -6.8580  -0.1418
## m1966 - m1965 == 0   2.1950  -2.2182   6.6081</code></pre>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb395-1" title="1"><span class="kw">plot</span>(meandiff)</a></code></pre></div>
<div class="figure"><span id="fig:ano-14"></span>
<img src="Labo_BIO4558_files/figure-html/ano-14-1.svg" alt="Différence anuelles dans la longueur des esturgeons" width="672" />
<p class="caption">
Figure 5.5: Différence anuelles dans la longueur des esturgeons
</p>
</div>
<p>C’est un peu mieux, mais ce qui le serait encore plus c’est un graphique des moyennes, avec leurs intervalles de confiance ajustés pour les comparaisons multiples:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb396-1" title="1"><span class="co"># Compute and plot means and Tukey CI</span></a>
<a class="sourceLine" id="cb396-2" title="2">means &lt;-<span class="st"> </span><span class="kw">glht</span>(</a>
<a class="sourceLine" id="cb396-3" title="3">  anova.fkl.vs.year,</a>
<a class="sourceLine" id="cb396-4" title="4">  <span class="dt">linfct =</span> <span class="kw">mcp</span>(<span class="dt">myyear =</span> <span class="st">&quot;Tukey&quot;</span>))</a>
<a class="sourceLine" id="cb396-5" title="5">cimeans &lt;-<span class="st"> </span><span class="kw">cld</span>(means)</a>
<a class="sourceLine" id="cb396-6" title="6"><span class="co"># use sufficiently large upper margin</span></a>
<a class="sourceLine" id="cb396-7" title="7"><span class="co"># plot</span></a>
<a class="sourceLine" id="cb396-8" title="8">old.par&lt;-<span class="kw">par</span>(<span class="dt">mai=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="fl">1.25</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb396-9" title="9"><span class="kw">plot</span>(cimeans)</a></code></pre></div>
<div class="figure"><span id="fig:ano-15"></span>
<img src="Labo_BIO4558_files/figure-html/ano-15-1.svg" alt="Différence anuelles dans la longueur des esturgeons" width="672" />
<p class="caption">
Figure 5.6: Différence anuelles dans la longueur des esturgeons
</p>
</div>
<p>Notez les lettres au dessus du graphique: les années étiquetées avec la même lettre ne diffèrent pas significativement l’une de l’autre.</p>
</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="set-ano.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="transformations-de-données-et-anova-non-paramétrique.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/BIO4558_uOttawa_lab_manual/05-anova.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labo_BIO4558.pdf", "Labo_BIO4558.epub", "Labo_BIO4558.mobi"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
