<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Introduction à R | BIO4558 Biostatistiques appliquées avec R</title>
  <meta name="description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Introduction à R | BIO4558 Biostatistiques appliquées avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/missing.png" />
  <meta property="og:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="github-repo" content="JulienGAMartin/BIO4558_uOttawa_lab_manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Introduction à R | BIO4558 Biostatistiques appliquées avec R" />
  
  <meta name="twitter:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="twitter:image" content="images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="préface.html"/>
<link rel="next" href="analyse-de-puissance-avec-r-et-gpower.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4558 Manuel de laboratoire</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a><ul>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#quelques-points-importants-à-retenir"><i class="fa fa-check"></i>Quelques points importants à retenir</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours"><i class="fa fa-check"></i>Qu’est-ce que R et pourquoi l’utiliser dans ce cours?</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#installation-des-logiciels-nécessaires"><i class="fa fa-check"></i>Installation des logiciels nécessaires</a><ul>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#rstudio"><i class="fa fa-check"></i>Rstudio</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#paquets-pour-r"><i class="fa fa-check"></i>Paquets pour R</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#instructions-générales-pour-les-laboratoires"><i class="fa fa-check"></i>Instructions générales pour les laboratoires</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#notes-sur-le-manuel"><i class="fa fa-check"></i>Notes sur le manuel</a><ul>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html#licence"><i class="fa fa-check"></i>Licence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-à-r.html"><a href="introduction-à-r.html"><i class="fa fa-check"></i><b>1</b> Introduction à R</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#objectifs-labo-1"><i class="fa fa-check"></i><b>1.1</b> Objectifs Labo 1</a><ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#set-intro"><i class="fa fa-check"></i><b>1.1.1</b> Paquets et données requises pour le labo</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-à-r.html"><a href="introduction-à-r.html#premier-pas-avec-r"><i class="fa fa-check"></i><b>1.2</b> Premier pas avec R</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#la-console"><i class="fa fa-check"></i><b>1.2.1</b> La console</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-à-r.html"><a href="introduction-à-r.html#objets"><i class="fa fa-check"></i><b>1.2.2</b> Objets</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-à-r.html"><a href="introduction-à-r.html#vecteurs"><i class="fa fa-check"></i><b>1.2.3</b> Vecteurs</a></li>
<li class="chapter" data-level="1.2.4" data-path="introduction-à-r.html"><a href="introduction-à-r.html#fonctions"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions</a></li>
<li class="chapter" data-level="1.2.5" data-path="introduction-à-r.html"><a href="introduction-à-r.html#regrouper-ses-commandes-dans-des-scripts"><i class="fa fa-check"></i><b>1.2.5</b> Regrouper ses commandes dans des scripts</a></li>
<li class="chapter" data-level="1.2.6" data-path="introduction-à-r.html"><a href="introduction-à-r.html#packages"><i class="fa fa-check"></i><b>1.2.6</b> Installer et charger des extensions (<em>packages</em>)</a></li>
<li class="chapter" data-level="1.2.7" data-path="introduction-à-r.html"><a href="introduction-à-r.html#ex-introR"><i class="fa fa-check"></i><b>1.2.7</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-à-r.html"><a href="introduction-à-r.html#premier-travail-avec-des-données"><i class="fa fa-check"></i><b>1.3</b> Premier travail avec des données</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#jeu-de-données-dexemple"><i class="fa fa-check"></i><b>1.3.1</b> Jeu de données d’exemple</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction-à-r.html"><a href="introduction-à-r.html#tableau-de-données-data-frame"><i class="fa fa-check"></i><b>1.3.2</b> Tableau de données (<em>data frame</em>)</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction-à-r.html"><a href="introduction-à-r.html#analyse-univariée"><i class="fa fa-check"></i><b>1.3.3</b> Analyse univariée</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction-à-r.html"><a href="introduction-à-r.html#ex-introR-univ"><i class="fa fa-check"></i><b>1.3.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction-à-r.html"><a href="introduction-à-r.html#analyse-de-2-variables"><i class="fa fa-check"></i><b>1.4</b> Analyse de 2 variables</a><ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#croisement-de-deux-variables-qualitatives"><i class="fa fa-check"></i><b>1.4.1</b> Croisement de deux variables qualitatives</a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-à-r.html"><a href="introduction-à-r.html#croisement-dune-variable-quantitative-et-dune-variable-qualitative"><i class="fa fa-check"></i><b>1.4.2</b> Croisement d’une variable quantitative et d’une variable qualitative</a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-à-r.html"><a href="introduction-à-r.html#croisement-de-deux-variables-quantitatives"><i class="fa fa-check"></i><b>1.4.3</b> Croisement de deux variables quantitatives</a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-à-r.html"><a href="introduction-à-r.html#ex-introR-biv"><i class="fa fa-check"></i><b>1.4.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-à-r.html"><a href="introduction-à-r.html#gérer-les-données"><i class="fa fa-check"></i><b>1.5</b> Gérer les données</a><ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-à-r.html"><a href="introduction-à-r.html#importer-et-exporter-des-données"><i class="fa fa-check"></i><b>1.5.1</b> Importer et exporter des données</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction-à-r.html"><a href="introduction-à-r.html#examen-préliminaire-des-données"><i class="fa fa-check"></i><b>1.5.2</b> Examen préliminaire des données</a></li>
<li class="chapter" data-level="1.5.3" data-path="introduction-à-r.html"><a href="introduction-à-r.html#créer-des-sous-ensembles-de-cas"><i class="fa fa-check"></i><b>1.5.3</b> Créer des sous-ensembles de cas</a></li>
<li class="chapter" data-level="1.5.4" data-path="introduction-à-r.html"><a href="introduction-à-r.html#transformations-de-données"><i class="fa fa-check"></i><b>1.5.4</b> Transformations de données</a></li>
<li class="chapter" data-level="1.5.5" data-path="introduction-à-r.html"><a href="introduction-à-r.html#exercice-sur-r"><i class="fa fa-check"></i><b>1.5.5</b> Exercice sur R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html"><i class="fa fa-check"></i><b>2</b> Analyse de puissance avec R et G*Power</a><ul>
<li class="chapter" data-level="2.1" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#la-théorie"><i class="fa fa-check"></i><b>2.1</b> La théorie</a><ul>
<li class="chapter" data-level="2.1.1" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#quest-ce-que-la-puissance"><i class="fa fa-check"></i><b>2.1.1</b> Qu’est-ce que la puissance?</a></li>
<li class="chapter" data-level="2.1.2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#pourquoi-faire-une-analyse-de-puissance"><i class="fa fa-check"></i><b>2.1.2</b> Pourquoi faire une analyse de puissance?</a></li>
<li class="chapter" data-level="2.1.3" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#facteurs-qui-affectent-la-puissance"><i class="fa fa-check"></i><b>2.1.3</b> Facteurs qui affectent la puissance</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#quest-ce-que-gpower"><i class="fa fa-check"></i><b>2.2</b> Qu’est ce que G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#comment-utiliser-gpower"><i class="fa fa-check"></i><b>2.3</b> Comment utiliser G*Power</a><ul>
<li class="chapter" data-level="2.3.1" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#principe-général"><i class="fa fa-check"></i><b>2.3.1</b> Principe général</a></li>
<li class="chapter" data-level="2.3.2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#types-danalyses-de-puissance-disponibles"><i class="fa fa-check"></i><b>2.3.2</b> Types d’analyses de puissance disponibles</a></li>
<li class="chapter" data-level="2.3.3" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#comment-calculer-la-taille-de-leffet-gpower-permet-de-faire-une-analyse-de-puissance-pour-de-nombreux-tests-statistiques"><i class="fa fa-check"></i><b>2.3.3</b> Comment calculer la taille de l’effet G*Power permet de faire une analyse de puissance pour de nombreux tests statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#puissance-pour-un-test-de-t-comparant-deux-moyennes"><i class="fa fa-check"></i><b>2.4</b> Puissance pour un test de t comparant deux moyennes</a><ul>
<li class="chapter" data-level="2.4.1" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#analyse-post-hoc"><i class="fa fa-check"></i><b>2.4.1</b> Analyse post-hoc</a></li>
<li class="chapter" data-level="2.4.2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#analyse-à-priori"><i class="fa fa-check"></i><b>2.4.2</b> Analyse à priori</a></li>
<li class="chapter" data-level="2.4.3" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#analyse-de-sensitivité---calculer-la-taille-deffet-détectable"><i class="fa fa-check"></i><b>2.4.3</b> Analyse de sensitivité - Calculer la taille d’effet détectable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#points-à-retenir"><i class="fa fa-check"></i><b>2.5</b> Points à retenir</a></li>
<li class="chapter" data-level="2.6" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html#ex-power"><i class="fa fa-check"></i><b>2.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html"><i class="fa fa-check"></i><b>3</b> Corrélation et régression linéaire simple</a><ul>
<li class="chapter" data-level="3.1" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#set-lm"><i class="fa fa-check"></i><b>3.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="3.2" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#diagrammes-de-dispersion"><i class="fa fa-check"></i><b>3.2</b> Diagrammes de dispersion</a></li>
<li class="chapter" data-level="3.3" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#transformations-et-le-coefficient-de-corrélation"><i class="fa fa-check"></i><b>3.3</b> Transformations et le coefficient de corrélation</a></li>
<li class="chapter" data-level="3.4" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#matrices-de-corrélations-et-correction-de-bonferroni"><i class="fa fa-check"></i><b>3.4</b> Matrices de corrélations et correction de Bonferroni</a></li>
<li class="chapter" data-level="3.5" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#corrélations-non-paramétriques-r-de-spearman-et-tau-de-kendall"><i class="fa fa-check"></i><b>3.5</b> Corrélations non paramétriques: r de Spearman et tau de Kendall</a></li>
<li class="chapter" data-level="3.6" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#régression-linéaire-simple"><i class="fa fa-check"></i><b>3.6</b> Régression linéaire simple</a><ul>
<li class="chapter" data-level="3.6.1" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#vérifier-les-conditions-dapplication-de-la-régression"><i class="fa fa-check"></i><b>3.6.1</b> Vérifier les conditions d’application de la régression</a></li>
<li class="chapter" data-level="3.6.2" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#tests-formels-des-conditions-dapplication-pour-la-régression"><i class="fa fa-check"></i><b>3.6.2</b> Tests formels des conditions d’application pour la régression</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#transformation-des-données-en-régression"><i class="fa fa-check"></i><b>3.7</b> Transformation des données en régression</a></li>
<li class="chapter" data-level="3.8" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#traitement-des-valeurs-extrèmes"><i class="fa fa-check"></i><b>3.8</b> Traitement des valeurs extrèmes</a></li>
<li class="chapter" data-level="3.9" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression"><i class="fa fa-check"></i><b>3.9</b> Quantifier la taille d’effet et analyse de puissance en régression</a><ul>
<li class="chapter" data-level="3.9.1" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#puissance-de-détecter-une-pente-donnée"><i class="fa fa-check"></i><b>3.9.1</b> Puissance de détecter une pente donnée</a></li>
<li class="chapter" data-level="3.9.2" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#effectif-requis-pour-atteindre-une-puissance-désirée-test-a-priori"><i class="fa fa-check"></i><b>3.9.2</b> Effectif requis pour atteindre une puissance désirée (test A-priori)</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html#bootstrap-en-régression-simple-avec-r"><i class="fa fa-check"></i><b>3.10</b> Bootstrap en régression simple avec R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html"><i class="fa fa-check"></i><b>4</b> Comparaison de deux échantillons</a><ul>
<li class="chapter" data-level="4.1" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#set-t"><i class="fa fa-check"></i><b>4.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="4.2" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#examen-visuel-des-données"><i class="fa fa-check"></i><b>4.2</b> Examen visuel des données</a></li>
<li class="chapter" data-level="4.3" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#comparer-les-moyennes-de-deux-échantillons-indépendants"><i class="fa fa-check"></i><b>4.3</b> Comparer les moyennes de deux échantillons indépendants</a></li>
<li class="chapter" data-level="4.4" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes"><i class="fa fa-check"></i><b>4.4</b> Bootstrap et tests de permutation pour comparer deux moyennes</a><ul>
<li class="chapter" data-level="4.4.1" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#comparer-les-moyennes-de-deux-échantillons-appariés"><i class="fa fa-check"></i><b>4.5</b> Comparer les moyennes de deux échantillons appariés</a></li>
<li class="chapter" data-level="4.6" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html#références"><i class="fa fa-check"></i><b>4.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html"><i class="fa fa-check"></i><b>5</b> ANOVA à un critère de classification</a><ul>
<li class="chapter" data-level="5.1" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#set-ano"><i class="fa fa-check"></i><b>5.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="5.2" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#anova-à-un-critère-de-classification-et-comparaisons-multiples"><i class="fa fa-check"></i><b>5.2</b> ANOVA à un critère de classification et comparaisons multiples</a><ul>
<li class="chapter" data-level="5.2.1" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#vérifier-les-conditions-dapplication-de-lanova-paramétrique"><i class="fa fa-check"></i><b>5.2.2</b> Vérifier les conditions d’application de l’ANOVA paramétrique</a></li>
<li class="chapter" data-level="5.2.3" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#faire-lanova"><i class="fa fa-check"></i><b>5.2.3</b> Faire l’ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#les-comparaisons-multiples"><i class="fa fa-check"></i><b>5.2.4</b> Les comparaisons multiples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#transformations-de-données-et-anova-non-paramétrique"><i class="fa fa-check"></i><b>5.3</b> Transformations de données et ANOVA non-paramétrique</a></li>
<li class="chapter" data-level="5.4" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#examen-des-valeurs-extrêmes"><i class="fa fa-check"></i><b>5.4</b> Examen des valeurs extrêmes</a></li>
<li class="chapter" data-level="5.5" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html#test-de-permutation"><i class="fa fa-check"></i><b>5.5</b> Test de permutation</a></li>
</ul></li>
<li class="appendix"><span><b>Appendice</b></span></li>
<li class="chapter" data-level="A" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html"><i class="fa fa-check"></i><b>A</b> Petit guide pour Rmarkdown</a><ul>
<li class="chapter" data-level="A.1" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html#syntaxe-markdown"><i class="fa fa-check"></i><b>A.1</b> Syntaxe Markdown</a><ul>
<li class="chapter" data-level="A.1.1" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html#titre-3"><i class="fa fa-check"></i><b>A.1.1</b> Titre 3</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html#à-propos-de-latex"><i class="fa fa-check"></i><b>A.2</b> À propos de LaTex</a></li>
<li class="chapter" data-level="A.3" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html#concernant-le-code-dans-notebook"><i class="fa fa-check"></i><b>A.3</b> Concernant le code dans notebook</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><a href="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><i class="fa fa-check"></i><b>B</b> Resources pour en apprendre plus sur rmarkdown</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4558 Biostatistiques appliquées avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-à-r" class="section level1">
<h1><span class="header-section-number">1</span> Introduction à R</h1>
<div id="objectifs-labo-1" class="section level2">
<h2><span class="header-section-number">1.1</span> Objectifs Labo 1</h2>
<p>Après avoir complété cet exercice de laboratoire, vous pourrez :
- Ouvrir des fichiers de données R déjà existants
- Importer des ensembles de données rectangulaires
- Exporter des donnes de R vers un fichier texte
- Vérifier si les données ont été correctement importées
- Examiner la distribution des observations d’une variable
- Examiner visuellement et tester la normalité d’une variable
- Calculer des statistiques descriptives d’une variable
- Effectuer des transformations de données</p>
<div id="set-intro" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Paquets et données requises pour le labo</h3>
<p>Ce laboratoire nécessite:</p>
<ul>
<li>les paquets R:
<ul>
<li>questionr</li>
<li>ggplot2</li>
</ul></li>
<li>les fichiers de données
<ul>
<li>ErablesGatineau.csv</li>
<li>sturgeon.csv</li>
</ul></li>
</ul>
</div>
</div>
<div id="premier-pas-avec-r" class="section level2">
<h2><span class="header-section-number">1.2</span> Premier pas avec R</h2>
<p>Une fois R et RStudio installés sur votre machine, nous n’allons pas lancer R mais plutôt RStudio.</p>
<p>RStudio n’est pas à proprement parler une interface graphique qui permettrait d’utiliser R de manière “classique” via la souris, des menus et des boîtes de dialogue. Il s’agit plutôt de ce qu’on appelle un <em>Environnement de développement intégré</em> (IDE) qui facilite l’utilisation de R et le développement de scripts (voir section <a href="préface.html#rstudio"><strong>??</strong></a>).</p>
<div id="la-console" class="section level3">
<h3><span class="header-section-number">1.2.1</span> La console</h3>
<div id="linvite-de-commandes" class="section level4">
<h4><span class="header-section-number">1.2.1.1</span> L’invite de commandes</h4>
<p>Au premier lancement de RStudio, l’écran principal est découpé en trois grandes zones :</p>
<div class="figure">
<img src="images/screenshots/rstudio_start.png" alt="Interface de Rstudio" />
<p class="caption">Interface de Rstudio</p>
</div>
<p>La zone de gauche se nomme <em>Console</em>. À son démarrage, RStudio a lancé une nouvelle session de R et c’est dans cette fenêtre que nous allons pouvoir interagir avec lui.</p>
<p>La <em>Console</em> doit normalement afficher un texte de bienvenue ressemblant à ceci :</p>
<pre><code>R version 4.0.0 (2020-04-24) -- &quot;Arbor Day&quot;
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R est un logiciel libre livré sans AUCUNE GARANTIE.
Vous pouvez le redistribuer sous certaines conditions.
Tapez &#39;license()&#39; ou &#39;licence()&#39; pour plus de détails.

R est un projet collaboratif avec de nombreux contributeurs.
Tapez &#39;contributors()&#39; pour plus d&#39;information et
&#39;citation()&#39; pour la façon de le citer dans les publications.

Tapez &#39;demo()&#39; pour des démonstrations, &#39;help()&#39; pour l&#39;aide
en ligne ou &#39;help.start()&#39; pour obtenir l&#39;aide au format HTML.
Tapez &#39;q()&#39; pour quitter R.</code></pre>
<p>suivi d’une ligne commençant par le caractère <code>&gt;</code> et sur laquelle devrait se trouver votre curseur. Cette ligne est appelée l’<em>invite de commande</em> (ou <em>prompt</em> en anglais). Elle signifie que R est disponible et en attente de votre prochaine commande.</p>
<p>Nous pouvons tout de suite lui fournir une première commande, en saisissant le texte suivant puis en appuyant sur <code>Entrée</code> :</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>R nous répond immédiatement, et nous pouvons constater avec soulagement qu’il sait faire des additions à un chiffre<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. On peut donc continuer avec d’autres opérations :</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="dv">5</span> <span class="op">-</span><span class="st"> </span><span class="dv">7</span></a></code></pre></div>
<pre><code>## [1] -2</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="dv">4</span> <span class="op">*</span><span class="st"> </span><span class="dv">12</span></a></code></pre></div>
<pre><code>## [1] 48</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="dv">-10</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span></a></code></pre></div>
<pre><code>## [1] -3.333333</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="dv">5</span><span class="op">^</span><span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 25</code></pre>
<p>Cette dernière opération utilise le symbole <code>^</code> qui représente l’opération <em>puissance</em>. <code>5^2</code> signifie donc “5 au carré”, soit 25.</p>
</div>
<div id="précisions-concernant-la-saisie-des-commandes" class="section level4">
<h4><span class="header-section-number">1.2.1.2</span> Précisions concernant la saisie des commandes</h4>
<p>Lorsqu’on saisit une commande, les espaces autour des opérateurs n’ont pas d’importance. Les trois commandes suivantes sont donc équivalentes, mais on privilégie en général la deuxième pour des raisons de lisibilité du code.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"><span class="dv">10</span><span class="op">+</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="dv">10</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb13-3" title="3"><span class="dv">10</span>       <span class="op">+</span><span class="st">       </span><span class="dv">2</span></a></code></pre></div>
<p>Quand vous êtes dans la console, vous pouvez utiliser les flèches vers le haut et vers le bas pour naviguer dans l’historique des commandes que vous avez tapées précédemment. Vous pouvez à tout moment modifier la commande affichée, et l’exécuter en appuyant sur <code>Entrée</code>.</p>
<p>Enfin, il peut arriver qu’on saisisse une commande de manière incomplète : oubli d’une parenthèse, faute de frappe, etc. Dans ce cas, R remplace l’invite de commande habituel par un signe <code>+</code> :</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="dv">4</span> <span class="op">*</span></a>
<a class="sourceLine" id="cb14-2" title="2"><span class="op">+</span></a></code></pre></div>
<p>Cela signifie qu’il “attend la suite”. On peut alors soit compléter la commande sur cette nouvelle ligne et appuyer sur <code>Entrée</code>, soit, si on est perdu, tout annuler et revenir à l’invite de commandes normal en appuyant sur <code>Esc</code> ou <code>Échap</code>.</p>
</div>
</div>
<div id="objets" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Objets</h3>
<div id="objets-simples" class="section level4">
<h4><span class="header-section-number">1.2.2.1</span> Objets simples</h4>
<p>Faire des calculs c’est bien, mais il serait intéressant de pouvoir stocker un résultat quelque part pour pouvoir le réutiliser ultérieurement sans avoir à faire du copier/coller.</p>
<p>Pour conserver le résultat d’une opération, on peut le stocker dans un <em>objet</em> à l’aide de l’opérateur d’assignation <code>&lt;-</code>. Cette “flèche” stocke ce qu’il y a à sa droite dans un objet dont le nom est indiqué à sa gauche.</p>
<p>Prenons tout de suite un exemple :</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1">x &lt;-<span class="st"> </span><span class="dv">2</span></a></code></pre></div>
<p>Cette commande peut se lire <em>“prend la valeur 2 et mets la dans un objet qui s’appelle <code>x</code>”</em>.</p>
<p>Si on exécute une commande comportant juste le nom d’un objet, R affiche son contenu :</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">x</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>On voit donc que notre objet <code>x</code> contient bien la valeur 2.</p>
<p>On peut évidemment réutiliser cet objet dans d’autres opérations. R le remplacera alors par sa valeur :</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1">x <span class="op">+</span><span class="st"> </span><span class="dv">4</span></a></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>On peut créer autant d’objets qu’on le souhaite.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1">x &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb20-2" title="2">y &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb20-3" title="3">resultat &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span>y</a>
<a class="sourceLine" id="cb20-4" title="4">resultat</a></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="rmdimportant">
<p>
Les noms d’objets peuvent contenir des lettres, des chiffres, les symboles <code>.</code> et <code>_</code>. Ils ne peuvent pas commencer par un chiffre. Attention, R fait la différence entre minuscules et majuscules dans les noms d’objets, ce qui signifie que <code>x</code> et <code>X</code> seront deux objets différents, tout comme <code>resultat</code> et <code>Resultat</code>.
</p>
<p>
De manière générale, il est préférable d’éviter les majuscules (pour les risques d’erreur) et les caractères accentués (pour des questions d’encodage) dans les noms d’objets.
</p>
<p>
De même, il faut essayer de trouver un équilibre entre clarté du nom (comprendre à quoi sert l’objet, ce qu’il contient) et sa longueur. Par exemple, on préfèrera comme nom d’objet <code>taille_conj1</code> à <code>taille_du_conjoint_numero_1</code> (trop long) ou à <code>t1</code> (pas assez explicite).
</p>
</div>
<p>Quand on assigne une nouvelle valeur à un objet déjà existant, la valeur précédente est perdue. Les objets n’ont pas de mémoire.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1">x &lt;-<span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb22-2" title="2">x &lt;-<span class="st"> </span><span class="dv">5</span></a>
<a class="sourceLine" id="cb22-3" title="3">x</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>De la même manière, assigner un objet à un autre ne crée pas de “lien” entre les deux. Cela copie juste la valeur de l’objet de droite dans celui de gauche :</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">x &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb24-2" title="2">y &lt;-<span class="st"> </span><span class="dv">3</span></a>
<a class="sourceLine" id="cb24-3" title="3">x &lt;-<span class="st"> </span>y</a>
<a class="sourceLine" id="cb24-4" title="4">x</a></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1"><span class="co">## Si on modifie y, cela ne modifie pas x</span></a>
<a class="sourceLine" id="cb26-2" title="2">y &lt;-<span class="st"> </span><span class="dv">4</span></a>
<a class="sourceLine" id="cb26-3" title="3">x</a></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>On le verra, les objets peuvent contenir tout un tas d’informations. Jusqu’ici on n’a stocké que des nombres, mais ils peuvent aussi contenir des chaînes de caractères (du texte), qu’on délimite avec des guillemets simples ou doubles (<code>'</code> ou <code>"</code>) :</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1">chien &lt;-<span class="st"> &quot;Chihuahua&quot;</span></a>
<a class="sourceLine" id="cb28-2" title="2">chien</a></code></pre></div>
<pre><code>## [1] &quot;Chihuahua&quot;</code></pre>
</div>
</div>
<div id="vecteurs" class="section level3">
<h3><span class="header-section-number">1.2.3</span> Vecteurs</h3>
<p>Imaginons maintenant qu’on a demandé la taille en centimètres de 5 personnes et qu’on souhaite calculer leur taille moyenne. On pourrait créer autant d’objets que de tailles et faire l’opération mathématique qui va bien :</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1">taille1 &lt;-<span class="st"> </span><span class="dv">156</span></a>
<a class="sourceLine" id="cb30-2" title="2">taille2 &lt;-<span class="st"> </span><span class="dv">164</span></a>
<a class="sourceLine" id="cb30-3" title="3">taille3 &lt;-<span class="st"> </span><span class="dv">197</span></a>
<a class="sourceLine" id="cb30-4" title="4">taille4 &lt;-<span class="st"> </span><span class="dv">147</span></a>
<a class="sourceLine" id="cb30-5" title="5">taille5 &lt;-<span class="st"> </span><span class="dv">173</span></a>
<a class="sourceLine" id="cb30-6" title="6">(taille1 <span class="op">+</span><span class="st"> </span>taille2 <span class="op">+</span><span class="st"> </span>taille3 <span class="op">+</span><span class="st"> </span>taille4 <span class="op">+</span><span class="st"> </span>taille5) <span class="op">/</span><span class="st"> </span><span class="dv">5</span></a></code></pre></div>
<pre><code>## [1] 167.4</code></pre>
<p>Cette manière de faire n’est évidemment pas pratique du tout. On va plutôt stocker l’ensemble de nos tailles dans un seul objet, de type <em>vecteur</em>, avec la syntaxe suivante :</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">tailles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">156</span>, <span class="dv">164</span>, <span class="dv">197</span>, <span class="dv">147</span>, <span class="dv">173</span>)</a></code></pre></div>
<p>Si on affiche le contenu de cet objet, on voit qu’il contient bien l’ensemble des tailles saisies :</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">tailles</a></code></pre></div>
<pre><code>## [1] 156 164 197 147 173</code></pre>
<p>Un <em>vecteur</em> dans R est un objet qui peut contenir plusieurs informations du même type, potentiellement en très grand nombre.</p>
<p>L’avantage d’un vecteur est que lorsqu’on lui applique une opération, celle-ci s’applique à toutes les valeurs qu’il contient. Ainsi, si on veut la taille en mètres plutôt qu’en centimètres, on peut faire :</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1">tailles_m &lt;-<span class="st"> </span>tailles <span class="op">/</span><span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb35-2" title="2">tailles_m</a></code></pre></div>
<pre><code>## [1] 1.56 1.64 1.97 1.47 1.73</code></pre>
<p>Cela fonctionne pour toutes les opérations de base :</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">tailles <span class="op">+</span><span class="st"> </span><span class="dv">10</span></a></code></pre></div>
<pre><code>## [1] 166 174 207 157 183</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">tailles<span class="op">^</span><span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 24336 26896 38809 21609 29929</code></pre>
<p>Imaginons maintenant qu’on a aussi demandé aux cinq mêmes personnes leur poids en kilos. On peut alors créer un deuxième vecteur :</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">poids &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">59</span>, <span class="dv">110</span>, <span class="dv">44</span>, <span class="dv">88</span>)</a></code></pre></div>
<p>On peut alors effectuer des calculs utilisant nos deux vecteurs <code>tailles</code> et <code>poids</code>. On peut par exemple calculer l’indice de masse corporelle (IMC) de chacun de nos enquêtés en divisant leur poids en kilo par leur taille en mètre au carré :</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1">imc &lt;-<span class="st"> </span>poids <span class="op">/</span><span class="st"> </span>(tailles <span class="op">/</span><span class="st"> </span><span class="dv">100</span>) <span class="op">^</span><span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb42-2" title="2">imc</a></code></pre></div>
<pre><code>## [1] 18.49112 21.93635 28.34394 20.36189 29.40292</code></pre>
<p>Un vecteur peut contenir des nombres, mais il peut aussi contenir du texte. Imaginons qu’on a demandé aux 5 mêmes personnes leur niveau de diplôme : on peut regrouper l’information dans un vecteur de <em>chaînes de caractères</em>. Une chaîne de caractère contient du texte libre, délimité par des guillemets simples ou doubles :</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1">diplome &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;CAP&quot;</span>, <span class="st">&quot;Bac&quot;</span>, <span class="st">&quot;Bac+2&quot;</span>, <span class="st">&quot;CAP&quot;</span>, <span class="st">&quot;Bac+3&quot;</span>)</a>
<a class="sourceLine" id="cb44-2" title="2">diplome</a></code></pre></div>
<pre><code>## [1] &quot;CAP&quot;   &quot;Bac&quot;   &quot;Bac+2&quot; &quot;CAP&quot;   &quot;Bac+3&quot;</code></pre>
<p>L’opérateur <code>:</code>, lui, permet de générer rapidement un vecteur comprenant tous les nombres entre deux valeurs, opération assez courante sous R :</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></a>
<a class="sourceLine" id="cb46-2" title="2">x</a></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<p>Enfin, notons qu’on peut accéder à un élément particulier d’un vecteur en faisant suivre le nom du vecteur de crochets contenant le numéro de l’élément désiré. Par exemple :</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">diplome[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>## [1] &quot;Bac&quot;</code></pre>
<p>Cette opération, qui utilise l’opérateur <code>[]</code>, permet donc la sélection d’éléments d’un vecteur.</p>
<p>Dernière remarque, si on affiche dans la console un vecteur avec beaucoup d’éléments, ceux-ci seront répartis sur plusieurs lignes. Par exemple, si on a un vecteur de 50 nombres on peut obtenir quelque chose comme :</p>
<pre><code> [1] 294 425 339 914 114 896 716 648 915 587 181 926 489
[14] 848 583 182 662 888 417 133 146 322 400 698 506 944
[27] 237 324 333 443 487 658 793 288 897 588 697 439 697
[40] 914 694 126 969 744 927 337 439 226 704 635</code></pre>
<p>On remarque que R ajoute systématiquement un nombre entre crochets au début de chaque ligne : il s’agit en fait de la position du premier élément de la ligne dans le vecteur. Ainsi, le 848 de la deuxième ligne est le 14e élément du vecteur, le 914 de la dernière ligne est le 40e, etc.</p>
<p>Ceci explique le <code>[1]</code> qu’on obtient quand on affiche un simple nombre<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> :</p>
<pre><code> [1] 4</code></pre>
</div>
<div id="fonctions" class="section level3">
<h3><span class="header-section-number">1.2.4</span> Fonctions</h3>
<div id="principe" class="section level4">
<h4><span class="header-section-number">1.2.4.1</span> Principe</h4>
<p>Nous savons désormais effectuer des opérations arithmétiques de base sur des nombres et des vecteurs, et stocker des valeurs dans des objets pour pouvoir les réutiliser plus tard.</p>
<p>Pour aller plus loin, nous devons aborder les <em>fonctions</em> qui sont, avec les objets, un deuxième concept de base de R. On utilise des fonctions pour effectuer des calculs, obtenir des résultats et accomplir des actions.</p>
<p>Formellement, une fonction a un <em>nom</em>, elle prend en entrée entre parenthèses un ou plusieurs <em>arguments</em> (ou <em>paramètres</em>), et retourne un <em>résultat</em>.</p>
<p>Prenons tout de suite un exemple. Si on veut connaître le nombre d’éléments du vecteur <code>tailles</code> que nous avons construit précédemment, on peut utiliser la fonction <code>length</code>, de cette manière :</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1"><span class="kw">length</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Ici, <code>length</code> est le nom de la fonction, on l’appelle en lui passant un argument entre parenthèses (en l’occurrence notre vecteur <code>tailles</code>), et elle nous renvoie un résultat, à savoir le nombre d’éléments du vecteur passé en paramètre.</p>
<p>Autre exemple, les fonctions <code>min</code> et <code>max</code> retournent respectivement les valeurs minimales et maximales d’un vecteur de nombres :</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">min</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 147</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="kw">max</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 197</code></pre>
<p>La fonction <code>mean</code> calcule et retourne la moyenne d’un vecteur de nombres :</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">mean</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 167.4</code></pre>
<p>La fonction <code>sum</code> retourne la somme de tous les éléments du vecteur :</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="kw">sum</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 837</code></pre>
<p>Jusqu’à présent on n’a vu que des fonctions qui calculent et retournent un unique nombre. Mais une fonction peut renvoyer d’autres types de résultats. Par exemple, la fonction <code>range</code> (étendue) renvoie un vecteur de deux nombres, le minimum et le maximum :</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">range</span>(tailles)</a></code></pre></div>
<pre><code>## [1] 147 197</code></pre>
<p>Ou encore, la fonction <code>unique</code>, qui supprime toutes les valeurs en double dans un vecteur, qu’il s’agisse de nombres ou de chaînes de caractères :</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">diplome &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;CAP&quot;</span>, <span class="st">&quot;Bac&quot;</span>, <span class="st">&quot;Bac+2&quot;</span>, <span class="st">&quot;CAP&quot;</span>, <span class="st">&quot;Bac+3&quot;</span>)</a>
<a class="sourceLine" id="cb64-2" title="2"><span class="kw">unique</span>(diplome)</a></code></pre></div>
<pre><code>## [1] &quot;CAP&quot;   &quot;Bac&quot;   &quot;Bac+2&quot; &quot;Bac+3&quot;</code></pre>
</div>
<div id="arguments" class="section level4">
<h4><span class="header-section-number">1.2.4.2</span> Arguments</h4>
<p>Une fonction peut prendre plusieurs arguments, dans ce cas on les indique toujours entre parenthèses, séparés par des virgules.</p>
<p>On a déjà rencontré un exemple de fonction acceptant plusieurs arguments : la fonction <code>c</code>, qui combine l’ensemble de ses arguments en un vecteur<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> :</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1">tailles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">156</span>, <span class="dv">164</span>, <span class="dv">197</span>, <span class="dv">181</span>, <span class="dv">173</span>)</a></code></pre></div>
<p>Ici, <code>c</code> est appelée en lui passant cinq arguments, les cinq tailles séparées par des virgules, et elle renvoie un vecteur numérique regroupant ces cinq valeurs.</p>
<p>Supposons maintenant que dans notre vecteur <code>tailles</code> nous avons une valeur manquante (une personne a refusé de répondre, ou notre mètre mesureur était en panne). On symbolise celle-ci dans R avec le code interne <code>NA</code> :</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1">tailles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">156</span>, <span class="dv">164</span>, <span class="dv">197</span>, <span class="ot">NA</span>, <span class="dv">173</span>)</a>
<a class="sourceLine" id="cb67-2" title="2">tailles</a></code></pre></div>
<pre><code>## [1] 156 164 197  NA 173</code></pre>
<div class="rmdnote">
<p>
<code>NA</code> est l’abbréviation de <em>Not available</em>, non disponible. Cette valeur particulière peut être utilisée pour indiquer une valeur manquante, qu’il s’agisse d’un nombre, d’une chaîne de caractères, etc.
</p>
</div>
<p>Si je calcule maintenant la taille moyenne à l’aide de la fonction <code>mean</code>, j’obtiens :</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">mean</span>(tailles)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>En effet, R considère par défaut qu’il ne peut pas calculer la moyenne si une des valeurs n’est pas disponible. Il considère alors que cette moyenne est elle-même “non disponible” et renvoie donc comme résultat <code>NA</code>.</p>
<p>On peut cependant indiquer à <code>mean</code> d’effectuer le calcul en ignorant les valeurs manquantes. Ceci se fait en ajoutant un argument supplémentaire, nommé <code>na.rm</code> (abbréviation de <em>NA remove</em>, “enlever les NA”), et de lui attribuer la valeur <code>TRUE</code> (code interne de R signifiant <em>vrai</em>) :</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">mean</span>(tailles, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## [1] 172.5</code></pre>
<p>Positionner le paramètre <code>na.rm</code> à <code>TRUE</code> indique à la fonction <code>mean</code> de ne pas tenir compte des valeurs manquantes dans le calcul.</p>
<p>Si on ne dit rien à la fonction <code>mean</code>, cet argument a une valeur par défaut, en l’occurrence <code>FALSE</code> (faux), qui fait qu’il ne supprime pas les valeurs manquantes. Les deux commandes suivantes sont donc rigoureusement équivalentes :</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="kw">mean</span>(tailles)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="kw">mean</span>(tailles, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>

<div class="rmdnote">
Lorsqu’on passe un argument à une fonction de cette manière, c’est-à-dire sous la forme <code>nom = valeur</code>, on parle d’<em>argument nommé</em>.
</div>

</div>
<div id="aide-sur-une-fonction" class="section level4">
<h4><span class="header-section-number">1.2.4.3</span> Aide sur une fonction</h4>
<p>Il est fréquent de ne pas savoir (ou d’avoir oublié) quels sont les arguments d’une fonction, ou comment ils se nomment. On peut à tout moment faire appel à l’aide intégrée à R en passant le nom de la fonction (entre guillemets) à la fonction <code>help</code> :</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="kw">help</span>(<span class="st">&quot;mean&quot;</span>)</a></code></pre></div>
<p>On peut aussi utiliser le raccourci <code>?mean</code>.</p>
<p>Ces deux commandes affichent une page (en anglais) décrivant la fonction, ses paramètres, son résultat, le tout accompagné de diverses notes, références et exemples. Ces pages d’aide contiennent à peu près tout ce que vous pourrez chercher à savoir, mais elles ne sont pas toujours d’une lecture aisée.</p>
<p>Dans RStudio, les pages d’aide en ligne s’ouvriront par défaut dans la zone en bas à droite,
sous l’onglet <em>Help</em>. Un clic sur l’icône en forme de maison vous affichera la page d’accueil de l’aide.</p>
</div>
</div>
<div id="regrouper-ses-commandes-dans-des-scripts" class="section level3">
<h3><span class="header-section-number">1.2.5</span> Regrouper ses commandes dans des scripts</h3>
<p>Jusqu’ici on a utilisé R de manière “interactive”, en saisissant des commandes directement dans la console. Ça n’est cependant pas la manière dont on va utiliser R au quotidien, pour une raison simple : lorsque R redémarre, tout ce qui a été effectué dans la console est perdu.</p>
<p>Plutôt que de saisir nos commandes dans la console, on va donc les regrouper dans des scripts (de simples fichiers texte), qui vont garder une trace de toutes les opérations effectuées, et ce sont ces scripts, sauvegardés régulièrement, qui seront le “coeur” de notre travail. C’est en rouvrant les scripts et en réexécutant les commandes qu’ils contiennent qu’on pourra “reproduire” les données, leur traitement, les analyses et leurs résultats.</p>
<p>Pour créer un script, il suffit de sélectionner le menu <em>File</em>, puis <em>New file</em> et <em>R script</em>. Une quatrième zone apparaît alors en haut à gauche de l’interface de RStudio. On peut enregistrer notre script à tout moment dans un fichier avec l’extension <code>.R</code>, en cliquant sur l’icône de disquette ou en choissant <em>File</em> puis <em>Save</em>.</p>
<p>Un script est un fichier texte brut, qui s’édite de la manière habituelle. À la différence de la console, quand on appuie sur <code>Entrée</code>, cela n’exécute pas la commande en cours mais insère un saut de ligne (comme on pouvait s’y attendre).</p>
<p>Pour exécuter une commande saisie dans un script, il suffit de positionner le curseur sur la ligne de la commande en question, et de cliquer sur le bouton <em>Run</em> dans la barre d’outils juste au-dessus de la zone d’édition du script. On peut aussi utiliser le raccourci clavier <code>Ctrl + Entrée</code> (<code>Cmd + Entrée</code> sous Mac). On peut enfin sélectionner plusieurs lignes avec la souris ou le clavier et cliquer sur <em>Run</em> (ou utiliser le raccourci clavier), et l’ensemble des lignes est exécuté d’un coup.</p>
<p>Au final, un script pourra ressembler à quelque chose comme ça :</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1">tailles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">156</span>, <span class="dv">164</span>, <span class="dv">197</span>, <span class="dv">147</span>, <span class="dv">173</span>)</a>
<a class="sourceLine" id="cb78-2" title="2">poids &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">59</span>, <span class="dv">110</span>, <span class="dv">44</span>, <span class="dv">88</span>)</a>
<a class="sourceLine" id="cb78-3" title="3"></a>
<a class="sourceLine" id="cb78-4" title="4"><span class="kw">mean</span>(tailles)</a>
<a class="sourceLine" id="cb78-5" title="5"><span class="kw">mean</span>(poids)</a>
<a class="sourceLine" id="cb78-6" title="6"></a>
<a class="sourceLine" id="cb78-7" title="7">imc &lt;-<span class="st"> </span>poids <span class="op">/</span><span class="st"> </span>(tailles <span class="op">/</span><span class="st"> </span><span class="dv">100</span>) <span class="op">^</span><span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb78-8" title="8"><span class="kw">min</span>(imc)</a>
<a class="sourceLine" id="cb78-9" title="9"><span class="kw">max</span>(imc)</a></code></pre></div>
<div id="commentaires" class="section level4">
<h4><span class="header-section-number">1.2.5.1</span> Commentaires</h4>
<p>Les commentaires sont un élément très important d’un script. Il s’agit de texte libre, ignoré par R, et qui permet de décrire les étapes du script, sa logique, les raisons pour lesquelles on a procédé de telle ou telle manière… Il est primordial de documenter ses scripts à l’aide de commentaires, car il est très facile de ne plus se retrouver dans un programme qu’on a produit soi-même, même après une courte interruption.</p>
<p>Pour ajouter un commentaire, il suffit de le faire précéder d’un ou plusieurs symboles <code>#</code>. En effet, dès que R rencontre ce caractère, il ignore tout ce qui se trouve derrière, jussqu’à la fin de la ligne.</p>
<p>On peut donc documenter le script précédent :</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="co"># Saisie des tailles et poids des enquêtés</span></a>
<a class="sourceLine" id="cb79-2" title="2">tailles &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">156</span>, <span class="dv">164</span>, <span class="dv">197</span>, <span class="dv">147</span>, <span class="dv">173</span>)</a>
<a class="sourceLine" id="cb79-3" title="3">poids &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">45</span>, <span class="dv">59</span>, <span class="dv">110</span>, <span class="dv">44</span>, <span class="dv">88</span>)</a>
<a class="sourceLine" id="cb79-4" title="4"></a>
<a class="sourceLine" id="cb79-5" title="5"><span class="co"># Calcul des tailles et poids moyens</span></a>
<a class="sourceLine" id="cb79-6" title="6"><span class="kw">mean</span>(tailles)</a>
<a class="sourceLine" id="cb79-7" title="7"><span class="kw">mean</span>(poids)</a>
<a class="sourceLine" id="cb79-8" title="8"></a>
<a class="sourceLine" id="cb79-9" title="9"><span class="co"># Calcul de l&#39;IMC (poids en kilo divisé par les tailles en mètre au carré)</span></a>
<a class="sourceLine" id="cb79-10" title="10">imc &lt;-<span class="st"> </span>poids <span class="op">/</span><span class="st"> </span>(tailles <span class="op">/</span><span class="st"> </span><span class="dv">100</span>) <span class="op">^</span><span class="st"> </span><span class="dv">2</span></a>
<a class="sourceLine" id="cb79-11" title="11"><span class="co"># Valeurs extrêmes de l&#39;IMC</span></a>
<a class="sourceLine" id="cb79-12" title="12"><span class="kw">min</span>(imc)</a>
<a class="sourceLine" id="cb79-13" title="13"><span class="kw">max</span>(imc)</a></code></pre></div>
</div>
</div>
<div id="packages" class="section level3">
<h3><span class="header-section-number">1.2.6</span> Installer et charger des extensions (<em>packages</em>)</h3>
<p>R étant un logiciel libre, il bénéficie d’un développement communautaire riche et dynamique. L’installation de base de R permet de faire énormément de choses, mais le langage dispose en plus d’un système d’extensions permettant d’ajouter facilement de nouvelles fonctionnalités. La plupart des extensions sont développées et maintenues par la communauté des utilisateurs de R, et diffusées via un réseau de serveurs nommé CRAN (<em>Comprehensive R Archive Network</em>).</p>
<p>Pour installer une extension, si on dispose d’une connexion Internet, on peut utiliser le bouton <em>Install</em> de l’onglet <em>Packages</em> de RStudio.</p>
<div class="figure">
<img src="images/screenshots/rstudio_package_install.png" alt="Installer une extension" />
<p class="caption">Installer une extension</p>
</div>
<p>Il suffit alors d’indiquer le nom de l’extension dans le champ <em>Package</em> et de cliquer sur <em>Install</em>.</p>
<div class="figure">
<img src="images/screenshots/rstudio_package_install2.png" alt="Installation d’une extension" />
<p class="caption">Installation d’une extension</p>
</div>
<p>On peut aussi installer des extensions en utilisant la fonction <code>install.packages()</code> directement dans la console. Par exemple, pour installer le <em>package</em> <code>questionr</code> on peut exécuter la commande :</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">install.packages</span>(<span class="st">&quot;questionr&quot;</span>)</a></code></pre></div>
<p>Installer une extension via l’une des deux méthodes précédentes va télécharger l’ensemble des fichiers nécessaires depuis l’une des machines du CRAN, puis installer tout ça sur le disque dur de votre ordinateur. Vous n’avez besoin de le faire qu’une fois, comme vous le faites pour installer un programme sur votre Mac ou PC.</p>
<p>Une fois l’extension installée, il faut la “charger” avant de pouvoir utiliser les fonctions qu’elle propose. Ceci se fait avec la fonction <code>library</code>. Par exemple, pour pouvoir utiliser les fonctions de <code>questionr</code>, vous devrez exécuter la commande suivante :</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">library</span>(questionr)</a></code></pre></div>
<p>Ainsi, bien souvent, on regroupe en début de script toute une série d’appels à <code>library</code> qui permettent de charger tous les packages utilisés dans le script. Quelque chose comme :</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb82-2" title="2"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb82-3" title="3"><span class="kw">library</span>(questionr)</a></code></pre></div>
<p>Si vous essayez d’exécuter une fonction d’une extension et que vous obtenez le message d’erreur <code>impossible de trouver la fonction</code>, c’est certainement parce que vous n’avez pas exécuté la commande <code>library</code> correspondante.</p>
</div>
<div id="ex-introR" class="section level3">
<h3><span class="header-section-number">1.2.7</span> Exercices</h3>
<p><strong>Exercice 1</strong></p>
<p>Construire le vecteur <code>x</code> suivant :</p>
<pre><code>## [1] 120 134 256  12</code></pre>

<div class="solution">
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">120</span>, <span class="dv">134</span>, <span class="dv">256</span>, <span class="dv">12</span>)</a></code></pre></div>
</div>

<p>Utiliser ce vecteur <code>x</code> pour générer les deux vecteurs suivants :</p>
<pre><code>## [1] 220 234 356 112</code></pre>
<pre><code>## [1] 240 268 512  24</code></pre>

<div class="solution">
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1">x <span class="op">+</span><span class="st"> </span><span class="dv">100</span></a>
<a class="sourceLine" id="cb87-2" title="2">x <span class="op">*</span><span class="st"> </span><span class="dv">2</span></a></code></pre></div>
</div>

<p><strong>Exercice 2</strong></p>
<p>On a demandé à 4 ménages le revenu des deux conjoints, et le nombre de personnes du ménage :</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">conjoint1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1200</span>, <span class="dv">1180</span>, <span class="dv">1750</span>, <span class="dv">2100</span>)</a>
<a class="sourceLine" id="cb88-2" title="2">conjoint2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1450</span>, <span class="dv">1870</span>, <span class="dv">1690</span>, <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb88-3" title="3">nb_personnes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>)</a></code></pre></div>
<p>Calculer le revenu total de chaque ménage, puis diviser par le nombre de personnes pour obtenir le revenu par personne de chaque ménage.</p>

<div class="solution">
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">revenu_total &lt;-<span class="st"> </span>conjoint1 <span class="op">+</span><span class="st"> </span>conjoint2</a>
<a class="sourceLine" id="cb89-2" title="2">revenu_total <span class="op">/</span><span class="st"> </span>nb_personnes</a></code></pre></div>
</div>

<p><strong>Exercice 3</strong></p>
<p>Dans l’exercice précédent, calculer le revenu minimum et maximum parmi ceux du premier conjoint.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1">conjoint1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1200</span>, <span class="dv">1180</span>, <span class="dv">1750</span>, <span class="dv">2100</span>)</a></code></pre></div>

<div class="solution">
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1"><span class="kw">range</span>(conjoint1)</a></code></pre></div>
</div>

<p>Recommencer avec les revenus suivants, parmi lesquels l’un des enquetés n’a pas voulu répondre :</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1">conjoint1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1200</span>, <span class="dv">1180</span>, <span class="dv">1750</span>, <span class="ot">NA</span>)</a></code></pre></div>

<div class="solution">
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1"><span class="kw">range</span>(conjoint1, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
</div>

<p><strong>Exercice 4</strong></p>
<p>Les deux vecteurs suivants représentent les précipitations (en mm) et la température (en °C) moyennes sur la ville de Lyon, pour chaque mois de l’année, entre 1981 et 2010 :</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1">temperature &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">3.4</span>, <span class="fl">4.8</span>, <span class="fl">8.4</span>, <span class="fl">11.4</span>, <span class="fl">15.8</span>, <span class="fl">19.4</span>, <span class="fl">22.2</span>, <span class="fl">21.6</span>, <span class="fl">17.6</span>, <span class="fl">13.4</span>, <span class="fl">7.6</span>, <span class="fl">4.4</span>)</a>
<a class="sourceLine" id="cb94-2" title="2">precipitations &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">47.2</span>, <span class="fl">44.1</span>, <span class="fl">50.4</span>, <span class="fl">74.9</span>, <span class="fl">90.8</span>, <span class="fl">75.6</span>, <span class="fl">63.7</span>, <span class="dv">62</span>, <span class="fl">87.5</span>, <span class="fl">98.6</span>, <span class="fl">81.9</span>, <span class="fl">55.2</span>)</a></code></pre></div>
<p>Calculer la température moyenne sur l’année.</p>
<p>Calculer la quantité totale de précipitations sur l’année.</p>

<div class="solution">
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1"><span class="kw">mean</span>(temperature)</a>
<a class="sourceLine" id="cb95-2" title="2"><span class="kw">sum</span>(precipitations)</a></code></pre></div>
</div>

<p>À quoi correspond et comment peut-on interpréter le résultat de la fonction suivante ? Vous pouvez vous aider de la page d’aide de la fonction si nécessaire.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="kw">cumsum</span>(precipitations)</a></code></pre></div>
<pre><code>##  [1]  47.2  91.3 141.7 216.6 307.4 383.0 446.7 508.7 596.2 694.8 776.7 831.9</code></pre>
<p>Même question pour :</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1"><span class="kw">diff</span>(temperature)</a></code></pre></div>
<pre><code>##  [1]  1.4  3.6  3.0  4.4  3.6  2.8 -0.6 -4.0 -4.2 -5.8 -3.2</code></pre>

<div class="solution">
<p><code>cumsum(precipitations)</code> correspond à la somme cumulée des précipitations sur l’année. Par exemple, la 6e valeur du vecteur résultat correspond au total de précipitations de janvier à juin.</p>
<p><code>diff(temperature)</code> correspond à la différence de température d’un mois sur l’autre. Par exemple, la 2e valeur de ce vecteur correspond à l’écart de température entre le mois de février et le mois de janvier.</p>
</div>

<p><strong>Exercice 5</strong></p>
<p>On a relevé les notes en maths, anglais et sport d’une classe de 6 élèves et on a stocké ces données dans trois vecteurs :</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb100-1" title="1">maths &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">8</span>, <span class="dv">18</span>, <span class="dv">6</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb100-2" title="2">anglais &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">14</span>, <span class="dv">9</span>, <span class="dv">13</span>, <span class="dv">15</span>, <span class="dv">17</span>, <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb100-3" title="3">sport &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">18</span>, <span class="dv">11</span>, <span class="dv">14</span>, <span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">12</span>)</a></code></pre></div>
<p>Calculer la moyenne des élèves de la classe en anglais.</p>
<p>Calculer la moyenne générale de chaque élève.</p>

<div class="solution">
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1"><span class="kw">mean</span>(anglais)</a>
<a class="sourceLine" id="cb101-2" title="2">(maths <span class="op">+</span><span class="st"> </span>anglais <span class="op">+</span><span class="st"> </span>sport) <span class="op">/</span><span class="st"> </span><span class="dv">3</span></a></code></pre></div>
</div>

<p>Essayez de comprendre le résultat des deux fonctions suivantes (vous pouvez vous aider de la page d’aide de ces fonctions) :</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">pmin</span>(maths, anglais, sport)</a></code></pre></div>
<pre><code>## [1] 12  9  8 10  6 10</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1"><span class="kw">pmax</span>(maths, anglais, sport)</a></code></pre></div>
<pre><code>## [1] 18 16 14 18 17 12</code></pre>

<div class="solution">
<p><code>pmin</code> et <code>pmax</code> renvoient les minimum et maximum “parallèles” des trois vecteurs passés en argument. Ainsi, <code>pmin</code> renvoie pour chaque élève la note minimale dans les trois matières, et <code>pmax</code> la note maximale.</p>
</div>


</div>
</div>
<div id="premier-travail-avec-des-données" class="section level2">
<h2><span class="header-section-number">1.3</span> Premier travail avec des données</h2>
<div id="jeu-de-données-dexemple" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Jeu de données d’exemple</h3>
<p>Dans cette partie nous allons (enfin) travailler sur des “vraies” données, et utiliser un jeu de données présent dans l’extension <code>questionr</code>. Nous devons donc avant toute chose installer cette extension.</p>
<p>Pour installer ce package, deux possibilités :</p>
<ul>
<li>Dans l’onglet <em>Packages</em> de la zone de l’écran en bas à droite, cliquez sur le bouton <em>Install</em>. Dans le dialogue qui s’ouvre, entrez “questionr” dans le champ <em>Packages</em> puis cliquez sur <em>Install</em>.</li>
<li>Saisissez directement la commande suivante dans la console : <code>install.packages("questionr")</code></li>
</ul>
<p>Dans les deux cas, tout un tas de messages devraient s’afficher dans la console. Attendez que l’invite de commandes <code>&gt;</code> apparaisse à nouveau.</p>
<p>Pour plus d’informations sur les extensions et leur installation, voir la section <a href="introduction-à-r.html#packages">1.2.6</a>.</p>
<p>Le jeu de données que nous allons utiliser est un extrait de l’enquête <em>Histoire de vie</em> réalisée par l’INSEE en 2003. Il contient 2000 individus et 20 variables. Pour une description plus complète et une liste des variables, voir la section <a href="#hdv2003"><strong>??</strong></a>.</p>
<p>Pour pouvoir utiliser ces données, il faut d’abord charger l’extension <code>questionr</code> (après l’avoir installée, bien entendu) :</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="kw">library</span>(questionr)</a></code></pre></div>
<p>L’utilisation de <code>library</code> permet de rendre “disponibles”, dans notre session R, les fonctions et jeux de données inclus dans l’extension.</p>
<p>Nous devons ensuite indiquer à R que nous souhaitons accéder au jeu de données à l’aide de la commande <code>data</code> :</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1"><span class="kw">data</span>(hdv2003)</a></code></pre></div>
<p>Cette commande ne renvoie aucun résultat particulier (sauf en cas d’erreur), mais vous devriez voir apparaître dans l’onglet <em>Environment</em> de RStudio un nouvel objet nommé <code>hdv2003</code> :</p>
<div class="figure">
<img src="images/screenshots/rstudio_environment.png" alt="Onglet Environment" />
<p class="caption">Onglet <em>Environment</em></p>
</div>
<p>Cet objet est d’un type nouveau : il s’agit d’un tableau de données.</p>
</div>
<div id="tableau-de-données-data-frame" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Tableau de données (<em>data frame</em>)</h3>
<p>Un <em>data frame</em> (ou tableau de données, ou table) est un type d’objet R qui contient des données au format tabulaire, avec les observations en ligne et les variables en colonnes, comme dans une feuille de tableur de type LibreOffice ou Excel.</p>
<p>Si on se contente d’exécuter le nom de notre tableau de données :</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1">hdv2003</a></code></pre></div>
<p>R va, comme à son habitude, nous l’afficher dans la console, ce qui est tout sauf utile.</p>
<p>Une autre manière d’afficher le contenu du tableau est de cliquer sur l’icône en forme de tableau à droite du nom de l’objet dans l’onglet <em>Environment</em> :</p>
<div class="figure">
<img src="images/screenshots/rstudio_view_icon.png" alt="View icon" />
<p class="caption">View icon</p>
</div>
<p>Ou d’utiliser la fonction <code>View</code> :</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="kw">View</span>(hdv2003)</a></code></pre></div>
<p>Dans les deux cas votre tableau devrait s’afficher dans RStudio avec une interface de type tableur :</p>
<div class="figure">
<img src="images/screenshots/rstudio_view.png" alt="Interface “View”" />
<p class="caption">Interface “View”</p>
</div>
<p>Il est important de comprendre que l’objet <code>hdv2003</code> contient <em>l’intégralité</em> des données du tableau.
On voit donc qu’un objet peut contenir des données de types très différents (simple nombre, texte, vecteur, tableau de données entier), et être potentiellement de très grande taille<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a>.</p>
<div class="rmdnote">
<p>
Sous R, on peut importer ou créer autant de tableaux de données qu’on le souhaite, dans les limites des capacités de sa machine.
</p>
</div>
<p>Un <em>data frame</em> peut être manipulé comme les autres objets vus précédemment. On peut par exemple faire :</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1">d &lt;-<span class="st"> </span>hdv2003</a></code></pre></div>
<p>ce qui va entraîner la copie de l’ensemble de nos données dans un nouvel objet nommé <code>d</code>. Ceci peut paraître parfaitement inutile mais a en fait l’avantage de fournir un objet avec un nom beaucoup plus court, ce qui diminuera la quantité de texte à saisir par la suite.</p>
<p><strong>Pour résumer</strong>, comme nous avons désormais décidé de saisir nos commandes dans un script et non plus directement dans la console, les premières lignes de notre fichier de travail sur les données de l’enquête <em>Histoire de vie</em> pourraient donc ressembler à ceci :</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="co">## Chargement des extensions nécessaires</span></a>
<a class="sourceLine" id="cb111-2" title="2"><span class="kw">library</span>(questionr)</a>
<a class="sourceLine" id="cb111-3" title="3"></a>
<a class="sourceLine" id="cb111-4" title="4"><span class="co">## Jeu de données hdv2003</span></a>
<a class="sourceLine" id="cb111-5" title="5"><span class="kw">data</span>(hdv2003)</a>
<a class="sourceLine" id="cb111-6" title="6">d &lt;-<span class="st"> </span>hdv2003</a></code></pre></div>
<div id="structure-du-tableau" class="section level4">
<h4><span class="header-section-number">1.3.2.1</span> Structure du tableau</h4>
<p>Un tableau étant un objet comme un autre, on peut lui appliquer des fonctions. Par exemple, <code>nrow</code> et <code>ncol</code> retournent le nombre de lignes et de colonnes du tableau :</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1"><span class="kw">nrow</span>(d)</a></code></pre></div>
<pre><code>## [1] 2000</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1"><span class="kw">ncol</span>(d)</a></code></pre></div>
<pre><code>## [1] 20</code></pre>
<p>La fonction <code>dim</code> renvoie ses dimensions, donc les deux nombres précédents :</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="kw">dim</span>(d)</a></code></pre></div>
<pre><code>## [1] 2000   20</code></pre>
<p>La fonction <code>names</code> retourne les noms des colonnes du tableau, c’est-à-dire la liste de nos <em>variables</em> :</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">names</span>(d)</a></code></pre></div>
<pre><code>##  [1] &quot;id&quot;            &quot;age&quot;           &quot;sexe&quot;          &quot;nivetud&quot;      
##  [5] &quot;poids&quot;         &quot;occup&quot;         &quot;qualif&quot;        &quot;freres.soeurs&quot;
##  [9] &quot;clso&quot;          &quot;relig&quot;         &quot;trav.imp&quot;      &quot;trav.satisf&quot;  
## [13] &quot;hard.rock&quot;     &quot;lecture.bd&quot;    &quot;peche.chasse&quot;  &quot;cuisine&quot;      
## [17] &quot;bricol&quot;        &quot;cinema&quot;        &quot;sport&quot;         &quot;heures.tv&quot;</code></pre>
<p>Enfin, la fonction <code>str</code> renvoie un descriptif plus détaillé de la structure du tableau. Elle liste les différentes variables, indique leur type <a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> et affiche les premières valeurs :</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1"><span class="kw">str</span>(d)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	2000 obs. of  20 variables:
##  $ id           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ age          : int  28 23 59 34 71 35 60 47 20 28 ...
##  $ sexe         : Factor w/ 2 levels &quot;Homme&quot;,&quot;Femme&quot;: 2 2 1 1 2 2 2 1 2 1 ...
##  $ nivetud      : Factor w/ 8 levels &quot;N&#39;a jamais fait d&#39;etudes&quot;,..: 8 NA 3 8 3 6 3 6 NA 7 ...
##  $ poids        : num  2634 9738 3994 5732 4329 ...
##  $ occup        : Factor w/ 7 levels &quot;Exerce une profession&quot;,..: 1 3 1 1 4 1 6 1 3 1 ...
##  $ qualif       : Factor w/ 7 levels &quot;Ouvrier specialise&quot;,..: 6 NA 3 3 6 6 2 2 NA 7 ...
##  $ freres.soeurs: int  8 2 2 1 0 5 1 5 4 2 ...
##  $ clso         : Factor w/ 3 levels &quot;Oui&quot;,&quot;Non&quot;,&quot;Ne sait pas&quot;: 1 1 2 2 1 2 1 2 1 2 ...
##  $ relig        : Factor w/ 6 levels &quot;Pratiquant regulier&quot;,..: 4 4 4 3 1 4 3 4 3 2 ...
##  $ trav.imp     : Factor w/ 4 levels &quot;Le plus important&quot;,..: 4 NA 2 3 NA 1 NA 4 NA 3 ...
##  $ trav.satisf  : Factor w/ 3 levels &quot;Satisfaction&quot;,..: 2 NA 3 1 NA 3 NA 2 NA 1 ...
##  $ hard.rock    : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ lecture.bd   : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ peche.chasse : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 1 1 1 1 1 2 2 1 1 ...
##  $ cuisine      : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 2 1 1 2 1 1 2 2 1 1 ...
##  $ bricol       : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 1 1 2 1 1 1 2 1 1 ...
##  $ cinema       : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 2 1 2 1 2 1 1 2 2 ...
##  $ sport        : Factor w/ 2 levels &quot;Non&quot;,&quot;Oui&quot;: 1 2 2 2 1 2 1 1 1 2 ...
##  $ heures.tv    : num  0 1 0 2 3 2 2.9 1 2 2 ...</code></pre>
<p>Sous RStudio, on peut afficher à tout moment la structure d’un objet en cliquant sur l’icône de triangle sur fond bleu à gauche du nom de l’objet dans l’onglet <em>Environment</em> :</p>
<div class="figure">
<img src="images/screenshots/rstudio_environment_str.png" alt="Structure d’un objet" />
<p class="caption">Structure d’un objet</p>
</div>
</div>
<div id="accéder-aux-variables-dun-tableau" class="section level4">
<h4><span class="header-section-number">1.3.2.2</span> Accéder aux variables d’un tableau</h4>
<p>Une opération très importante est l’accès aux variables du tableau (à ses colonnes) pour pouvoir les manipuler, effectuer des calculs, etc. On utilise pour cela l’opérateur <code>$</code>, qui permet d’accéder aux colonnes du tableau. Ainsi, si l’on tape :</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1">d<span class="op">$</span>sexe</a></code></pre></div>
<pre><code>##   [1] Femme Femme Homme Homme Femme Femme Femme Homme Femme Homme Femme Homme
##  [13] Femme Femme Femme Femme Homme Femme Homme Femme Femme Homme Femme Femme
##  [25] Femme Homme Femme Homme Homme Homme Homme Homme Homme Homme Femme Femme
##  [37] Homme Femme Femme Homme Femme Homme Homme Femme Femme Homme Femme Femme
##  [49] Femme Femme Homme Femme Homme Femme Homme Femme Femme Femme Homme Femme
##  [61] Femme Homme Homme Homme Homme Femme Homme Homme Femme Femme Homme Homme
##  [73] Femme Femme Femme Femme Homme Femme Femme Femme Femme Femme Femme Homme
##  [85] Homme Femme Homme Homme Homme Homme Homme Femme Homme Femme Femme Femme
##  [97] Homme Homme Femme Femme Femme Homme Femme Homme Homme Femme Femme Femme
## [109] Femme Homme Homme Homme Homme Homme Femme Homme Homme Femme Homme Homme
## [121] Femme Femme Femme Homme Femme Femme Homme Femme Femme Homme Femme Homme
## [133] Femme Femme Femme Homme Homme Homme Homme Homme Homme Homme Homme Femme
## [145] Homme Homme Homme Femme Femme Femme Homme Femme Femme Femme Femme Homme
## [157] Femme Homme Homme Homme Femme Homme Femme Homme Femme Homme Homme Femme
## [169] Femme Femme Homme Femme Homme Femme Femme Femme Homme Homme Homme Femme
## [181] Homme Femme Femme Homme Homme Femme Femme Femme Femme Femme Homme Homme
## [193] Femme Homme Homme Femme Homme Femme Homme Femme
##  [ reached getOption(&quot;max.print&quot;) -- omitted 1800 entries ]
## Levels: Homme Femme</code></pre>
<p>R va nous afficher l’ensemble des valeurs de notre variable <code>sexe</code> dans la console, ce qui est à nouveau fort peu utile. Mais cela nous permet de constater que <code>d$sexe</code> est un vecteur de chaînes de caractères tels qu’on en a déjà rencontré précédemment.</p>
<p>La fonction <code>table$colonne</code> renvoie donc la colonne nommée <code>colonne</code> du tableau <code>table</code>, c’est-à-dire un vecteur, en général de nombres ou de chaînes de caractères.</p>
<p>Si on souhaite afficher seulement les premières ou dernières valeurs d’une variable, on peut utiliser les fonctions <code>head</code> et <code>tail</code> :</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="kw">head</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 28 23 59 34 71 35</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1"><span class="kw">tail</span>(d<span class="op">$</span>age, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##  [1] 52 42 50 41 46 45 46 24 24 66</code></pre>
<p>Le deuxième argument numérique permet d’indiquer le nombre de valeurs à afficher.</p>
</div>
<div id="créer-une-nouvelle-variable" class="section level4">
<h4><span class="header-section-number">1.3.2.3</span> Créer une nouvelle variable</h4>
<p>On peut aussi utiliser l’opérateur <code>$</code> pour créer une nouvelle variable dans notre tableau : pour cela, il suffit de lui assigner une valeur.</p>
<p>Par exemple, la variable <code>heures.tv</code> contient le nombre d’heures passées quotidiennement devant la télé :</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">head</span>(d<span class="op">$</span>heures.tv, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##  [1] 0.0 1.0 0.0 2.0 3.0 2.0 2.9 1.0 2.0 2.0</code></pre>
<p>On peut vouloir créer une nouvelle variable dans notre tableau qui contienne la même durée mais en minutes. On va donc créer une nouvelle variables <code>minutes.tv</code> de la manière suivante :</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">d<span class="op">$</span>minutes.tv &lt;-<span class="st"> </span>d<span class="op">$</span>heures.tv <span class="op">*</span><span class="st"> </span><span class="dv">60</span></a></code></pre></div>
<p>On peut alors constater, soit visuellement soit dans la console, qu’une nouvelle variable (une nouvelle colonne) a bien été ajoutée au tableau :</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1"><span class="kw">head</span>(d<span class="op">$</span>minutes.tv)</a></code></pre></div>
<pre><code>## [1]   0  60   0 120 180 120</code></pre>
</div>
</div>
<div id="analyse-univariée" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Analyse univariée</h3>
<p>On a donc désormais accès à un tableau de données <code>d</code>, dont les lignes sont des observations (des individus enquêtés), et les colonnes des variables (des caractéristiques de chacun de ces individus), et on sait accéder à ces variables grâce à l’opérateur <code>$</code>.</p>
<p>Si on souhaite analyser ces variables, les méthodes et fonctions utilisées seront différentes selon qu’il s’agit d’une variable <em>quantitative</em> (variable numérique pouvant prendre un grand nombre de valeurs : l’âge, le revenu, un pourcentage…) ou d’une variable <em>qualitative</em> (variable pouvant prendre un nombre limité de valeurs appelées modalités : le sexe, la profession, le dernier diplôme obtenu, etc.).</p>
<div id="analyser-une-variable-quantitative" class="section level4">
<h4><span class="header-section-number">1.3.3.1</span> Analyser une variable quantitative</h4>
<p>Une variable quantitative est une variable de type numérique (un nombre) qui peut prendre un grand nombre de valeurs. On en a plusieurs dans notre jeu de données, notamment l’âge (variable <code>age</code>) ou le nombre d’heures passées devant la télé (<code>heures.tv</code>).</p>
<div id="indicateurs-de-centralité" class="section level5">
<h5><span class="header-section-number">1.3.3.1.1</span> Indicateurs de centralité</h5>
<p>Caractériser une variable quantitative, c’est essayer de décrire la manière dont ses valeurs se répartissent, ou se distribuent.</p>
<p>Pour cela on peut commencer par regarder les valeurs extrêmes, avec les fonctions <code>min</code>, <code>max</code> ou <code>range</code> :</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1"><span class="kw">min</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 18</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">max</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 97</code></pre>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">range</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 18 97</code></pre>
<p>On peut aussi calculer des indicateurs de <em>centralité</em> : ceux-ci indiquent autour de quel nombre se répartissent les valeurs de la variable. Il y en a plusieurs, le plus connu étant la moyenne, qu’on peut calculer avec la fonction <code>mean</code> :</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1"><span class="kw">mean</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 48.157</code></pre>
<p>Il existe aussi la médiane, qui est la valeur qui sépare notre population en deux : on a la moitié de nos observations en-dessous, et la moitié au-dessus. Elle se calcule avec la fonction <code>median</code> :</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1"><span class="kw">median</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 48</code></pre>
<p>Une différence entre les deux indicateurs est que la médiane est beaucoup moins sensible aux valeurs “extrêmes” : on dit qu’elle est plus <em>robuste</em>. Ainsi, en 2013, le salaire net <em>moyen</em> des salariés à temps plein en France était de 2202 euros, tandis que le salaire net <em>médian</em> n’était que de 1772 euros. La différence étant due à des très hauts salaires qui “tirent” la moyenne vers le haut.</p>
</div>
<div id="indicateurs-de-dispersion" class="section level5">
<h5><span class="header-section-number">1.3.3.1.2</span> Indicateurs de dispersion</h5>
<p>Les indicateurs de dispersion permettent de mesurer si les valeurs sont plutôt regroupées ou au contraire plutôt dispersées.</p>
<p>L’indicateur le plus simple est l’étendue de la distribution, qui décrit l’écart maximal observé entre les observations :</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">max</span>(d<span class="op">$</span>age) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 79</code></pre>
<p>Les indicateurs de dispersion les plus utilisés sont la variance ou, de manière équivalente, l’écart-type (qui est égal à la racine carrée de la variance). On obtient la première avec la fonction <code>var</code>, et le second avec <code>sd</code> (abbréviation de <em>standard deviation</em>) :</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">var</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 287.0249</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1"><span class="kw">sd</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 16.94181</code></pre>
<p>Plus la variance ou l’écart-type sont élevés, plus les valeurs sont dispersées autour de la moyenne. À l’inverse, plus ils sont faibles et plus les valeurs sont regroupées.</p>
<p>Une autre manière de mesurer la dispersion est de calculer les quartiles :</p>
<ul>
<li>le premier quartile est la valeur pour laquelle on a 25% des observations en dessous et 75% au dessus</li>
<li>le deuxième quartile est la valeur pour laquelle on a 50% des observations en dessous et 50% au dessus (c’est donc la médiane)</li>
<li>le troisième quartile est la valeur pour laquelle on a 75% des observations en dessous et 25% au dessus</li>
</ul>
<p>On peut les calculer avec la fonction <code>quantile</code> :</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1"><span class="co">### Premier quartile</span></a>
<a class="sourceLine" id="cb149-2" title="2"><span class="kw">quantile</span>(d<span class="op">$</span>age, <span class="dt">prob =</span> <span class="fl">0.25</span>)</a></code></pre></div>
<pre><code>## 25% 
##  35</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" title="1"><span class="co">## Troisième quartile</span></a>
<a class="sourceLine" id="cb151-2" title="2"><span class="kw">quantile</span>(d<span class="op">$</span>age, <span class="dt">prob =</span> <span class="fl">0.75</span>)</a></code></pre></div>
<pre><code>## 75% 
##  60</code></pre>
<p><code>quantile</code> prend deux arguments principaux : le vecteur dont on veut calculer le quantile, et un argument <code>prob</code> qui indique quel quantile on souhaite obtenir. <code>prob</code> prend une valeur entre 0 et 1 : 0.5 est la médiane, 0.25 le premier quartile, 0.1 le premier décile, etc.</p>
<p>Notons enfin que la fonction <code>summary</code> permet d’obtenir d’un coup plusieurs indicateurs classiques :</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" title="1"><span class="kw">summary</span>(d<span class="op">$</span>age)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.00   35.00   48.00   48.16   60.00   97.00</code></pre>
</div>
<div id="représentation-graphique" class="section level5">
<h5><span class="header-section-number">1.3.3.1.3</span> Représentation graphique</h5>
<p>L’outil le plus utile pour étudier la distribution des valeurs d’une variable quantitative reste la représentation graphique.</p>
<p>La représentation la plus courante est sans doute l’histogramme. On peut l’obtenir avec la fonction <code>hist</code> :</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1"><span class="kw">hist</span>(d<span class="op">$</span>age)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-94-1.svg" width="672" /></p>
<p>Cette fonction n’a pas pour effet direct d’effectuer un calcul ou de nous renvoyer un résultat : elle génère un graphique qui va s’afficher dans l’onglet <em>Plots</em> de RStudio.</p>
<p>On peut personnaliser l’apparence de l’histogramme en ajoutant des arguments supplémentaires à la fonction <code>hist</code>. L’argument le plus important est <code>breaks</code>, qui permet d’indiquer le nombre de classes que l’on souhaite.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="kw">hist</span>(d<span class="op">$</span>age, <span class="dt">breaks =</span> <span class="dv">10</span>)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-95-1.svg" width="672" /></p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" title="1"><span class="kw">hist</span>(d<span class="op">$</span>age, <span class="dt">breaks =</span> <span class="dv">70</span>)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-96-1.svg" width="672" /></p>
<p>Le choix d’un “bon” nombre de classes pour un histogramme n’est pas un problème simple : si on a trop peu de classes, on risque d’effacer quasiment toutes les variations, et si on en a trop on risque d’avoir trop de détails et de masquer les grandes tendances.</p>
<p>Les arguments de <code>hist</code> permettent également de modifier la présentation du graphique. On peut ainsi changer la couleur des barres avec <code>col</code><a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a>, le titre avec <code>main</code>, les étiquettes des axes avec <code>xlab</code> et <code>ylab</code>, etc. :</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="kw">hist</span>(d<span class="op">$</span>age, <span class="dt">col =</span> <span class="st">&quot;skyblue&quot;</span>,</a>
<a class="sourceLine" id="cb158-2" title="2">     <span class="dt">main =</span> <span class="st">&quot;Répartition des âges des enquêtés&quot;</span>,</a>
<a class="sourceLine" id="cb158-3" title="3">     <span class="dt">xlab =</span> <span class="st">&quot;Âge&quot;</span>,</a>
<a class="sourceLine" id="cb158-4" title="4">     <span class="dt">ylab =</span> <span class="st">&quot;Effectif&quot;</span>)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-97-1.svg" width="672" /></p>
<p>La fonction <code>hist</code> fait partie des fonctions graphique de base de R. On verra plus en détail d’autres fonctions graphiques dans la partie <a href="#ggplot2"><strong>??</strong></a> de ce document, consacrée à l’extension <code>ggplot2</code>, qui fait partie du <em>tidyverse</em> et qui permet la production et la personnalisation de graphiques complexes.</p>
</div>
</div>
<div id="analyser-une-variable-qualitative" class="section level4">
<h4><span class="header-section-number">1.3.3.2</span> Analyser une variable qualitative</h4>
<p>Une variable qualitative est une variable qui ne peut prendre qu’un nombre limité de valeurs, appelées modalités. Dans notre jeu de données on trouvera par exemple le sexe (<code>sexe</code>), le niveau d’études (<code>nivetud</code>), la catégorie socio-professionnelle (<code>qualif</code>)…</p>
<p>À noter qu’une variable qualitative peut tout-à-fait être numérique, et que certaines variables peuvent être traitées soit comme quantitatives, soit comme qualitatives : c’est le cas par exemple du nombre d’enfants ou du nombre de frères et soeurs.</p>
<div id="tri-à-plat" class="section level5">
<h5><span class="header-section-number">1.3.3.2.1</span> Tri à plat</h5>
<p>L’outil le plus utilisé pour représenter la répartition des valeurs d’une variable qualitative est le <em>tri à plat</em> : il s’agit simplement de compter, pour chacune des valeurs possibles de la variable (pour chacune des modalités), le nombre d’observations ayant cette valeur. Un tri à plat s’obtient sous R à l’aide de la fonction <code>table</code> :</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1"><span class="kw">table</span>(d<span class="op">$</span>sexe)</a></code></pre></div>
<pre><code>## 
## Homme Femme 
##   899  1101</code></pre>
<p>Ce tableau nous indique donc que parmi nos enquêtés on trouve 899 hommes et 1101 femmes.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1"><span class="kw">table</span>(d<span class="op">$</span>qualif)</a></code></pre></div>
<pre><code>## 
##       Ouvrier specialise         Ouvrier qualifie               Technicien 
##                      203                      292                       86 
## Profession intermediaire                    Cadre                  Employe 
##                      160                      260                      594 
##                    Autre 
##                       58</code></pre>
<p>Un tableau de ce type peut être affiché ou stocké dans un objet, et on peut à son tour lui appliquer des fonctions. Par exemple, la fonction <code>sort</code> permet de trier le tableau selon la valeur de l’effectif. On peut donc faire :</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(d<span class="op">$</span>qualif)</a>
<a class="sourceLine" id="cb163-2" title="2"><span class="kw">sort</span>(tab)</a></code></pre></div>
<pre><code>## 
##                    Autre               Technicien Profession intermediaire 
##                       58                       86                      160 
##       Ouvrier specialise                    Cadre         Ouvrier qualifie 
##                      203                      260                      292 
##                  Employe 
##                      594</code></pre>
<div class="rmdimportant">
<p>
Attention, par défaut la fonction <code>table</code> n’affiche pas les valeurs manquantes (<code>NA</code>). Si on souhaite les inclure il faut utiliser l’argument <code>useNA = “always”</code>, soit : <code>table(d$qualif, useNA = “always”)</code>.
</p>
</div>
<p>À noter qu’on peut aussi appliquer <code>summary</code> à une variable qualitative. Le résultat est également le tri à plat de la variable, avec en plus le nombre de valeurs manquantes éventuelles :</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1"><span class="kw">summary</span>(d<span class="op">$</span>qualif)</a></code></pre></div>
<pre><code>##       Ouvrier specialise         Ouvrier qualifie               Technicien 
##                      203                      292                       86 
## Profession intermediaire                    Cadre                  Employe 
##                      160                      260                      594 
##                    Autre                     NA&#39;s 
##                       58                      347</code></pre>
<p>Par défaut ces tris à plat sont en effectifs et ne sont donc pas toujours très lisibles, notamment quand on a des effectifs importants. On leur rajoute donc en général la répartition en pourcentages. Pour cela, nous allons utiliser la fonction <code>freq</code> de l’extension <code>questionr</code>, qui devra donc avoir précédemment été chargée avec <code>library(questionr)</code> :</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1"><span class="co">## À rajouter en haut de script et à exécuter</span></a>
<a class="sourceLine" id="cb167-2" title="2"><span class="kw">library</span>(questionr)</a></code></pre></div>
<p>On peut alors utiliser la fonction :</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" title="1"><span class="kw">freq</span>(d<span class="op">$</span>qualif)</a></code></pre></div>
<pre><code>##                            n    % val%
## Ouvrier specialise       203 10.2 12.3
## Ouvrier qualifie         292 14.6 17.7
## Technicien                86  4.3  5.2
## Profession intermediaire 160  8.0  9.7
## Cadre                    260 13.0 15.7
## Employe                  594 29.7 35.9
## Autre                     58  2.9  3.5
## NA                       347 17.3   NA</code></pre>
<p>La colonne <code>n</code> représente les effectifs de chaque catégorie, la colonne <code>%</code> le pourcentage, et la colonne <code>val%</code> le pourcentage calculé sur les valeurs valides, donc en excluant les <code>NA</code>. Une ligne a également été rajoutée pour indiquer le nombre et la proportion de <code>NA</code>.</p>
<p><code>freq</code> accepte un certain nombre d’arguments pour personnaliser son affichage. Par exemple :</p>
<ul>
<li><code>valid</code> indique si on souhaite ou non afficher les pourcentages sur les valeurs valides</li>
<li><code>cum</code> indique si on souhaite ou non afficher les pourcentages cumulés</li>
<li><code>total</code> permet d’ajouter une ligne avec les effectifs totaux</li>
<li><code>sort</code> permet de trier le tableau par fréquence croissante (<code>sort="inc"</code>) ou décroissante (<code>sort="dec"</code>).</li>
</ul>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" title="1"><span class="kw">freq</span>(d<span class="op">$</span>qualif, <span class="dt">valid=</span> <span class="ot">FALSE</span>, <span class="dt">total =</span> <span class="ot">TRUE</span>, <span class="dt">sort =</span> <span class="st">&quot;dec&quot;</span>)</a></code></pre></div>
<pre><code>##                             n     %
## Employe                   594  29.7
## Ouvrier qualifie          292  14.6
## Cadre                     260  13.0
## Ouvrier specialise        203  10.2
## Profession intermediaire  160   8.0
## Technicien                 86   4.3
## Autre                      58   2.9
## NA                        347  17.3
## Total                    2000 100.0</code></pre>
</div>
<div id="représentations-graphiques" class="section level5">
<h5><span class="header-section-number">1.3.3.2.2</span> Représentations graphiques</h5>
<p>On peut représenter graphiquement le tri à plat d’une variable qualitative avec un diagramme en barres, obtenu avec la fonction <code>barplot</code>. Attention, contrairement à <code>hist</code> cette fonction ne s’applique pas directement à la variable mais au résultat du tri à plat de cette variable, calculé avec <code>table</code>. Il faut donc procéder en deux étapes :</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(d<span class="op">$</span>clso)</a>
<a class="sourceLine" id="cb172-2" title="2"><span class="kw">barplot</span>(tab)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-108-1.svg" width="672" /></p>
<p>On peut aussi trier le tri à plat avec la fonction <code>sort</code> avant de le représenter graphiquement, ce qui peut faciliter la lecture du graphique :</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="kw">barplot</span>(<span class="kw">sort</span>(tab))</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-109-1.svg" width="672" /></p>
<p>Une alternative au graphique en barres est le <em>diagramme de Cleveland</em>, qu’on peut obtenir avec la fonction <code>dotchart</code>. Celle-ci s’applique elle aussi au tri à plat de la variable calculé avec <code>table</code>.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" title="1"><span class="kw">dotchart</span>(<span class="kw">table</span>(d<span class="op">$</span>qualif))</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-110-1.svg" width="672" />
Là aussi, pour améliorer la lisibilité du graphique il est préférable de trier le tri à plat de la variable avant de le représenter :</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="kw">dotchart</span>(<span class="kw">sort</span>(<span class="kw">table</span>(d<span class="op">$</span>qualif)))</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-111-1.svg" width="672" /></p>
</div>
</div>
</div>
<div id="ex-introR-univ" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Exercices</h3>
<p><strong>Exercice 1</strong></p>
<p>Créer un nouveau script qui effectue les actions suivantes :</p>
<ul>
<li>charger l’extension <code>questionr</code></li>
<li>charger le jeu de données nommé <code>hdv2003</code></li>
<li>copier le jeu de données dans un nouvel objet nommé <code>df</code></li>
<li>afficher les dimensions et la liste des variables de <code>df</code></li>
</ul>

<div class="solution">
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" title="1"><span class="kw">library</span>(questionr)</a>
<a class="sourceLine" id="cb176-2" title="2"></a>
<a class="sourceLine" id="cb176-3" title="3"><span class="kw">data</span>(hdv2003)</a>
<a class="sourceLine" id="cb176-4" title="4">df &lt;-<span class="st"> </span>hdv2003</a>
<a class="sourceLine" id="cb176-5" title="5"></a>
<a class="sourceLine" id="cb176-6" title="6"><span class="kw">dim</span>(df)</a>
<a class="sourceLine" id="cb176-7" title="7"><span class="kw">names</span>(df)</a></code></pre></div>
</div>

<p><strong>Exercice 2</strong></p>
<p>On souhaite étudier la répartition du temps passé devant la télévision par les enquêtés (variable <code>heures.tv</code>). Pour cela, affichez les principaux indicateurs de cette variable : valeur minimale, maximale, moyenne, médiane et écart-type. Représentez ensuite sa distribution par un histogramme en 10 classes.</p>

<div class="solution">
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1"><span class="kw">summary</span>(df<span class="op">$</span>heures.tv)</a>
<a class="sourceLine" id="cb177-2" title="2"><span class="kw">sd</span>(df<span class="op">$</span>heures.tv)</a>
<a class="sourceLine" id="cb177-3" title="3"></a>
<a class="sourceLine" id="cb177-4" title="4"><span class="kw">hist</span>(df<span class="op">$</span>heures.tv, <span class="dt">breaks =</span> <span class="dv">10</span>)</a></code></pre></div>
</div>

<p><strong>Exercice 3</strong></p>
<p>On s’intéresse maintenant à l’importance accordée par les enquêtés à leur travail (variable <code>trav.imp</code>). Faites un tri à plat des effectifs des modalités de cette variable avec la commande <code>table</code>.</p>

<div class="solution">
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1"><span class="kw">table</span>(df<span class="op">$</span>trav.imp)</a></code></pre></div>
</div>

<p>Faites un tri à plat affichant à la fois les effectifs et les pourcentages de chaque modalité. Y’a-t-il des valeurs manquantes ?</p>

<div class="solution">
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="kw">freq</span>(df<span class="op">$</span>trav.imp)</a></code></pre></div>
</div>

<p>Représentez graphiquement les effectifs des modalités à l’aide d’un graphique en barres.</p>

<div class="solution">
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">sort</span>(<span class="kw">table</span>(df<span class="op">$</span>trav.imp))</a>
<a class="sourceLine" id="cb180-2" title="2"><span class="kw">barplot</span>(tab)</a></code></pre></div>
</div>

<p>Utilisez l’argument <code>col</code> de la fonction <code>barplot</code> pour modifier la couleur du graphique en
<code>tomato</code>.</p>

<div class="solution">
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1"><span class="kw">barplot</span>(tab, <span class="dt">col =</span> <span class="st">&quot;tomato&quot;</span>)</a></code></pre></div>
</div>

<p>Tapez <code>colors()</code> dans la console pour afficher l’ensemble des noms de couleurs disponibles dans R. Testez chaque couleur une à une pour trouver votre couleur préférée.</p>

<div class="solution">
<p>C’est une blague, hein ! Cela dit <code>moccasin</code> ou <code>palevioletred</code> sont pas mal, si vous voulez essayer :-)</p>
</div>


</div>
</div>
<div id="analyse-de-2-variables" class="section level2">
<h2><span class="header-section-number">1.4</span> Analyse de 2 variables</h2>
<p>Faire une analyse bivariée, c’est étudier la relation entre deux variables : sont-elles liées ? les valeurs de l’une influencent-elles les valeurs de l’autre ? ou sont-elles au contraire indépendantes ?</p>
<p>À noter qu’on va parler ici d’influence ou de lien, mais pas de relation de cause à effet : les outils présentés permettent de visualiser ou de déterminer une relation, mais des liens de causalité proprement dit sont plus difficiles à mettre en évidence. Il faut en effet vérifier que c’est bien telle variable qui influence telle autre et pas l’inverse, qu’il n’y a pas de “variable cachée”, etc.</p>
<p>Là encore, le type d’analyse ou de visualisation est déterminé par la nature qualitative ou quantitative des deux variables.</p>
<div id="croisement-de-deux-variables-qualitatives" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Croisement de deux variables qualitatives</h3>
<div id="tableaux-croisés" class="section level4">
<h4><span class="header-section-number">1.4.1.1</span> Tableaux croisés</h4>
<p>On va continuer à travailler avec le jeu de données tiré de l’enquête <em>Histoire de vie</em> inclus dans l’extension <code>questionr</code>. On commence donc par charger l’extension, le jeu de données, et à le renommer en un nom plus court pour gagner un peu de temps de saisie au clavier :</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">library</span>(questionr)</a>
<a class="sourceLine" id="cb182-2" title="2"><span class="kw">data</span>(hdv2003)</a>
<a class="sourceLine" id="cb182-3" title="3">d &lt;-<span class="st"> </span>hdv2003</a></code></pre></div>
<p>Quand on veut croiser deux variables qualitatives, on fait un <em>tableau croisé</em>. Comme pour un tri à plat ceci s’obtient avec la fonction <code>table</code> de R, mais à laquelle on passe cette fois deux variables en argument. Par exemple, si on veut croiser la catégorie socio-professionnelle et le sexe des enquêtés :</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="kw">table</span>(d<span class="op">$</span>qualif, d<span class="op">$</span>sexe)</a></code></pre></div>
<pre><code>##                           
##                            Homme Femme
##   Ouvrier specialise          96   107
##   Ouvrier qualifie           229    63
##   Technicien                  66    20
##   Profession intermediaire    88    72
##   Cadre                      145   115
##   Employe                     96   498
##   Autre                       21    37</code></pre>
<p>Pour pouvoir interpréter ce tableau on doit passer du tableau en effectifs au tableau en pourcentages ligne ou colonne. Pour cela, on peut utiliser les fonctions <code>lprop</code> et <code>cprop</code> de l’extension <code>questionr</code>, qu’on applique au tableau croisé précédent.</p>
<p>Pour calculer les pourcentages ligne :</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(d<span class="op">$</span>qualif, d<span class="op">$</span>sexe)</a>
<a class="sourceLine" id="cb185-2" title="2"><span class="kw">lprop</span>(tab)</a></code></pre></div>
<pre><code>##                           
##                            Homme Femme Total
##   Ouvrier specialise        47.3  52.7 100.0
##   Ouvrier qualifie          78.4  21.6 100.0
##   Technicien                76.7  23.3 100.0
##   Profession intermediaire  55.0  45.0 100.0
##   Cadre                     55.8  44.2 100.0
##   Employe                   16.2  83.8 100.0
##   Autre                     36.2  63.8 100.0
##   All                       44.8  55.2 100.0</code></pre>
<p>Et pour les pourcentages colonne :</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="kw">cprop</span>(tab)</a></code></pre></div>
<pre><code>##                           
##                            Homme Femme All  
##   Ouvrier specialise        13.0  11.7  12.3
##   Ouvrier qualifie          30.9   6.9  17.7
##   Technicien                 8.9   2.2   5.2
##   Profession intermediaire  11.9   7.9   9.7
##   Cadre                     19.6  12.6  15.7
##   Employe                   13.0  54.6  35.9
##   Autre                      2.8   4.1   3.5
##   Total                    100.0 100.0 100.0</code></pre>
<div class="rmdnote">
<p>
Pour savoir si on doit faire des pourcentages ligne ou colonne, on pourra se référer à l’article suivant :
</p>
<p>
<a href="http://alain-leger.lescigales.org/textes/lignecolonne.pdf" class="uri">http://alain-leger.lescigales.org/textes/lignecolonne.pdf</a>
</p>
<p>
En résumé, quand on fait un tableau croisé, celui-ci est parfaitement symétrique : on peut inverser les lignes et les colonnes, ça ne change pas son interprétation. Par contre, on a toujours en tête un “sens” de lecture dans le sens où on considère que l’une des variables <em>dépend</em> de l’autre. Par exemple, si on croise sexe et type de profession, on dira que le type de profession dépend du sexe, et non l’inverse : le type de profession est alors la variable <em>dépendante</em> (à expliquer), et le sexe la variable <em>indépendante</em> (explicative).
</p>
<p>
Pour faciliter la lecture d’un tableau croisé, il est recommandé de <strong>faire les pourcentages sur la variable indépendante</strong>. Dans notre exemple, la variable indépendante est le sexe, elle est en colonne, on calcule donc les pourcentages colonnes qui permettent de comparer directement, pour chaque sexe, la répartition des catégories socio-professionnelles.
</p>
</div>
<!--### Test du χ²

Comme on travaille sur un échantillon et pas sur une population entière, on peut compléter ce tableau croisé par un test d'indépendance du χ². Celui-ci permet de rejeter l'hypothèse d'indépendance des lignes et des colonnes du tableau, c'est à dire de rejeter l'hypothèse que les écarts à l'indépendance observés seraient uniquement dus au biais d'échantillonnage (au fait qu'on n'a pas interrogé toute notre population).

Pour effectuer un test de ce type, on applique la fonction `chisq.test` au tableau croisé calculé précédemment :


```r
chisq.test(tab)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  tab
## X-squared = 387.56, df = 6, p-value < 2.2e-16
```

Le résultat nous indique trois valeurs :

- `X-squared`, la valeur de la statistique du χ² pour notre tableau, c'est-à-dire une "distance" entre notre tableau observé et celui attendu si les deux variables étaient indépendantes.
- `df`, le nombre de degrés de libertés du test.
- `p-value`, le fameux *p*, qui indique la probabilité d'obtenir une valeur de la statistique du χ² au moins aussi extrême sous l'hypothèse d'indépendance.

Ici, le *p* est extrêmement petit (la notation `< 2.2e-16` indique qu'il est plus petit que la plus petite valeur proche de zéro calculable par R), donc certainement en-dessous du seuil de décision choisi préalablement au test (souvent 5%, soit 0.05). On peut donc rejeter l'hypothèse d'indépendance des lignes et des colonnes du tableau.

En complément du test du χ², on peut aussi regarder les *résidus* de ce test pour affiner la lecture du tableau. Ceux-ci s'obtiennent avec la fonction `chisq.residuals` de `questionr` :


```r
chisq.residuals(tab)
```

```
##                           
##                             Homme  Femme
##   Ouvrier specialise         0.52  -0.47
##   Ouvrier qualifie           8.57  -7.73
##   Technicien                 4.42  -3.98
##   Profession intermediaire   1.92  -1.73
##   Cadre                      2.64  -2.38
##   Employe                  -10.43   9.41
##   Autre                     -0.98   0.88
```

L'interprétation des résidus est la suivante :

- si la valeur du résidu pour une case est inférieure à -2, alors il y a une sous-représentation de cette case dans le tableau : les effectifs sont significativement plus faibles que ceux attendus sous l'hypothèse d'indépendance
- à l'inverse, si le résidu est supérieur à 2, il y a sur-représentatation de cette case
- si le résidu est compris entre -2 et 2, il n'y a pas d'écart à l'indépendance significatif

Les résidus peuvent être une aide utile à l'interprétation, notamment pour des tableaux de grande dimension.
-->
</div>
<div id="représentation-graphique" class="section level4">
<h4><span class="header-section-number">1.4.1.2</span> Représentation graphique</h4>
<p>Il est possible de faire une représentation graphique d’un tableau croisé, par exemple avec la fonction <code>mosaicplot</code> :</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="kw">mosaicplot</span>(tab)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-125-1.svg" width="576" /></p>
<p>On peut améliorer ce graphique en colorant les cases selon les résidus du test du χ² (argument <code>shade = TRUE</code>) et en orientant verticalement les labels de colonnes (argument <code>las = 3</code>) :</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1"><span class="kw">mosaicplot</span>(tab, <span class="dt">las =</span> <span class="dv">3</span>, <span class="dt">shade =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-126-1.svg" width="576" /></p>
<p>Chaque rectangle de ce graphique représente une case de tableau. Sa largeur correspond au pourcentage des modalités en colonnes (il y’a beaucoup d’employés et d’ouvriers et très peu d’“autres”). Sa hauteur correspond aux pourcentages colonnes : la proportion d’hommes chez les cadres est plus élevée que chez les employés. Enfin, la couleur de la case correspond au résidu du test du χ² correspondant : les cases en rouge sont sous-représentées, les cases en bleu sur-représentées, et les cases blanches sont proches des effectifs attendus sous l’hypothèse d’indépendance.</p>
</div>
</div>
<div id="croisement-dune-variable-quantitative-et-dune-variable-qualitative" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Croisement d’une variable quantitative et d’une variable qualitative</h3>
<div id="représentation-graphique-1" class="section level4">
<h4><span class="header-section-number">1.4.2.1</span> Représentation graphique</h4>
<p>Croiser une variable quantitative et une variable qualitative, c’est essayer de voir si les valeurs de la variable quantitative se répartissent différemment selon la catégorie d’appartenance de la variable qualitative.</p>
<p>Pour cela, l’idéal est de commencer par une représentation graphique de type “boîte à moustache” à l’aide de la fonction <code>boxplot</code>. Par exemple, si on veut visualiser la répartition des âges selon la pratique ou non d’un sport, on va utiliser la syntaxe suivante :</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1"><span class="kw">boxplot</span>(d<span class="op">$</span>age <span class="op">~</span><span class="st"> </span>d<span class="op">$</span>sport)</a></code></pre></div>
<div class="rmdnote">
<p>
Cette syntaxe de <code>boxplot</code> utilise une nouvelle notation de type “formule”. Celle-ci est utilisée notamment pour la spécification des modèles de régression. Ici le <code>~</code> peut se lire comme “en fonction de” : on veut représenter le boxplot de l’âge en fonction du sport.
</p>
</div>
<p>Ce qui va nous donner le résultat suivant :</p>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-129-1.svg" width="672" /></p>
<div class="rmdnote">
<p>
L’interprétation d’un boxplot est la suivante : Les bords inférieurs et supérieurs du carré central représentent le premier et le troisième quartile de la variable représentée sur l’axe vertical. On a donc 50% de nos observations dans cet intervalle. Le trait horizontal dans le carré représente la médiane. Enfin, des “moustaches” s’étendent de chaque côté du carré, jusqu’aux valeurs minimales et maximales, avec une exception : si des valeurs sont éloignées du carré de plus de 1,5 fois l’écart interquartile (la hauteur du carré), alors on les représente sous forme de points (symbolisant des valeurs considérées comme “extrêmes”).
</p>
</div>
<p>Dans le graphique ci-dessus, on voit que ceux qui ont pratiqué un sport au cours des douze derniers mois ont l’air d’être sensiblement plus jeunes que les autres.</p>
</div>
<div id="calculs-dindicateurs" class="section level4">
<h4><span class="header-section-number">1.4.2.2</span> Calculs d’indicateurs</h4>
<p>On peut aussi vouloir comparer certains indicateurs (moyenne, médiane) d’une variable quantitative selon les modalités d’une variable qualitative. Si on reprend l’exemple précédent, on peut calculer la moyenne d’âge pour ceux qui pratiquent un sport et pour ceux qui n’en pratiquent pas.</p>
<p>Une première méthode pour cela est d’extraire de notre population autant de sous-populations qu’il y a de modalités dans la variable qualitative. On peut le faire notamment avec la fonction <code>filter</code> du package <code>dplyr</code>.</p>
<!-- ^[Le package en question est présenté en détail dans la partie \@ref(dplyr).]. -->
<p>On commence par charger <code>dplyr</code> (en l’ayant préalablement installé) :</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" title="1"><span class="kw">library</span>(dplyr)</a></code></pre></div>
<p>Puis on applique <code>filter</code> pour créer deux sous-populations, stockées dans deux nouveaux tableaux de données :</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1">d_sport &lt;-<span class="st"> </span><span class="kw">filter</span>(d, sport <span class="op">==</span><span class="st"> &quot;Oui&quot;</span>)</a>
<a class="sourceLine" id="cb193-2" title="2">d_nonsport &lt;-<span class="st"> </span><span class="kw">filter</span>(d, sport <span class="op">==</span><span class="st"> &quot;Non&quot;</span>)</a></code></pre></div>
<p>On peut ensuite utiliser ces deux nouveaux tableaux de données comme on en a l’habitude, et calculer les deux moyennes d’âge :</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1"><span class="kw">mean</span>(d_sport<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 40.92531</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="kw">mean</span>(d_nonsport<span class="op">$</span>age)</a></code></pre></div>
<pre><code>## [1] 52.25137</code></pre>
<p>Une autre possibilité est d’utiliser la fonction <code>tapply</code>, qui prend en paramètre une variable quantitative, une variable qualitative et une fonction, puis applique automatiquement la fonction aux valeurs de la variables quantitative pour chaque niveau de la variable qualitative :</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1"><span class="kw">tapply</span>(d<span class="op">$</span>age, d<span class="op">$</span>sport, mean)</a></code></pre></div>
<pre><code>##      Non      Oui 
## 52.25137 40.92531</code></pre>
<!-- ### Tests statistiques

Un des tests les plus connus est le test du *t* de Student, qui permet de tester si les moyennes de deux sous-populations peuvent être considérées comme différentes (compte tenu des fluctuations aléatoires provenant du biais d'échantillonnage).

Un test *t* s'effectue à l'aide de la fonction `t.test`. Ainsi, on peut tester l'hypothèse d'égalité des âges moyens selon la pratique ou non d'un sport avec la commande suivante :


```r
t.test(d$age ~ d$sport)
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  d$age by d$sport
## t = 15.503, df = 1600.4, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.893117 12.759002
## sample estimates:
## mean in group Non mean in group Oui 
##          52.25137          40.92531
```

Le résultat du test est significatif, avec un *p* extrêmement petit, et on peut rejeter l'hypothèse nulle d'égalité des moyennes des deux groupes. Le test nous donne même un intervalle de confiance à 95% pour la valeur de la différence entre les deux moyennes.

Nous sommes cependant allés un peu vite, et avons négligé le fait que le test *t* s'applique normalement à des distributions normales. On peut se faire un premier aperçu visuel de cette normalité en traçant les histogrammes des deux répartitions :


```r
hist(d_sport$age)
```

<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-137-1.svg" width="672" />


```r
hist(d_nonsport$age)
```

<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-138-1.svg" width="672" />

Si l'âge dans le groupe des non sportifs se rapproche d'une distribution normale, celui des sportifs en semble assez éloigné, notamment du fait de la limite d'âge à 18 ans imposée par construction de l'enquête.

On peut tester cette normalité à l'aide du test de Shapiro-Wilk et de la fonction `shapiro.test` :



```r
shapiro.test(d_sport$age)
```

```
## 
## 	Shapiro-Wilk normality test
## 
## data:  d_sport$age
## W = 0.96203, p-value = 9.734e-13
```


```r
shapiro.test(d_nonsport$age)
```

```
## 
## 	Shapiro-Wilk normality test
## 
## data:  d_nonsport$age
## W = 0.98844, p-value = 1.654e-08
```

Le test est significatif dans les deux cas et rejette l'hypothèse d'une normalité des deux distributions.

Dans ce cas on peut faire appel à un test non-paramétrique, qui ne fait donc pas d'hypothèses sur les lois de distribution des variables testées, en l'occurrence le test des rangs de Wilcoxon, à l'aide de la fonction `wilcox.test` :


```r
wilcox.test(d$age ~ d$sport)
```

```
## 
## 	Wilcoxon rank sum test with continuity correction
## 
## data:  d$age by d$sport
## W = 640577, p-value < 2.2e-16
## alternative hypothesis: true location shift is not equal to 0
```

La valeur *p* étant à nouveau extrêmement petite, on peut rejeter l'hypothèse d'indépendance et considérer que les distributions des âges dans les deux sous-populations sont différentes.
-->
</div>
</div>
<div id="croisement-de-deux-variables-quantitatives" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Croisement de deux variables quantitatives</h3>
<p>Le jeu de données <code>hdv2003</code> comportant assez peu de variables quantitatives, on va s’intéresser maintenant à un autre jeu de données comportant des informations du recensement de la population de 2012. On le charge avec :</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1"><span class="kw">data</span>(rp2012)</a></code></pre></div>
<p>Un nouveau tableau de données <code>rp2012</code> devrait apparaître dans votre environnement. Celui-ci comprend les 5170 communes de France métropolitaine de plus de 2000 habitants, et une soixantaine de variables telles que le département, la population, le taux de chômage, etc. Pour une description plus complète et une liste des variables, voir section <a href="#rp2012"><strong>??</strong></a>.</p>
<div id="représentation-graphique-2" class="section level4">
<h4><span class="header-section-number">1.4.3.1</span> Représentation graphique</h4>
<p>Quand on croise deux variables quantitatives, l’idéal est de faire une représentation graphique sous forme de nuage de points à l’aide de la fonction <code>plot</code>. On va représenter le croisement entre le pourcentage de cadres et le pourcentage de propriétaires dans la commune :</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1"><span class="kw">plot</span>(rp2012<span class="op">$</span>cadres, rp2012<span class="op">$</span>proprio)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-143-1.svg" width="672" /></p>
<p>Une représentation graphique est l’idéal pour visualiser l’existence d’un lien entre les deux variables. Voici quelques exemples d’interprétation :</p>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-144-1.svg" width="576" /></p>
<p>Dans ce premier graphique généré sur nos données, il semble difficile de mettre en évidence une relation de dépendance. Si par contre on croise le pourcentage de cadres et celui de diplômés du supérieur, on obtient une belle relation de dépendance linéaire.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1"><span class="kw">plot</span>(rp2012<span class="op">$</span>cadres, rp2012<span class="op">$</span>dipl_sup)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/unnamed-chunk-145-1.svg" width="672" /></p>
<!-- ### Calcul d'indicateurs

En plus d'une représentation graphique, on peut calculer certains indicateurs permettant de mesurer le degré d'association de deux variables quantitatives.

##### Corrélation linéaire (Pearson)

La corrélation est une mesure du lien d'association *linéaire* entre deux variables quantitatives. Sa valeur varie entre -1 et 1. Si la corrélation vaut -1, il s'agit d'une association linéaire négative parfaite. Si elle vaut 1, il s'agit d'une association linéaire positive parfaite. Si elle vaut 0, il n'y a aucune association linéaire entre les variables.

On la calcule dans R à l'aide de la fonction `cor`.

Ainsi la corrélation entre le pourcentage de cadres et celui de diplômés du supérieur vaut :


```r
cor(rp2012$cadres, rp2012$dipl_sup)
```

```
## [1] 0.9371629
```

Ce qui est extrêmement fort. Il y a donc un lien linéaire et positif entre les deux variables (quand la valeur de l'une augmente, la valeur de l'autre augmente également).

À l'inverse, la corrélation entre le pourcentage de cadres et le pourcentage de propriétaires vaut :


```r
cor(rp2012$cadres, rp2012$proprio)
```

```
## [1] 0.1622786
```

Ce qui indique, pour nos données, une absence de liaison linéaire entre les deux variables.




##### Corrélation des rangs (Spearman)

Le coefficient de corrélation de Pearson ci-dessus fait une hypothèse forte sur les données : elles doivent être liées par une association linéaire. Quand ça n'est pas le cas mais qu'on est en présence d'une association monotone, on peut utiliser un autre coefficient, le coefficient de corrélation des rangs de Spearman.

Plutôt que de se baser sur les valeurs des variables, cette corrélation va se baser sur leurs rangs, c'est-à-dire sur leur position parmi les différentes valeurs prises par les variables.

Ainsi, si la valeur la plus basse de la première variable est associée à la valeur la plus basse de la deuxième, et ainsi de suite jusqu'à la valeur la plus haute, on obtiendra une corrélation de 1. Si la valeur la plus forte de la première variable est associée à la valeur la plus faible de la seconde, et ainsi de suite, et que la valeur la plus faible de la première est associée à la plus forte de la deuxième, on obtiendra une corrélation de -1. Si les rangs sont "mélangés", sans rapports entre eux, on obtiendra une corrélation autour de 0.


<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-148-1.svg" width="576" />

La corrélation des rangs a aussi pour avantage d'être moins sensibles aux valeurs extrêmes ou aux points isolés. On dit qu'elle est plus "robuste".

Pour calculer une corrélation de Spearman, on utilise la fonction `cor` mais avec l'argument `method = "spearman"` :


```r
cor(rp2012$cadres, rp2012$dipl_sup, method = "spearman")
```

```
## [1] 0.9036273
```

#### Régression linéaire

Quand on est en présence d'une association linéaire entre deux variables, on peut vouloir faire la régression linéaire d'une des variables sur l'autres.

Une régression linéaire simple se fait à l'aide de la fonction `lm` :


```r
lm(rp2012$cadres ~ rp2012$dipl_sup)
```

```
## 
## Call:
## lm(formula = rp2012$cadres ~ rp2012$dipl_sup)
## 
## Coefficients:
##     (Intercept)  rp2012$dipl_sup  
##          0.9217           1.0816
```

<div class="rmdnote">
<p>On retrouve avec <code>lm</code> la syntaxe “formule” déjà rencontrée avec <code>boxplot</code>. Elle permet ici de spécifier des modèles de régression : la variable dépendante se place à gauche du <code>~</code>, et la variable indépendante à droite. Si on souhaite faire une régression multiple avec plusieurs variables indépendantes, on aura une formule du type <code>dep ~ indep1 + indep2</code>. Il est également possible de spécifier des termes plus complexes, des interactions, etc.</p>
</div>

`lm` nous renvoie par défaut les coefficients de la droite de régression :

- l'ordonnée à l'origine `(Intercept)` vaut 0.92
- le coefficient associé à `dipl_sup` vaut 1.08

Pour des résultats plus détaillés, on peut stocker le résultat de la régression dans un objet et utiliser la fonction `summary` :


```r
reg <- lm(rp2012$cadres ~ rp2012$dipl_sup)
summary(reg)
```

```
## 
## Call:
## lm(formula = rp2012$cadres ~ rp2012$dipl_sup)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.218  -1.606  -0.172   1.491  13.001 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     0.921661   0.071814   12.83   <2e-16 ***
## rp2012$dipl_sup 1.081636   0.005601  193.10   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.701 on 5168 degrees of freedom
## Multiple R-squared:  0.8783,	Adjusted R-squared:  0.8783 
## F-statistic: 3.729e+04 on 1 and 5168 DF,  p-value: < 2.2e-16
```

Ces résultats montrent notamment que les coefficients sont significativement
différents de 0. La part de cadres augmente donc bien avec celle de diplômés du supérieur.

On peut enfin représenter la droite de régression sur notre nuage de points à l'aide de la fonction `abline` :


```r
plot(rp2012$dipl_sup, rp2012$cadres)
abline(reg, col="red")
```

<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-153-1.svg" width="672" />
-->
</div>
</div>
<div id="ex-introR-biv" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Exercices</h3>
<p><strong>Exercice 1</strong></p>
<p>Dans le jeu de données <code>hdv2003</code>, faire le tableau croisé entre la catégorie socio-professionnelle (variable <code>qualif</code>) et le fait de croire ou non en l’existence des classes sociales (variable <code>clso</code>). Identifier la variable indépendante et la variable dépendante, et calculer les pourcentages ligne ou colonne. Interpréter le résultat.</p>

<div class="solution">
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" title="1"><span class="kw">library</span>(questionr)</a>
<a class="sourceLine" id="cb203-2" title="2"><span class="kw">data</span>(hdv2003)</a>
<a class="sourceLine" id="cb203-3" title="3">tab &lt;-<span class="st"> </span><span class="kw">table</span>(hdv2003<span class="op">$</span>qualif, hdv2003<span class="op">$</span>clso)</a>
<a class="sourceLine" id="cb203-4" title="4"></a>
<a class="sourceLine" id="cb203-5" title="5"><span class="co">## Ici la variable indépendante est `qualif`, on calcule donc</span></a>
<a class="sourceLine" id="cb203-6" title="6"><span class="co">## les pourcentages lignes</span></a>
<a class="sourceLine" id="cb203-7" title="7"><span class="kw">lprop</span>(tab)</a></code></pre></div>
</div>

<!--
Faire un test du χ². Peut-on rejeter l'hypothèse d'indépendance ?

\iffalse
<div class="solution">

```r
chisq.test(tab)

## On peut rejeter l'hypothèse d'indépendance au seuil de 0.05,
## et même au seuil de 0.001
```
</div>
\fi
-->
<p>Représenter ce tableau croisé sous la forme d’un <code>mosaicplot</code> en colorant les cases selon les résidus du test du χ².</p>

<div class="solution">
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1"><span class="kw">mosaicplot</span>(tab, <span class="dt">shade =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
</div>

<p><strong>Exercice 2</strong></p>
<p>Toujours sur le jeu de données <code>hdv2003</code>, faire le boxplot qui croise le nombre d’heures passées devant la télévision (variable <code>heures.tv</code>) avec le statut d’occupation (variable <code>occup</code>).</p>

<div class="solution">
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" title="1"><span class="kw">boxplot</span>(hdv2003<span class="op">$</span>heures.tv <span class="op">~</span><span class="st"> </span>hdv2003<span class="op">$</span>occup)</a></code></pre></div>
</div>

<p>Calculer la durée moyenne devant la télévision en fonction du statut d’occupation à l’aide de <code>tapply</code>.</p>

<div class="solution">
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1"><span class="kw">tapply</span>(hdv2003<span class="op">$</span>heures.tv, hdv2003<span class="op">$</span>occup, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
</div>

<p><strong>Exercice 3</strong></p>
<p>Sur le jeu de données <code>rp2012</code>, représenter le nuage de points croisant le pourcentage de personnes sans diplôme (variable <code>dipl_aucun</code>) et le pourcentage de propriétaires (variable <code>proprio</code>).</p>

<div class="solution">
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" title="1"><span class="kw">library</span>(questionr)</a>
<a class="sourceLine" id="cb207-2" title="2"><span class="kw">data</span>(rp2012)</a>
<a class="sourceLine" id="cb207-3" title="3"><span class="kw">plot</span>(rp2012<span class="op">$</span>dipl_aucun, rp2012<span class="op">$</span>proprio)</a></code></pre></div>
</div>

<!--
Calculer le coefficient de corrélation linéaire correspondant.

\iffalse
<div class="solution">

```r
cor(rp2012$dipl_aucun, rp2012$proprio)
```
</div>
\fi
-->

</div>
</div>
<div id="gérer-les-données" class="section level2">
<h2><span class="header-section-number">1.5</span> Gérer les données</h2>
<div id="importer-et-exporter-des-données" class="section level3">
<h3><span class="header-section-number">1.5.1</span> Importer et exporter des données</h3>
<p>Il existe de multiple format four sauvegarder les données, les 2 plus utiles sont <code>.csv</code> et <code>.Rdata</code>.
Les fichiers <code>.csv</code> sont utilisés pour stocker des données.
Ils sont ouvrables par les éditeurs de texte (e.g. Word, Writer, atom, …) et les tableurs (e.g. MS Excel, LO Calc).
Les fichiers <code>.Rdata</code> sont utilisés pour stocker n’importe quelle objet R pas uniquement des données.
Cependant, ces fichiers ne peuvent être lus et utilisés que par R.</p>
<p>Les données pour les exercices de laboratoire et pour les devoirs vous sont fournies déjà en format <code>.csv</code>.</p>
<div id="ouvrir-un-fichier-de-données-en-format-.rdata" class="section level4">
<h4><span class="header-section-number">1.5.1.1</span> Ouvrir un fichier de données en format <code>.Rdata</code></h4>
<p>Pour ouvrir ces fichiers, vous pouvez cliquer dessus et laisser votre système d’exploitation démarrer une nouvelle session de R ou encore, à partir de la console de R, taper sur une ligne de commande :</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1"><span class="kw">load</span>(<span class="kw">file.choose</span>())</a></code></pre></div>
<p>ce qui ouvrira une boîte de dialogue vous permettant d’aller choisir un fichier sur votre ordinateur.
Si cette option semble très attirante de part sa simplicité, je ne recommande pas de s’en servir car elle ne permet pas de reproduire l’analyse facilement. En effet, elle nécessite de choisir le document chaque que l’on souhaite l’utiliser.</p>
<p>Vous pouvez aussi directement taper le nom du fichier entre guillemet <code>"nom du fichier avec l'extension"</code>.
Par exemple,</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" title="1"><span class="kw">load</span>(<span class="st">&quot;ErablesGatineau.Rdata&quot;</span>)</a></code></pre></div>
</div>
<div id="ouvrir-un-fichier-de-données-en-format-.csv" class="section level4">
<h4><span class="header-section-number">1.5.1.2</span> Ouvrir un fichier de données en format <code>.csv</code></h4>
<p>Pour importer ces données en format <code>.csv</code> dans R, il faut utiliser la commande <code>read.csv()</code>.
Par exemple, pour créer un objet R <code>erables</code> qui contient les données du fichier <code>ErablesGatineau.csv</code>, il faut utiliser la commande suivant.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1">erables &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/ErablesGatineau.csv&quot;</span>)</a></code></pre></div>

<div class="rmdwarning">
Attention si vous travaillez dans une langue utilisant la virgule au lieu du point décimal.
Par défaut, R utilise le point décimal et vous n’obtiendrez pas le résultat escompté.
Il existe une version modifiée de <code>read.csv()</code> appelée <code>read.csv2()</code> qui règle ce problème.
Googlez-la si vous en avez besoin.
</div>

<p>Pour vérifier si les données ont bel et bien été lues, vous pouvez lister les objets en mémoire avec la fonction <code>ls()</code> ou en obtenir une liste avec une description plus détaillée avec <code>ls.str()</code>.</p>

<div class="rmdtip">
Je vous déconseille cependant, la fonction <code>ls.str()</code> car elle peut produire des sorties extrèmementn longue si vous avez beaucoup d’objet dans l’environnement R. Je vous suggère donc d’utliser <code>ls()</code> et ensuite <code>str()</code> sur l’objet qui vous intéresse.
</div>

<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" title="1"><span class="kw">ls</span>()</a></code></pre></div>
<pre><code>##  [1] &quot;anglais&quot;        &quot;chien&quot;          &quot;d&quot;              &quot;d_nonsport&quot;    
##  [5] &quot;d_sport&quot;        &quot;diplome&quot;        &quot;erables&quot;        &quot;hdv2003&quot;       
##  [9] &quot;imc&quot;            &quot;maths&quot;          &quot;p&quot;              &quot;poids&quot;         
## [13] &quot;precipitations&quot; &quot;reg&quot;            &quot;resultat&quot;       &quot;rp2012&quot;        
## [17] &quot;s&quot;              &quot;sport&quot;          &quot;tab&quot;            &quot;taille1&quot;       
## [21] &quot;taille2&quot;        &quot;taille3&quot;        &quot;taille4&quot;        &quot;taille5&quot;       
## [25] &quot;tailles&quot;        &quot;tailles_m&quot;      &quot;temperature&quot;    &quot;title&quot;         
## [29] &quot;x&quot;              &quot;y&quot;</code></pre>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb213-1" title="1"><span class="kw">str</span>(erables)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	100 obs. of  3 variables:
##  $ station: chr  &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; ...
##  $ diam   : num  22.4 36.1 44.4 24.6 17.7 ...
##  $ biom   : num  732 1171 673 1552 504 ...</code></pre>
<p>R confirme avoir en mémoire l’objet <code>erables</code>.
<code>erables</code> est un tableau de données rectangulaire (data.frame) contenant 100 observations (lignes) de 3 variables (colonnes): <code>station</code>, une variable de type Facteur avec 2 niveaux, et <code>diam</code> et <code>biom</code> qui sont 2 variables numériques.</p>
</div>
<div id="entrer-des-données" class="section level4">
<h4><span class="header-section-number">1.5.1.3</span> Entrer des données</h4>
<p>R n’est pas un environnement idéal pour entrer des données.
C’est possible, mais la syntaxe est lourde et peut inciter à s’arracher les cheveux.
Utilisez votre chiffrier préféré pour faire l’entrée de données.
Ce sera plus efficace et moins frustrant.</p>
</div>
<div id="nettoyercorriger-des-données" class="section level4">
<h4><span class="header-section-number">1.5.1.4</span> Nettoyer/corriger des données</h4>
<p>Une autre opération qui peut être frustrante en R.
Mon conseil : ne le faites pas là.
Retournez au fichier original, faites la correction, puis re-exportez les données vers R.
Il est finalement plus simple de refaire exécuter les quelques lignes de code par la machine.
Vous aurez à la fin une seule version (corrigée) de vos données et un code qui vous permet de refaire votre analyse.</p>
</div>
<div id="exporter-des-données-à-partir-de-r." class="section level4">
<h4><span class="header-section-number">1.5.1.5</span> Exporter des données à partir de R.</h4>
<p>Vous pouvez utiliser la fonction,</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1">  <span class="kw">write.csv</span>(mydata, <span class="dt">file =</span> <span class="st">&quot;outfilename.csv&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p>où <code>mydata</code> est le nom du base de données à exporter et <code>outfilename.csv</code> est le nom du fichier à produire.
Notez que ce fichier sera créé dans le répertoire de travail (qui peut être changé par le menu à <code>File&gt;Change dir</code>, ou par la commande <code>setwd()</code>)</p>
</div>
</div>
<div id="examen-préliminaire-des-données" class="section level3">
<h3><span class="header-section-number">1.5.2</span> Examen préliminaire des données</h3>
<p>La première étape de toute analyse est l’examen des données.
Elle nous permet de découvrir si on a bien importé les données, si les nombres enregistrés sont possibles, si toutes les données ont bien été lues, etc.
L’examen préliminaire des données permet souvent aussi d’identifier des observations suspectes, possiblement dûes à des erreurs d’entrée de donnée.
Finalement, l’examen graphique préliminaire permet en général de visualiser les tendances principales qui seront confirmées par l’analyse statistique en tant que telle.
Le fichier <code>sturgeon.csv</code> contient les données d’une étude effectuée sur les esturgeons de la rivière Saskatchewan.
Ces données ont été récoltées, entre autres, pour examiner comment la taille des esturgeons varie entre les sexes (sex), les sites (location), et les années (year).</p>
<!-- - Pour recommencer avec une ardoise vide, videz la mémoire de R de tout son contenu en tapant la commande `rm(list=ls())`-->
<ul>
<li>Chargez les données du fichier <code>sturgeon.csv</code> dans un objet <code>sturgeon</code>.</li>
<li>Pour obtenir un aperçu des éléments du fichier qui ont été chargés en mémoire, taper la commande <code>str(sturgeon)</code>.</li>
</ul>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1">sturgeon &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/sturgeon.csv&quot;</span>)</a>
<a class="sourceLine" id="cb216-2" title="2"><span class="kw">str</span>(sturgeon)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	186 obs. of  9 variables:
##  $ fklngth : num  37 50.2 28.9 50.2 45.6 ...
##  $ totlngth: num  40.7 54.1 31.3 53.1 49.5 ...
##  $ drlngth : num  23.6 31.5 17.3 32.3 32.1 ...
##  $ rdwght  : num  15.95 NA 6.49 NA 29.92 ...
##  $ age     : int  11 24 7 23 20 23 20 7 23 19 ...
##  $ girth   : num  40.5 53.5 31 52.5 50 54.2 48 28.5 44 39 ...
##  $ sex     : chr  &quot;MALE&quot; &quot;FEMALE&quot; &quot;MALE&quot; &quot;FEMALE&quot; ...
##  $ location: chr  &quot;THE_PAS&quot; &quot;THE_PAS&quot; &quot;THE_PAS&quot; &quot;THE_PAS&quot; ...
##  $ year    : int  1978 1978 1978 1978 1978 1978 1978 1978 1978 1978 ...</code></pre>
<div id="sommaire-statistique" class="section level4">
<h4><span class="header-section-number">1.5.2.1</span> Sommaire statistique</h4>
<p>Pour un sommaire du contenu du base de données appelé sturgeon qui est en mémoire, taper la commande</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" title="1"><span class="kw">summary</span>(sturgeon)</a></code></pre></div>
<pre><code>##     fklngth         totlngth        drlngth          rdwght     
##  Min.   :24.96   Min.   :28.15   Min.   :14.33   Min.   : 4.73  
##  1st Qu.:41.00   1st Qu.:43.66   1st Qu.:25.00   1st Qu.:18.09  
##  Median :44.06   Median :47.32   Median :27.00   Median :23.10  
##  Mean   :44.15   Mean   :47.45   Mean   :27.29   Mean   :24.87  
##  3rd Qu.:48.00   3rd Qu.:51.97   3rd Qu.:29.72   3rd Qu.:30.27  
##  Max.   :66.85   Max.   :72.05   Max.   :41.93   Max.   :93.72  
##                  NA&#39;s   :85      NA&#39;s   :13      NA&#39;s   :4      
##       age            girth           sex              location        
##  Min.   : 7.00   Min.   :11.50   Length:186         Length:186        
##  1st Qu.:17.00   1st Qu.:40.00   Class :character   Class :character  
##  Median :20.00   Median :44.00   Mode  :character   Mode  :character  
##  Mean   :20.24   Mean   :44.33                                        
##  3rd Qu.:23.50   3rd Qu.:48.80                                        
##  Max.   :55.00   Max.   :73.70                                        
##  NA&#39;s   :11      NA&#39;s   :85                                           
##       year     
##  Min.   :1978  
##  1st Qu.:1979  
##  Median :1979  
##  Mean   :1979  
##  3rd Qu.:1980  
##  Max.   :1980  
## </code></pre>
<p>Pour chaque variable, R donne le minimum, le maximum, la médiane qui est la valeur au milieu de la liste des observations ordonnées (appelée le 50 ième percentile), ici, la 93 ième valeur des 186 observations, les valeurs au premier (25%) et troisième quartile (75%), et si il y a des valeurs manquantes dans la colonne.
Notez que plusieurs des variables ont des observations manquantes (NA).
Donc, seules les variables fklngth (longueur à la fourche), sex, location et year ont 186 observations.</p>

<div class="rmdwarning">
<strong>Attention aux valeurs manquantes</strong>
Plusieurs fonctions de R y réagissent mal et on doit souvent faire les analyses sur des sous- ensembles sans valeur manquante, par des commandes ou des options dans les commandes.
On y reviendra, mais prenez l’habitude de noter mentalement si il y a des données manquantes et de vous en rappeler en faisant l’analyse.
</div>

</div>
<div id="histogramme-densité-de-probabilité-empirique-boxplot-et-examen-visuel-de-la-normalité" class="section level4">
<h4><span class="header-section-number">1.5.2.2</span> Histogramme, densité de probabilité empirique, boxplot et examen visuel de la normalité</h4>
<p>Examinons maintenant de plus près la distribution de fklngth.
La commande <code>hist()</code> permet de tracer un histogramme de la variable fklngth dans le base de données sturgeon.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" title="1"><span class="kw">hist</span>(sturgeon<span class="op">$</span>fklngth)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/hist-stur-1.svg" width="672" /></p>
<p>Les données semblent suivre approximativement une distribution normale.</p>

<div class="rmdnote">
Cette syntaxe peut paraître un peu lourde puisqu’on doit ajouter le préfixe <code>sturgeon$</code> devant chaque nom de variable.
On pourrait se faciliter la tâche en utilisant la commande <code>attach()</code> <strong>mais cela est fortement déconseillé</strong> et jamais utilisé dans ce document.
</div>

<p>Cet histogramme est la représentation classique.
Mais les histogrammes ne sont pas parfaits.
Leur forme dépend en partie du nombre de catégories utilisées, surtout pour les petits échantillons.
On peut faire mieux, particulièrement si on est intéressé à comparer visuellement la distribution des observations à une distribution normale.
Mais il faut programmer un peu (ou savoir copier-coller…)</p>

<div class="rmdcode">
Copiez-collez le code suivant dans une nouvelle fenêtre script ( File-&gt;New script, ou Ctrl-n dans Windows), puis exécutez le.
</div>

<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" title="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb221-2" title="2"><span class="co">#  use &quot;sturgeon&quot; dataframe to make plot called mygraph</span></a>
<a class="sourceLine" id="cb221-3" title="3"><span class="co">#  and define x axis as representing fklngth</span></a>
<a class="sourceLine" id="cb221-4" title="4">mygraph &lt;-<span class="st"> </span><span class="kw">ggplot</span>(sturgeon, <span class="kw">aes</span>(<span class="dt">x =</span> fklngth))</a>
<a class="sourceLine" id="cb221-5" title="5"><span class="co">#  add data to the mygraph ggplot</span></a>
<a class="sourceLine" id="cb221-6" title="6">mygraph &lt;-<span class="st"> </span>mygraph <span class="op">+</span></a>
<a class="sourceLine" id="cb221-7" title="7"><span class="co">#  add data density smooth</span></a>
<a class="sourceLine" id="cb221-8" title="8"><span class="st">    </span><span class="kw">geom_density</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb221-9" title="9"><span class="co">#  add rug (bars at the bottom of the plot)</span></a>
<a class="sourceLine" id="cb221-10" title="10"><span class="st">    </span><span class="kw">geom_rug</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb221-11" title="11"><span class="co">#  add black semitransparent histogram</span></a>
<a class="sourceLine" id="cb221-12" title="12"><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..), <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>,   <span class="dt">alpha =</span> <span class="fl">0.3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb221-13" title="13"><span class="co">#  add normal curve in red, with mean and sd from fklength</span></a>
<a class="sourceLine" id="cb221-14" title="14"><span class="st">    </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> dnorm,</a>
<a class="sourceLine" id="cb221-15" title="15">                   <span class="dt">args =</span> <span class="kw">list</span>(</a>
<a class="sourceLine" id="cb221-16" title="16">                     <span class="dt">mean =</span> <span class="kw">mean</span>(sturgeon<span class="op">$</span>fklngth),</a>
<a class="sourceLine" id="cb221-17" title="17">                     <span class="dt">sd =</span> <span class="kw">sd</span>(sturgeon<span class="op">$</span>fklngth) ),</a>
<a class="sourceLine" id="cb221-18" title="18">                   <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb221-19" title="19"><span class="co"># display graph</span></a>
<a class="sourceLine" id="cb221-20" title="20">    mygraph</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/stur-g1-1.svg" width="672" /></p>
<p>Chaque observation est représentée par une barre sous l’axe des x (rug).
En rouge est la distribution normale de données avec la même moyenne et écart-type que les observations.
Et l’autre ligne est la densité de probabilité empirique, « lissée » à partir des observations.
Si vous êtes plus aventureux, vous pouvez examiner la distribution des observations de fklngth par sous-groupes (par exemple sex et year) avec :</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" title="1">mygraph <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(year <span class="op">~</span><span class="st"> </span>sex)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/aventure-1.svg" width="672" /></p>
<p>Chaque panneau illustre la distribution pour un sexe cette année-là, et la courbe en rouge récurrente représente la distribution normale pour l’ensemble des données.
Cette courbe peut servir à mieux évaluer visuellement les différences entre les panneaux.
Une autre façon d’évaluer la normalité de données visuellement est de faire un QQ plot avec la paire de commandes <code>qqnorm()</code> et <code>qqline()</code>.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" title="1"><span class="kw">qqnorm</span>(sturgeon<span class="op">$</span>fklngth)</a>
<a class="sourceLine" id="cb223-2" title="2"><span class="kw">qqline</span>(sturgeon<span class="op">$</span>fklngth)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/stur-norm-1.svg" width="672" /></p>
<p>Des données parfaitement normales suivraient la ligne droite diagonale.
Ici, il y a des déviations dans les queues de la distribution, et un peu à droite du centre.
Comparez cette représentation à celle des deux graphiques précédents.
Vous conviendrez sans doute avec moi qu’il est plus facile de visualiser comment la distribution dévie de la normalité sur les histogrammes et les graphiques de la densité empirique de probabilité que sur les QQ plots.
Ceci dit, les QQ plots sont souvent utilisés et vous devriez être capable de les interpréter.
De plus, on peut facilement éprouver statistiquement l’hypothèse que les données sont distribuées normalement avec R par la commande <code>shapiro.test()</code> qui calcule une statistique (W) qui est une mesure de la tendance des points d’un QQ plot à former une ligne parfaite.
Si oui, alors W=1.
Si W s’éloigne de 1 (vers 0), alors les données s’éloignent de la normalité.
Ici,</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" title="1"><span class="kw">shapiro.test</span>(sturgeon<span class="op">$</span>fklngth)</a></code></pre></div>
<pre><code>## 
## 	Shapiro-Wilk normality test
## 
## data:  sturgeon$fklngth
## W = 0.97225, p-value = 0.0009285</code></pre>
<p>W n’est pas très loin de 1, mais suffisamment pour que la différence soit significative.
L’examen visuel des grands échantillons est souvent compliqué par le fait que plusieurs points se superposent et qu’il devient plus difficile de bien visualiser la tendance centrale.
Les boxplots avec “moustaches” (box and whiskers plots) offrent une alternative intéressante.
La commande <code>boxplot()</code> peut produire un boxplot de fklngth pour chaque niveau de sex, et ajoute les coches.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1"><span class="kw">boxplot</span>(fklngth <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> sturgeon, <span class="dt">notch =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/boxplot-stur-1.svg" width="672" /></p>
<p>La ligne un peu plus épaisse dans la boîte de la Fig.7 indique la médiane.
La coche est proportionnelle à l’incertitude quant à la position de la médiane.
On peut visuellement interpréter approximativement les différences entre médianes en examinant si il y a chevauchement entre les coches (ici, il n’y a pas chevauchement, et on conclurait provisoirement que la médiane de fklngth pour les femelles est supérieure à celle des mâles).
Les boîtes s’étendent du premier au troisième quartile (du 25ième au 75ième percentile si vous préférez), Les barres (moustaches ou whiskers) au-dessus et en dessous des boîtes s’étendent soit de la valeur minimum à la valeur maximum, ou, si il y a des valeurs extrêmes, de la plus petite à la plus grande valeur à l’intérieur de 1.5x la largeur de l’étendue interquartile .
Enfin, les observations qui excèdent les limites des moustaches (donc à plus de 1.5x l’étendue interquartile de chaque côté de la médiane) sont indiquées par des symboles.Ce sont des valeurs qui pourraient être considérées comme extrêmes et possiblement aberrantes.</p>
</div>
<div id="diagrammes-de-dispersion-bivariés" class="section level4">
<h4><span class="header-section-number">1.5.2.3</span> Diagrammes de dispersion bivariés</h4>
<p>En plus des graphiques pour chacune des variables séparément, il est très souvent intéressant de jeter un coup d’oeil aux diagrammes de dispersion .
La commande <code>plot(y~x)</code> permet de faire le graphique de y sur l’axe vertical (l’ordonnée) en fonction de x sur l’axe horizontal (l’abscisse).</p>

<div class="rmdcode">
Faites un graphique de fklngth en fonction de age avec la commande plot.
</div>

<p>Vous devriez obtenir:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb227-1" title="1"><span class="kw">plot</span>(fklngth <span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> sturgeon)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/stur-biv-plot-1.svg" width="672" /></p>
<p>R a une fonction qui permet la création des graphiques de dispersion de toutes les paires de variables (<code>pairs()</code>).
Une des option de ¬ est l’ajout d’une trace lowess qui indique la tendance de la relation entre les variables.
Pour obtenir la matrice de ces graphiques avec la trace lowess pour toutes les variable dans sturgeon, entrer la commande <code>pairs(sturgeon[,1:6], panel=panel.smooth)</code> et vous devriez obtenir</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1"><span class="kw">pairs</span>(sturgeon[,<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>], <span class="dt">panel =</span> panel.smooth)</a></code></pre></div>
<p><img src="Labo_BIO4558_files/figure-html/pairs-stur-1.svg" width="672" /></p>
</div>
</div>
<div id="créer-des-sous-ensembles-de-cas" class="section level3">
<h3><span class="header-section-number">1.5.3</span> Créer des sous-ensembles de cas</h3>
<p>Il arrive fréquemment qu’une analyse se concentre sur un sous-ensemble des observations contenues dans un fichier de données.
Les cas sont d’habitude sélectionnés selon un critère en particulier.
Pour utiliser un sous-ensemble de vos données en créant un graphique ou en performant une analyse, on peut utiliser la commande <code>subset()</code>.
Par exemple, pour créer un sous ensemble des données du tableau sturgeon qui ne contient que les femelles capturées en 1978, on peut écrire :</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb229-1" title="1">sturgeon.female<span class="fl">.1978</span> &lt;-<span class="st"> </span><span class="kw">subset</span>(sturgeon, sex <span class="op">==</span><span class="st"> &quot;FEMALE&quot;</span> <span class="op">&amp;</span><span class="st"> </span>year <span class="op">==</span><span class="st"> &quot;1978&quot;</span>)</a>
<a class="sourceLine" id="cb229-2" title="2">sturgeon.female<span class="fl">.1978</span></a></code></pre></div>
<pre><code>##      fklngth totlngth  drlngth rdwght age girth    sex   location year
## 2   50.19685 54.13386 31.49606     NA  24  53.5 FEMALE    THE_PAS 1978
## 4   50.19685 53.14961 32.28346     NA  23  52.5 FEMALE    THE_PAS 1978
## 6   49.60630 53.93701 31.10236  35.86  23  54.2 FEMALE    THE_PAS 1978
## 7   47.71654 51.37795 33.97638  33.88  20  48.0 FEMALE    THE_PAS 1978
## 15  48.89764 53.93701 29.92126  35.86  23  52.5 FEMALE    THE_PAS 1978
## 105 46.85039       NA 28.34646  23.90  24    NA FEMALE CUMBERLAND 1978
## 106 40.74803       NA 24.80315  17.50  18    NA FEMALE CUMBERLAND 1978
## 107 40.35433       NA 25.59055  20.90  21    NA FEMALE CUMBERLAND 1978
## 109 43.30709       NA 27.95276  24.10  19    NA FEMALE CUMBERLAND 1978
## 113 53.54331       NA 33.85827  48.90  20    NA FEMALE CUMBERLAND 1978
## 114 51.77165       NA 31.49606  35.30  26    NA FEMALE CUMBERLAND 1978
## 116 45.27559       NA 26.57480  23.70  24    NA FEMALE CUMBERLAND 1978
## 118 53.14961       NA 32.67717  45.30  25    NA FEMALE CUMBERLAND 1978
## 119 50.19685       NA 32.08661  33.90  26    NA FEMALE CUMBERLAND 1978
## 123 49.01575       NA 29.13386  37.50  22    NA FEMALE CUMBERLAND 1978</code></pre>

<div class="rmdcaution">
Dans ces comparaisons, il faut toujours utiliser <code>==</code> pour égal à.
Dans ce contexte, si vous utilisez <code>=</code> seulement, vous n’obtiendrez pas ce que vous désirez.
Dans le tableau qui suit se trouve une liste de commandes communes que vous allez probablement utiliser pour créer des expressions en R.
</div>

<table>
<thead>
<tr class="header">
<th>Operateur</th>
<th>Explication</th>
<th>Operateur</th>
<th>Explication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>==</td>
<td>Égal à</td>
<td>!=</td>
<td>Pas égal à</td>
</tr>
<tr class="even">
<td>&gt;</td>
<td>Plus que</td>
<td>&lt;</td>
<td>Moins que</td>
</tr>
<tr class="odd">
<td>&gt;=</td>
<td>Plus que ou égal à</td>
<td>&lt;=</td>
<td>Moins que ou égal à</td>
</tr>
<tr class="even">
<td>&amp;</td>
<td>Et vectorisé</td>
<td>|</td>
<td>Ou vectorisé</td>
</tr>
<tr class="odd">
<td>&amp;&amp;</td>
<td>Et contrôle</td>
<td>||</td>
<td>Ou contrôle</td>
</tr>
<tr class="even">
<td>!</td>
<td>Pas</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

<div class="rmdcode">
En utilisant les commandes <code>subset()</code> et <code>hist()</code>, essayez de faire un histogramme pour le sous-ensemble de cas correspondant aux femelles capturées en 1979 et 1980 (donc <code>sex == "FEMALE" &amp; (year == "1979" | year == "1980")</code>)
</div>

</div>
<div id="transformations-de-données" class="section level3">
<h3><span class="header-section-number">1.5.4</span> Transformations de données</h3>
<p>Il est très fréquemment nécessaire d’effectuer des transformations mathématiques sur les données brutes pour mieux satisfaire aux conditions d’application de tests statistiques.
R étant aussi un langage de programmation complet, il peut donc effectuer les transformations désirées.
Les fonctions les plus fréquemment utilisées sont:</p>
<ul>
<li><code>log()</code></li>
<li><code>sqrt()</code></li>
<li><code>ifelse()</code></li>
</ul>
<p>On peut employer ces fonctions directement dans les lignes de commandes, ou encore créer de nouvelles variables orphelines ou faisant partie d’un data.frame.
Par exemple, pour faire un graphique du logarithme décimal de fklngth en fonction de l’âge, on peut écrire</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" title="1"><span class="kw">plot</span>(<span class="kw">log</span>(fklngth)<span class="op">~</span>age, <span class="dt">data =</span> sturgeon)</a></code></pre></div>
<p>Pour créer une variable orpheline (i.e. non incluse dans le data.frame) appelée logfklngth et contenant le logarithme décimal de fklngth, on peut écrire</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" title="1">logfklngth &lt;-<span class="st"> </span><span class="kw">log10</span>(sturgeon<span class="op">$</span>fklngth)</a></code></pre></div>
<p>Si on veut ajouter cette variable transformée à un tableau de données (data.frame), alors, on doit préfixer le nom de la variable par le nom du base de données et du symbole <code>$</code>, par exemple, pour ajouter une variable nommée <code>lfkl</code> contenant le log10 de fklngth au tableau sturgeon, on peut écrire:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" title="1">sturgeon<span class="op">$</span>logfkl &lt;-<span class="st"> </span><span class="kw">log10</span>(sturgeonfklngth)</a></code></pre></div>
<p>N’oubliez pas de sauvegarder ce tableau modifié si vous voulez avoir accès à cette nouvelle variable dans le futur.
Pour les transformations conditionnelles, on peut utiliser la fonction <code>ifelse()</code>.
Par exemple, pour créer une nouvelle variable appelée dummy qui sera égale à 1 pour les mâles et 0 pour les femelles, on peut écrire:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" title="1">sturgeon<span class="op">$</span>dummy &lt;-<span class="st"> </span><span class="kw">ifelse</span>(sturgeon<span class="op">$</span>sex <span class="op">==</span><span class="st"> &quot;MALE&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</a></code></pre></div>
</div>
<div id="exercice-sur-r" class="section level3">
<h3><span class="header-section-number">1.5.5</span> Exercice sur R</h3>

<div class="rmdcode">
Vous trouverez dans le fichier salmonella, des valeurs numériques du ratio pour deux milieux (IN VITRO et IN VIVO) pour trois souches.
Examinez les données pour ratio et faites des graphiques pour évaluer la normalité de la distribution des ratios pour la souche SAUVAGE.
</div>

<p><img src="Labo_BIO4558_files/figure-html/intror-exer-1.svg" width="672" /></p>

<!-- # (PART) Analyse de puissance {-} -->
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>On peut ignorer pour le moment la présence du <code>[1]</code> en début de ligne.<a href="introduction-à-r.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>Et permet de constater que pour R, un nombre est un vecteur à un seul élément.<a href="introduction-à-r.html#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p><code>c</code> est l’abbréviation de <em>combine</em>, son nom est très court car on l’utilise très souvent<a href="introduction-à-r.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>La seule limite pour la taille d’un objet étant la mémoire vive (RAM) de la machine sur laquelle tourne la session R.<a href="introduction-à-r.html#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>Les différents types de variables seront décrits plus en détail dans le chapitre <a href="#vectorfactor"><strong>??</strong></a> sur les recodages.<a href="introduction-à-r.html#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>Les différentes manières de spécifier des couleurs sont indiquées dans l’encadré de la section <a href="#scalecolor"><strong>??</strong></a>.<a href="introduction-à-r.html#fnref6" class="footnote-back">↩</a></p></li>
</ol>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="préface.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analyse-de-puissance-avec-r-et-gpower.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/BIO4558_uOttawa_lab_manual/01-introR.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labo_BIO4558.pdf", "Labo_BIO4558.epub", "Labo_BIO4558.mobi"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
