<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6.2 Plan factoriel à deux facteurs de classification et réplication | BIO4558 Biostatistiques appliquées avec R</title>
  <meta name="description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="6.2 Plan factoriel à deux facteurs de classification et réplication | BIO4558 Biostatistiques appliquées avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/missing.png" />
  <meta property="og:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="github-repo" content="JulienGAMartin/BIO4558_uOttawa_lab_manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6.2 Plan factoriel à deux facteurs de classification et réplication | BIO4558 Biostatistiques appliquées avec R" />
  
  <meta name="twitter:description" content="Manuel de laboratoire pour le cours BIO4558" />
  <meta name="twitter:image" content="images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="set-anomul.html"/>
<link rel="next" href="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4558 Manuel de laboratoire</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="préface.html"><a href="préface.html"><i class="fa fa-check"></i>Préface</a><ul>
<li class="chapter" data-level="" data-path="quelques-points-importants-à-retenir.html"><a href="quelques-points-importants-à-retenir.html"><i class="fa fa-check"></i>Quelques points importants à retenir</a></li>
<li class="chapter" data-level="" data-path="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><a href="quest-ce-que-r-et-pourquoi-lutiliser-dans-ce-cours.html"><i class="fa fa-check"></i>Qu’est-ce que R et pourquoi l’utiliser dans ce cours?</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html"><i class="fa fa-check"></i>Installation des logiciels nécessaires</a><ul>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#rstudio"><i class="fa fa-check"></i>Rstudio</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#paquets-pour-r"><i class="fa fa-check"></i>Paquets pour R</a></li>
<li class="chapter" data-level="" data-path="installation-des-logiciels-nécessaires.html"><a href="installation-des-logiciels-nécessaires.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="instructions-générales-pour-les-laboratoires.html"><a href="instructions-générales-pour-les-laboratoires.html"><i class="fa fa-check"></i>Instructions générales pour les laboratoires</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html"><i class="fa fa-check"></i>Notes sur le manuel</a><ul>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-sur-le-manuel.html"><a href="notes-sur-le-manuel.html#licence"><i class="fa fa-check"></i>Licence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-à-r.html"><a href="introduction-à-r.html"><i class="fa fa-check"></i><b>1</b> Introduction à R</a><ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="1.2" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html"><i class="fa fa-check"></i><b>1.2</b> Premier pas avec R</a><ul>
<li class="chapter" data-level="1.2.1" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#la-console"><i class="fa fa-check"></i><b>1.2.1</b> La console</a></li>
<li class="chapter" data-level="1.2.2" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#objets"><i class="fa fa-check"></i><b>1.2.2</b> Objets</a></li>
<li class="chapter" data-level="1.2.3" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#vecteurs"><i class="fa fa-check"></i><b>1.2.3</b> Vecteurs</a></li>
<li class="chapter" data-level="1.2.4" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#fonctions"><i class="fa fa-check"></i><b>1.2.4</b> Fonctions</a></li>
<li class="chapter" data-level="1.2.5" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#regrouper-ses-commandes-dans-des-scripts"><i class="fa fa-check"></i><b>1.2.5</b> Regrouper ses commandes dans des scripts</a></li>
<li class="chapter" data-level="1.2.6" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#packages"><i class="fa fa-check"></i><b>1.2.6</b> Installer et charger des extensions (<em>packages</em>)</a></li>
<li class="chapter" data-level="1.2.7" data-path="premier-pas-avec-r.html"><a href="premier-pas-avec-r.html#ex-introR"><i class="fa fa-check"></i><b>1.2.7</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html"><i class="fa fa-check"></i><b>1.3</b> Premier travail avec des données</a><ul>
<li class="chapter" data-level="1.3.1" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#jeu-de-données-dexemple"><i class="fa fa-check"></i><b>1.3.1</b> Jeu de données d’exemple</a></li>
<li class="chapter" data-level="1.3.2" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#tableau-de-données-data-frame"><i class="fa fa-check"></i><b>1.3.2</b> Tableau de données (<em>data frame</em>)</a></li>
<li class="chapter" data-level="1.3.3" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#analyse-univariée"><i class="fa fa-check"></i><b>1.3.3</b> Analyse univariée</a></li>
<li class="chapter" data-level="1.3.4" data-path="premier-travail-avec-des-données.html"><a href="premier-travail-avec-des-données.html#ex-introR-univ"><i class="fa fa-check"></i><b>1.3.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html"><i class="fa fa-check"></i><b>1.4</b> Analyse de 2 variables</a><ul>
<li class="chapter" data-level="1.4.1" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-de-deux-variables-qualitatives"><i class="fa fa-check"></i><b>1.4.1</b> Croisement de deux variables qualitatives</a></li>
<li class="chapter" data-level="1.4.2" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-dune-variable-quantitative-et-dune-variable-qualitative"><i class="fa fa-check"></i><b>1.4.2</b> Croisement d’une variable quantitative et d’une variable qualitative</a></li>
<li class="chapter" data-level="1.4.3" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#croisement-de-deux-variables-quantitatives"><i class="fa fa-check"></i><b>1.4.3</b> Croisement de deux variables quantitatives</a></li>
<li class="chapter" data-level="1.4.4" data-path="analyse-de-2-variables.html"><a href="analyse-de-2-variables.html#ex-introR-biv"><i class="fa fa-check"></i><b>1.4.4</b> Exercices</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="gérer-les-données.html"><a href="gérer-les-données.html"><i class="fa fa-check"></i><b>1.5</b> Gérer les données</a><ul>
<li class="chapter" data-level="1.5.1" data-path="gérer-les-données.html"><a href="gérer-les-données.html#importer-et-exporter-des-données"><i class="fa fa-check"></i><b>1.5.1</b> Importer et exporter des données</a></li>
<li class="chapter" data-level="1.5.2" data-path="gérer-les-données.html"><a href="gérer-les-données.html#examen-préliminaire-des-données"><i class="fa fa-check"></i><b>1.5.2</b> Examen préliminaire des données</a></li>
<li class="chapter" data-level="1.5.3" data-path="gérer-les-données.html"><a href="gérer-les-données.html#créer-des-sous-ensembles-de-cas"><i class="fa fa-check"></i><b>1.5.3</b> Créer des sous-ensembles de cas</a></li>
<li class="chapter" data-level="1.5.4" data-path="gérer-les-données.html"><a href="gérer-les-données.html#transformations-de-données"><i class="fa fa-check"></i><b>1.5.4</b> Transformations de données</a></li>
<li class="chapter" data-level="1.5.5" data-path="gérer-les-données.html"><a href="gérer-les-données.html#exercice-sur-r"><i class="fa fa-check"></i><b>1.5.5</b> Exercice sur R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analyse-de-puissance-avec-r-et-gpower.html"><a href="analyse-de-puissance-avec-r-et-gpower.html"><i class="fa fa-check"></i><b>2</b> Analyse de puissance avec R et G*Power</a><ul>
<li class="chapter" data-level="2.1" data-path="la-théorie.html"><a href="la-théorie.html"><i class="fa fa-check"></i><b>2.1</b> La théorie</a><ul>
<li class="chapter" data-level="2.1.1" data-path="la-théorie.html"><a href="la-théorie.html#quest-ce-que-la-puissance"><i class="fa fa-check"></i><b>2.1.1</b> Qu’est-ce que la puissance?</a></li>
<li class="chapter" data-level="2.1.2" data-path="la-théorie.html"><a href="la-théorie.html#pourquoi-faire-une-analyse-de-puissance"><i class="fa fa-check"></i><b>2.1.2</b> Pourquoi faire une analyse de puissance?</a></li>
<li class="chapter" data-level="2.1.3" data-path="la-théorie.html"><a href="la-théorie.html#facteurs-qui-affectent-la-puissance"><i class="fa fa-check"></i><b>2.1.3</b> Facteurs qui affectent la puissance</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="quest-ce-que-gpower.html"><a href="quest-ce-que-gpower.html"><i class="fa fa-check"></i><b>2.2</b> Qu’est ce que G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html"><i class="fa fa-check"></i><b>2.3</b> Comment utiliser G*Power</a><ul>
<li class="chapter" data-level="2.3.1" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#principe-général"><i class="fa fa-check"></i><b>2.3.1</b> Principe général</a></li>
<li class="chapter" data-level="2.3.2" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#types-danalyses-de-puissance-disponibles"><i class="fa fa-check"></i><b>2.3.2</b> Types d’analyses de puissance disponibles</a></li>
<li class="chapter" data-level="2.3.3" data-path="comment-utiliser-gpower.html"><a href="comment-utiliser-gpower.html#comment-calculer-la-taille-de-leffet-gpower-permet-de-faire-une-analyse-de-puissance-pour-de-nombreux-tests-statistiques"><i class="fa fa-check"></i><b>2.3.3</b> Comment calculer la taille de l’effet G*Power permet de faire une analyse de puissance pour de nombreux tests statistiques</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><i class="fa fa-check"></i><b>2.4</b> Puissance pour un test de t comparant deux moyennes</a><ul>
<li class="chapter" data-level="2.4.1" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-post-hoc"><i class="fa fa-check"></i><b>2.4.1</b> Analyse post-hoc</a></li>
<li class="chapter" data-level="2.4.2" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-à-priori"><i class="fa fa-check"></i><b>2.4.2</b> Analyse à priori</a></li>
<li class="chapter" data-level="2.4.3" data-path="puissance-pour-un-test-de-t-comparant-deux-moyennes.html"><a href="puissance-pour-un-test-de-t-comparant-deux-moyennes.html#analyse-de-sensitivité---calculer-la-taille-deffet-détectable"><i class="fa fa-check"></i><b>2.4.3</b> Analyse de sensitivité - Calculer la taille d’effet détectable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="points-à-retenir.html"><a href="points-à-retenir.html"><i class="fa fa-check"></i><b>2.5</b> Points à retenir</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="corrélation-et-régression-linéaire-simple.html"><a href="corrélation-et-régression-linéaire-simple.html"><i class="fa fa-check"></i><b>3</b> Corrélation et régression linéaire simple</a><ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> Extensions R et données requises pour le labo</a></li>
<li class="chapter" data-level="3.2" data-path="diagrammes-de-dispersion.html"><a href="diagrammes-de-dispersion.html"><i class="fa fa-check"></i><b>3.2</b> Diagrammes de dispersion</a></li>
<li class="chapter" data-level="3.3" data-path="transformations-et-le-coefficient-de-corrélation.html"><a href="transformations-et-le-coefficient-de-corrélation.html"><i class="fa fa-check"></i><b>3.3</b> Transformations et le coefficient de corrélation</a></li>
<li class="chapter" data-level="3.4" data-path="matrices-de-corrélations-et-correction-de-bonferroni.html"><a href="matrices-de-corrélations-et-correction-de-bonferroni.html"><i class="fa fa-check"></i><b>3.4</b> Matrices de corrélations et correction de Bonferroni</a></li>
<li class="chapter" data-level="3.5" data-path="corrélations-non-paramétriques-r-de-spearman-et-tau-de-kendall.html"><a href="corrélations-non-paramétriques-r-de-spearman-et-tau-de-kendall.html"><i class="fa fa-check"></i><b>3.5</b> Corrélations non paramétriques: <em>r</em> de Spearman et <span class="math inline">\(\tau\)</span> de Kendall</a></li>
<li class="chapter" data-level="3.6" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html"><i class="fa fa-check"></i><b>3.6</b> Régression linéaire simple</a><ul>
<li class="chapter" data-level="3.6.1" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html#vérifier-les-conditions-dapplication-de-la-régression"><i class="fa fa-check"></i><b>3.6.1</b> Vérifier les conditions d’application de la régression</a></li>
<li class="chapter" data-level="3.6.2" data-path="régression-linéaire-simple.html"><a href="régression-linéaire-simple.html#tests-formels-des-conditions-dapplication-pour-la-régression"><i class="fa fa-check"></i><b>3.6.2</b> Tests formels des conditions d’application pour la régression</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="transformation-des-données-en-régression.html"><a href="transformation-des-données-en-régression.html"><i class="fa fa-check"></i><b>3.7</b> Transformation des données en régression</a></li>
<li class="chapter" data-level="3.8" data-path="traitement-des-valeurs-extrèmes.html"><a href="traitement-des-valeurs-extrèmes.html"><i class="fa fa-check"></i><b>3.8</b> Traitement des valeurs extrèmes</a></li>
<li class="chapter" data-level="3.9" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><i class="fa fa-check"></i><b>3.9</b> Quantifier la taille d’effet et analyse de puissance en régression</a><ul>
<li class="chapter" data-level="3.9.1" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html#puissance-de-détecter-une-pente-donnée"><i class="fa fa-check"></i><b>3.9.1</b> Puissance de détecter une pente donnée</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html"><a href="quantifier-la-taille-deffet-et-analyse-de-puissance-en-régression.html#effectif-requis-pour-atteindre-une-puissance-désirée-test-a-priori"><i class="fa fa-check"></i><b>3.9.2</b> Effectif requis pour atteindre une puissance désirée (test A-priori)</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrap-en-régression-simple-avec-r.html"><a href="bootstrap-en-régression-simple-avec-r.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrap en régression simple avec R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="comparaison-de-deux-échantillons.html"><a href="comparaison-de-deux-échantillons.html"><i class="fa fa-check"></i><b>4</b> Comparaison de deux échantillons</a><ul>
<li class="chapter" data-level="4.1" data-path="set-t.html"><a href="set-t.html"><i class="fa fa-check"></i><b>4.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="4.2" data-path="examen-visuel-des-données.html"><a href="examen-visuel-des-données.html"><i class="fa fa-check"></i><b>4.2</b> Examen visuel des données</a></li>
<li class="chapter" data-level="4.3" data-path="comparer-les-moyennes-de-deux-échantillons-indépendants.html"><a href="comparer-les-moyennes-de-deux-échantillons-indépendants.html"><i class="fa fa-check"></i><b>4.3</b> Comparer les moyennes de deux échantillons indépendants</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap et tests de permutation pour comparer deux moyennes</a><ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html"><a href="bootstrap-et-tests-de-permutation-pour-comparer-deux-moyennes.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparer-les-moyennes-de-deux-échantillons-appariés.html"><a href="comparer-les-moyennes-de-deux-échantillons-appariés.html"><i class="fa fa-check"></i><b>4.5</b> Comparer les moyennes de deux échantillons appariés</a></li>
<li class="chapter" data-level="4.6" data-path="références.html"><a href="références.html"><i class="fa fa-check"></i><b>4.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="anova-à-un-critère-de-classification.html"><a href="anova-à-un-critère-de-classification.html"><i class="fa fa-check"></i><b>5</b> ANOVA à un critère de classification</a><ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="5.2" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><i class="fa fa-check"></i><b>5.2</b> ANOVA à un critère de classification et comparaisons multiples</a><ul>
<li class="chapter" data-level="5.2.1" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#vérifier-les-conditions-dapplication-de-lanova-paramétrique"><i class="fa fa-check"></i><b>5.2.2</b> Vérifier les conditions d’application de l’ANOVA paramétrique</a></li>
<li class="chapter" data-level="5.2.3" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#faire-lanova"><i class="fa fa-check"></i><b>5.2.3</b> Faire l’ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="anova-à-un-critère-de-classification-et-comparaisons-multiples.html"><a href="anova-à-un-critère-de-classification-et-comparaisons-multiples.html#les-comparaisons-multiples"><i class="fa fa-check"></i><b>5.2.4</b> Les comparaisons multiples</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="transformations-de-données-et-anova-non-paramétrique.html"><a href="transformations-de-données-et-anova-non-paramétrique.html"><i class="fa fa-check"></i><b>5.3</b> Transformations de données et ANOVA non-paramétrique</a></li>
<li class="chapter" data-level="5.4" data-path="examen-des-valeurs-extrêmes.html"><a href="examen-des-valeurs-extrêmes.html"><i class="fa fa-check"></i><b>5.4</b> Examen des valeurs extrêmes</a></li>
<li class="chapter" data-level="5.5" data-path="test-de-permutation.html"><a href="test-de-permutation.html"><i class="fa fa-check"></i><b>5.5</b> Test de permutation</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova-à-critères-multiples-plans-factoriels-et-hiérarchiques.html"><a href="anova-à-critères-multiples-plans-factoriels-et-hiérarchiques.html"><i class="fa fa-check"></i><b>6</b> ANOVA à critères multiples : plans factoriels et hiérarchiques</a><ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="6.2" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><i class="fa fa-check"></i><b>6.2</b> Plan factoriel à deux facteurs de classification et réplication</a><ul>
<li class="chapter" data-level="6.2.1" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html#anova-à-effets-fixes"><i class="fa fa-check"></i><b>6.2.1</b> ANOVA à effets fixes</a></li>
<li class="chapter" data-level="6.2.2" data-path="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-et-réplication.html#anova-à-effets-mixtes"><i class="fa fa-check"></i><b>6.2.2</b> ANOVA à effets mixtes</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html"><a href="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html"><i class="fa fa-check"></i><b>6.3</b> Plan factoriel à deux facteurs de classification sans réplication</a></li>
<li class="chapter" data-level="6.4" data-path="plans-hiérarchiques.html"><a href="plans-hiérarchiques.html"><i class="fa fa-check"></i><b>6.4</b> Plans hiérarchiques</a></li>
<li class="chapter" data-level="6.5" data-path="anova-non-paramétrique-avec-deux-facteurs-de-classification.html"><a href="anova-non-paramétrique-avec-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.5</b> ANOVA non paramétrique avec deux facteurs de classification</a></li>
<li class="chapter" data-level="6.6" data-path="comparaisons-multiples.html"><a href="comparaisons-multiples.html"><i class="fa fa-check"></i><b>6.6</b> Comparaisons multiples</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-pour-lanova-à-deux-facteurs-de-classification.html"><a href="bootstrap-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap pour l’ANOVA à deux facteurs de classification</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="régression-multiple.html"><a href="régression-multiple.html"><i class="fa fa-check"></i><b>7</b> Régression multiple</a><ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="7.2" data-path="conseils-généraux.html"><a href="conseils-généraux.html"><i class="fa fa-check"></i><b>7.2</b> Conseils généraux</a></li>
<li class="chapter" data-level="7.3" data-path="premières-régressions-multiples.html"><a href="premières-régressions-multiples.html"><i class="fa fa-check"></i><b>7.3</b> Premières régressions multiples</a></li>
<li class="chapter" data-level="7.4" data-path="régression-multiple-pas-à-pas-stepwise.html"><a href="régression-multiple-pas-à-pas-stepwise.html"><i class="fa fa-check"></i><b>7.4</b> Régression multiple pas-à-pas (stepwise)</a></li>
<li class="chapter" data-level="7.5" data-path="détecter-la-multicolinéarité.html"><a href="détecter-la-multicolinéarité.html"><i class="fa fa-check"></i><b>7.5</b> Détecter la multicolinéarité</a></li>
<li class="chapter" data-level="7.6" data-path="régression-polynomiale.html"><a href="régression-polynomiale.html"><i class="fa fa-check"></i><b>7.6</b> Régression polynomiale</a></li>
<li class="chapter" data-level="7.7" data-path="vérifier-les-conditions-dapplication-de-modèles-de-régression-multiple.html"><a href="vérifier-les-conditions-dapplication-de-modèles-de-régression-multiple.html"><i class="fa fa-check"></i><b>7.7</b> Vérifier les conditions d’application de modèles de régression multiple</a></li>
<li class="chapter" data-level="7.8" data-path="visualiser-la-taille-deffet.html"><a href="visualiser-la-taille-deffet.html"><i class="fa fa-check"></i><b>7.8</b> Visualiser la taille d’effet</a></li>
<li class="chapter" data-level="7.9" data-path="tester-la-présence-dinteractions.html"><a href="tester-la-présence-dinteractions.html"><i class="fa fa-check"></i><b>7.9</b> Tester la présence d’interactions</a></li>
<li class="chapter" data-level="7.10" data-path="recherche-du-meilleur-modèle-fondée-sur-la-théorie-de-linformation.html"><a href="recherche-du-meilleur-modèle-fondée-sur-la-théorie-de-linformation.html"><i class="fa fa-check"></i><b>7.10</b> Recherche du meilleur modèle fondée sur la théorie de l’information</a></li>
<li class="chapter" data-level="7.11" data-path="bootstrap-et-régression-multiple.html"><a href="bootstrap-et-régression-multiple.html"><i class="fa fa-check"></i><b>7.11</b> Bootstrap et régression multiple</a></li>
<li class="chapter" data-level="7.12" data-path="perm-reg-mult.html"><a href="perm-reg-mult.html"><i class="fa fa-check"></i><b>7.12</b> Test de permutation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-et-modèle-linéaire-général.html"><a href="ancova-et-modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8</b> ANCOVA et modèle linéaire général</a><ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="8.2" data-path="modèle-linéaire-général.html"><a href="modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8.2</b> Modèle linéaire général</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html"><i class="fa fa-check"></i><b>8.4</b> Homogénéité des pentes</a><ul>
<li class="chapter" data-level="8.4.1" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html#cas-1---la-taille-en-fonction-de-lâge-exemple-avec-pente-commune"><i class="fa fa-check"></i><b>8.4.1</b> Cas 1 - La taille en fonction de l’âge (exemple avec pente commune)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogénéité-des-pentes.html"><a href="homogénéité-des-pentes.html#cas-2---taille-en-fonction-de-lâge-exemple-avec-des-pentes-différentes"><i class="fa fa-check"></i><b>8.4.2</b> Cas 2 - Taille en fonction de l’âge (exemple avec des pentes différentes)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="le-modèle-dancova.html"><a href="le-modèle-dancova.html"><i class="fa fa-check"></i><b>8.5</b> Le modèle d’ANCOVA</a></li>
<li class="chapter" data-level="8.6" data-path="comparer-lajustement-de-modèles.html"><a href="comparer-lajustement-de-modèles.html"><i class="fa fa-check"></i><b>8.6</b> Comparer l’ajustement de modèles</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analyse-de-données-de-fréquence-tableaux-de-contingence-modèles-log-linéaires-et-régression-de-poisson.html"><a href="analyse-de-données-de-fréquence-tableaux-de-contingence-modèles-log-linéaires-et-régression-de-poisson.html"><i class="fa fa-check"></i><b>9</b> Analyse de données de fréquence: Tableaux de contingence, modèles log-linéaires et régression de Poisson</a><ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> Paquets et données requises pour le labo</a></li>
<li class="chapter" data-level="9.2" data-path="organisation-des-données-3-formats.html"><a href="organisation-des-données-3-formats.html"><i class="fa fa-check"></i><b>9.2</b> Organisation des données: 3 formats</a></li>
<li class="chapter" data-level="9.3" data-path="visualiser-graphiquement-les-tableaux-de-contingence-et-test-dindépendance.html"><a href="visualiser-graphiquement-les-tableaux-de-contingence-et-test-dindépendance.html"><i class="fa fa-check"></i><b>9.3</b> Visualiser graphiquement les tableaux de contingence et test d’indépendance</a></li>
<li class="chapter" data-level="9.4" data-path="régression-de-poisson-une-alternative-au-test-de-chi-carré-pour-les-tableaux-de-contingence.html"><a href="régression-de-poisson-une-alternative-au-test-de-chi-carré-pour-les-tableaux-de-contingence.html"><i class="fa fa-check"></i><b>9.4</b> Régression de Poisson: une alternative au test de Chi carré pour les tableaux de contingence</a></li>
<li class="chapter" data-level="9.5" data-path="tester-une-hypothèse-extrinsèque.html"><a href="tester-une-hypothèse-extrinsèque.html"><i class="fa fa-check"></i><b>9.5</b> Tester une hypothèse extrinsèque</a></li>
<li class="chapter" data-level="9.6" data-path="régression-de-poisson-pour-lanalyse-de-tableaux-de-contingence-à-plusieurs-critères.html"><a href="régression-de-poisson-pour-lanalyse-de-tableaux-de-contingence-à-plusieurs-critères.html"><i class="fa fa-check"></i><b>9.6</b> Régression de Poisson pour l’analyse de tableaux de contingence à plusieurs critères</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendice</b></span></li>
<li class="chapter" data-level="A" data-path="note-sur-les-devoirs-et-rmarkdown.html"><a href="note-sur-les-devoirs-et-rmarkdown.html"><i class="fa fa-check"></i><b>A</b> Note sur les devoirs et Rmarkdown</a></li>
<li class="chapter" data-level="B" data-path="petit-guide-pour-rmarkdown.html"><a href="petit-guide-pour-rmarkdown.html"><i class="fa fa-check"></i><b>B</b> Petit guide pour Rmarkdown</a><ul>
<li class="chapter" data-level="B.1" data-path="syntaxe-markdown.html"><a href="syntaxe-markdown.html"><i class="fa fa-check"></i><b>B.1</b> Syntaxe Markdown</a><ul>
<li class="chapter" data-level="B.1.1" data-path="syntaxe-markdown.html"><a href="syntaxe-markdown.html#titre-3"><i class="fa fa-check"></i><b>B.1.1</b> Titre 3</a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="à-propos-de-latex.html"><a href="à-propos-de-latex.html"><i class="fa fa-check"></i><b>B.2</b> À propos de LaTex</a></li>
<li class="chapter" data-level="B.3" data-path="concernant-le-code-dans-notebook.html"><a href="concernant-le-code-dans-notebook.html"><i class="fa fa-check"></i><b>B.3</b> Concernant le code dans notebook</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><a href="resources-pour-en-apprendre-plus-sur-rmarkdown.html"><i class="fa fa-check"></i><b>C</b> Resources pour en apprendre plus sur rmarkdown</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Publié avec bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4558 Biostatistiques appliquées avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="plan-factoriel-à-deux-facteurs-de-classification-et-réplication" class="section level2">
<h2><span class="header-section-number">6.2</span> Plan factoriel à deux facteurs de classification et réplication</h2>
<p>Il est fréquent de vouloir analyser l’effet de plusieurs facteurs simultanément. L’ANOVA factorielle à deux critères de classification permet d’examiner deux facteurs à la fois, mais la même approche peut être utilisée pour 3, 4 ou même 5 facteurs quoique l’interprétation des résultats devienne beaucoup plus complexe.</p>
<p>Supposons que vous êtes intéressés par l’effet de deux facteurs : site (location, Cumberland House ou The Pas) et sexe (sex, mâle ou femelle) sur la taille des esturgeons. Comme l’effectif n’est pas le même pour tous les groupes, c’est un plan qui n’est pas balancé. Notez aussi qu’il y a des valeurs manquantes pour certaines variables, ce qui veut dire que chaque mesure n’a pas été effectuée sur chaque poisson.</p>
<div id="anova-à-effets-fixes" class="section level3">
<h3><span class="header-section-number">6.2.1</span> ANOVA à effets fixes</h3>
<ul>
<li>Examinez d’abord les données en faisant des box plots de rdwght pour sex et location des données du fichier <code>Stu2wdat.csv</code> .</li>
</ul>
<p>Les graphiques montrent qu’aux deux sites les femelles sont probablement plus grandes que les mâles, mais que les tailles ne varient pas beaucoup d’un site à l’autre. La présence de valeurs extrêmes sur ces graphiques suggère qu’il y aura peut-être des problèmes avec la condition de normalité des résidus.</p>
<ul>
<li>Générez les statistiques sommaires pour RDWGHT par sex et Location.</li>
</ul>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb411-1" title="1">Stu2wdat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Stu2wdat.csv&quot;</span>)</a>
<a class="sourceLine" id="cb411-2" title="2"><span class="kw">aggregate</span>(rdwght<span class="op">~</span>sex<span class="op">+</span>location, <span class="dt">data=</span>Stu2wdat, <span class="dt">FUN =</span> <span class="st">&quot;summary&quot;</span>)</a></code></pre></div>
<pre><code>##            sex     location rdwght.Min. rdwght.1st Qu. rdwght.Median
## 1 FEMALE       CUMBERLAND      15.10000       20.40000      26.80000
## 2 MALE         CUMBERLAND      14.00000       19.22500      20.85000
## 3 FEMALE       THE_PAS         12.54000       19.14000      27.39000
## 4 MALE         THE_PAS          4.73000       14.63000      20.79000
##   rdwght.Mean rdwght.3rd Qu. rdwght.Max.
## 1    27.37347       31.40000    55.60000
## 2    22.14118       23.90000    35.60000
## 3    27.97717       33.88000    93.72000
## 4    20.64652       24.94250    49.94000</code></pre>
<p>Ces résultats supportent l’interprétation des box plots: Les femelles sont plus grosses que les mâles, et la différence de taille entre les deuxsites sont petites.</p>
<ul>
<li>À l’aide du fichier Stu2wdat.csv faites une ANOVA factorielle à
deux critères de classification:</li>
</ul>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb413-1" title="1"><span class="co"># Fit anova model and plot residual diagnostics</span></a>
<a class="sourceLine" id="cb413-2" title="2"><span class="co"># but first, save current par and set graphic page to hold 4 graphs</span></a>
<a class="sourceLine" id="cb413-3" title="3">opar &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb413-4" title="4">anova.model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(rdwght <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>location <span class="op">+</span><span class="st"> </span>sex<span class="op">:</span>location,</a>
<a class="sourceLine" id="cb413-5" title="5"><span class="dt">contrasts =</span> <span class="kw">list</span>(<span class="dt">sex =</span> contr.sum, <span class="dt">location =</span> contr.sum),</a>
<a class="sourceLine" id="cb413-6" title="6"><span class="dt">data =</span> Stu2wdat)</a>
<a class="sourceLine" id="cb413-7" title="7"><span class="kw">anova</span>(anova.model1)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: rdwght
##               Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## sex            1  1839.6 1839.55 18.6785 2.569e-05 ***
## location       1     4.3    4.26  0.0433    0.8355    
## sex:location   1    48.7   48.69  0.4944    0.4829    
## Residuals    178 17530.4   98.49                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>

<div class="rmdwarning">
Attention, R imprime les sommes des carrés séquentielles (Type I) les carrés moyens et probabilités associés. Vous ne pouvez pas vous y fier si votre plan d’expérience n’est pas parfaitement balancé. Dans cet exemple, le nombre de poissons capturés change selon le site et le sexe et le plan d’expérience n’est donc pas balancé.
</div>

<p>Vous devez extraire les sommes de carrés partielles (Type III). Le moyen le plus simple que j’ai trouvé est d’utiliser la fonction Anova()du package <code>car</code> (notez la différence subtile, Anova() n’est pas la même chose que anova(), R est impitoyable et distingue les majuscules des minuscules). Malheureusement, Anova() ne suffit pas; il faut également spécifier le type de contraste dans le modèle avecl’argument <code>contrasts = list(sex = contr.sum,location = contr.sum)</code></p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb415-1" title="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb415-2" title="2"><span class="kw">Anova</span>(anova.model1, <span class="dt">type =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: rdwght
##              Sum Sq  Df   F value    Pr(&gt;F)    
## (Intercept)  106507   1 1081.4552 &lt; 2.2e-16 ***
## sex            1745   1   17.7220 4.051e-05 ***
## location          9   1    0.0891    0.7656    
## sex:location     49   1    0.4944    0.4829    
## Residuals     17530 178                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Suite à l’ANOVA, on accepte deux hypothèses nulles: (1) que l’effet du sexe ne varie pas entre les sites (pas d’interaction significative) et (2) qu’il n’y a pas de différence de taille des esturgeons (peu importe le sexe) entre les deux sites. D’un autre coté, on rejette l’hypothèse nulle qu’il n’y a pas de différence de taille entre les esturgeons mâles et les femelles, tel que suggéré par les graphiques.</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb417-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb417-2" title="2"><span class="kw">plot</span>(anova.model1)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-210"></span>
<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-210-1.svg" alt="Conditions d'application ANOVA model1" width="672" />
<p class="caption">
Figure 6.1: Conditions d’application ANOVA model1
</p>
</div>
<p>Cependant, on ne peut se fier à ces résultats sans vérifier si les conditions d’application de l’ANOVA étaient remplies. Un examen des graphiques des résidus, en haut, montre que les résidus semblent être distribués plus ou moins normalement, si ce n’est des 3 valeurs extrêmes qui sont notées sur le diagramme de probabilité (cas 101, 24,&amp; 71). D’après le graphique des résidus vs les valeurs prédites, on voit que l’étendue des résidus est plus ou moins égale pour les valeurs estimées, sauf encore pour 2 ou 3 cas. Si on éprouve la normalité, on obtient:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb418-1" title="1"><span class="kw">shapiro.test</span>(<span class="kw">residuals</span>(anova.model1))</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(anova.model1)
## W = 0.87213, p-value = 2.619e-11</code></pre>
<p>Alors, il y a évidence que les résidus ne sont pas distribués normalement.</p>
<p>Nous allons utiliser le test de Levene pour examiner l’homoscédasticité des résidus, de la même façon qu’on a fait pour l’ANOVA à un critère de classification.</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb420-1" title="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb420-2" title="2"><span class="kw">leveneTest</span>(rdwght <span class="op">~</span><span class="st"> </span>sex <span class="op">*</span><span class="st"> </span>location, <span class="dt">data =</span> Stu2wdat)</a></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value  Pr(&gt;F)  
## group   3  3.8526 0.01055 *
##       178                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Si les résidus étaient homoscédastiques, on accepterait l’hypothèse nulle que le absres moyen ne varie pas entre les niveaux de sexe et location (i.e., sexloc). Le tableau d’ANOVA ci-dessus montre que l’hypothèse est rejetée. Il y a donc évidence d’hétéroscédasticité. En bref, nous avons donc plusieurs conditions d’application qui ne sont pas respectées. La question qui reste est: ces violations sont-elles suffisantes pour invalider nos conclusions ?</p>

<div class="rmdcode">
Répétez la même analyse avec les données du fichier <code>stu2mdat.csv</code> . Que concluez-vous? Supposons que vous vouliez comparer la taille des mâles et des femelles. Comment cette comparaison diffère entre les deux ensembles de données ?
</div>

<div class="sourceCode" id="cb422"><pre class="sourceCode r exer"><code class="sourceCode r"><a class="sourceLine" id="cb422-1" title="1">Stu2mdat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Stu2mdat.csv&quot;</span>)</a>
<a class="sourceLine" id="cb422-2" title="2">anova.model2 &lt;-<span class="st"> </span><span class="kw">lm</span>(</a>
<a class="sourceLine" id="cb422-3" title="3">  <span class="dt">formula =</span> rdwght <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>location <span class="op">+</span><span class="st"> </span>sex<span class="op">:</span>location,</a>
<a class="sourceLine" id="cb422-4" title="4">  <span class="dt">contrasts =</span> <span class="kw">list</span>(<span class="dt">sex =</span> contr.sum, <span class="dt">location =</span> contr.sum),</a>
<a class="sourceLine" id="cb422-5" title="5">  <span class="dt">data =</span> Stu2mdat)</a>
<a class="sourceLine" id="cb422-6" title="6"><span class="kw">summary</span>(anova.model2)</a>
<a class="sourceLine" id="cb422-7" title="7"><span class="kw">Anova</span>(anova.model2, <span class="dt">type =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = rdwght ~ sex + location + sex:location, data = Stu2mdat, 
##     contrasts = list(sex = contr.sum, location = contr.sum))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.917  -6.017  -0.580   4.445  65.743 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     24.5346     0.7461  32.885  &lt; 2e-16 ***
## sex1            -0.5246     0.7461  -0.703    0.483    
## location1        0.2227     0.7461   0.299    0.766    
## sex1:location1   3.1407     0.7461   4.210 4.05e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.924 on 178 degrees of freedom
##   (4 observations deleted due to missingness)
## Multiple R-squared:  0.09744,    Adjusted R-squared:  0.08223 
## F-statistic: 6.405 on 3 and 178 DF,  p-value: 0.0003817</code></pre>
<p>Notez que cette fois les femelles sont plus grandes que les mâles à Cumberland House, mais que c’est le contraire à The Pas. Quel est le résultat de l’ANOVA (n’oubliez pas qu’il faut des Type III sums of squares pour les résultats)?</p>
<pre><code>## Anova Table (Type III tests)
## 
## Response: rdwght
##              Sum Sq  Df   F value    Pr(&gt;F)    
## (Intercept)  106507   1 1081.4552 &lt; 2.2e-16 ***
## sex              49   1    0.4944    0.4829    
## location          9   1    0.0891    0.7656    
## sex:location   1745   1   17.7220 4.051e-05 ***
## Residuals     17530 178                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Dans ce cas, le terme de l’interaction (sex:location) est maintenant significatif mais les effets principaux ne le sont pas.</p>
<ul>
<li>Vous trouverez utile ici de créer des graphiques pour les deux fichiers de données pour comparer les interactions entre sex et location. Le graphique d’interaction montre les relations entre les moyennes de chaque combinaison de facteurs (appelées aussi les moyennes des ce$lules).Générez un graphique illustrant les intéractions en utilisant la fonction allEffects du package effects :</li>
</ul>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb425-1" title="1"><span class="kw">library</span>(effects)</a></code></pre></div>
<pre><code>## Registered S3 methods overwritten by &#39;lme4&#39;:
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car</code></pre>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb428-1" title="1"><span class="kw">allEffects</span>(anova.model1)</a></code></pre></div>
<pre><code>##  model: rdwght ~ sex + location + sex:location
## 
##  sex*location effect
##               location
## sex            CUMBERLAND   THE_PAS     
##   FEMALE           27.37347     27.97717
##   MALE             22.14118     20.64652</code></pre>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb430-1" title="1"><span class="kw">plot</span>(<span class="kw">allEffects</span>(anova.model1), <span class="st">&#39;sex:location&#39;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-217"></span>
<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-217-1.svg" alt="Effet du sexe et du lieu sur le poids des esturgeons" width="672" />
<p class="caption">
Figure 6.2: Effet du sexe et du lieu sur le poids des esturgeons
</p>
</div>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb431-1" title="1"><span class="kw">allEffects</span>(anova.model2)</a></code></pre></div>
<pre><code>##  model: rdwght ~ sex + location + sex:location
## 
##  sex*location effect
##               location
## sex            CUMBERLAND   THE_PAS     
##   FEMALE           27.37347     20.64652
##   MALE             22.14118     27.97717</code></pre>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb433-1" title="1"><span class="kw">plot</span>(<span class="kw">allEffects</span>(anova.model2), <span class="st">&#39;sex:location&#39;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-218"></span>
<img src="Labo_BIO4558_files/figure-html/unnamed-chunk-218-1.svg" alt="Effet du sexe et du lieu sur le poids des esturgeons" width="672" />
<p class="caption">
Figure 6.3: Effet du sexe et du lieu sur le poids des esturgeons
</p>
</div>
<p>Il y a une différence importante entre les résultats obtenus avec <code>stu2wdat</code> et <code>stu2mdat</code>. Dans le premier cas, puisqu’il n’y a pas d’interaction, on peut regrouper les données des deux niveaux d’un facteur (le site, par exemple) pour éprouver l’hypothèse d’un effet de l’autre facteur (le sexe). En fait, si on fait cela et que l’on calcule une ANOVA à un critère de classification (sex), on obtient:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb434-1" title="1"><span class="kw">Anova</span>(<span class="kw">aov</span>(rdwght <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> Stu2wdat), <span class="dt">type =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: rdwght
##             Sum Sq  Df F value    Pr(&gt;F)    
## (Intercept)  78191   1 800.440 &lt; 2.2e-16 ***
## sex           1840   1  18.831 2.377e-05 ***
## Residuals    17583 180                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notez que la somme des carrés des résidus (17583) est presque égale à celle du modèle complet (17530) de l’ANOVA factorielle à deux facteurs. C’est parce que dans cette anova factorielle, le terme d’interaction et le terme représentant l’effet du site n’expliquent qu’une partie infime de la variabilité. D’un autre coté, si on essaie le même truc avec <code>stu2mdat</code>, on obtient:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb436-1" title="1"><span class="kw">Anova</span>(<span class="kw">aov</span>(rdwght <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> Stu2mdat), <span class="dt">type =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: rdwght
##             Sum Sq  Df  F value Pr(&gt;F)    
## (Intercept)  55251   1 515.0435 &lt;2e-16 ***
## sex            113   1   1.0571 0.3053    
## Residuals    19309 180                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Ici la somme des carrées des résidus (19309) est beaucoup plus grande que celle de l’ANOVA factorielle (175306) parce qu’une partie importante de la variabilité expliquée par le modèle est associée à l’interaction. Notez que si on n’avait fait que cette analyse, on conclurait que les esturgeons mâles et femelles ont la même taille. Mais en fait leur taille diffère; seulement la différence est à l’avantage des mâles à un site et à l’avantage des femelles à l’autre. Il est donc délicat d’interpréter l’effet principal (sexe) en présence d’une interaction significative…</p>
</div>
<div id="anova-à-effets-mixtes" class="section level3">
<h3><span class="header-section-number">6.2.2</span> ANOVA à effets mixtes</h3>
<p>Les analyses qui précèdent négligent un point important: <code>location</code> pourrait être traité comme un facteur aléatoire et <code>sex</code> est fixe. Par conséquent le modèle approprié d’ANOVA est de type mixte.</p>
<p>Notez que dans toutes les analyses qui précèdent, R a traité cette ANOVA comme si elle etait de type effet fixe seulement, et les termes principaux et celui d’interaction ont été testés en utilisant le carré moyen des résidus comme dénominateur des tests de F. Cependant, pour une ANOVA de type mixte, ces effets devraient être testés en utilisant le carré moyen du terme d’interaction, ou en combinant la somme des carrés de l’erreur et de l’interaction (selon le statisticien consulté!).</p>
<p>En utilisant <code>Stu2wdat</code>, refaites un tableau d’ANOVA pour RDWGHT en considérant location comme facteur aléatoire et sex comme un facteur fixe. Pour ce faire, vous devrez recalculer les valeurs de F pour sex et location en utilisant le carré moyen de l’interaction sex:location au lieu du carré moyen des résidus comme dénominateur. Le mieux c’est de le faire à la mitaine ent travaillant avec les Type III Sums of squares du tableau d’ANOVA.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r exer"><code class="sourceCode r"><a class="sourceLine" id="cb438-1" title="1"><span class="kw">Anova</span>(anova.model2, <span class="dt">type =</span> <span class="dv">3</span>)</a></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: rdwght
##              Sum Sq  Df   F value    Pr(&gt;F)    
## (Intercept)  106507   1 1081.4552 &lt; 2.2e-16 ***
## sex              49   1    0.4944    0.4829    
## location          9   1    0.0891    0.7656    
## sex:location   1745   1   17.7220 4.051e-05 ***
## Residuals     17530 178                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Pour <code>sex</code>, la nouvelle valeur de F (le rapport des carrés moyens) est de</p>
<p><span class="math display">\[F = \frac{(1745/1)}{(49/1)} = 35.6\]</span></p>
<p>Pour obtenir la valeur de p correspondant à cette statistique <code>F</code>, il faut utilisez la fonction de probabilité de la distribtuion de F <code>pf(F, df1, df2, lower.tail = FALSE)</code>, où F est la valeur de F calculée, et <code>df1</code> et <code>df2</code> sont les degrés de liberté du numérateur (sex) et dénominateur(SEX:location).</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb440-1" title="1"><span class="kw">pf</span>(<span class="fl">35.6</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dt">lower.tail =</span>  <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## [1] 0.1057152</code></pre>
<p>Notez que maintenant la valeur de p pour sex n’est plus significative. C’est parce que le carré moyen de l’erreur dans l’ANOVA initiale est plus petit que celui associé à l’interaction, mais surtout parce que le nombre de degrés de liberté pour le dénominateur du test de F est passé de 178 à 1 seulement. En général, c’est beaucoup plus difficile d’obtenir des résultats significatifs quand les degrés de liberté pour le dénominateur sont petits.</p>

<div class="rmdnote">
Les modèles mixtes qui sont une généralisation de l’ANOVA à effets mixtes sont maintenant extrêmement bien développé et sont à favoriser lors d’analyse incluant des effets dit aléatoires.
</div>

</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="set-anomul.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="plan-factoriel-à-deux-facteurs-de-classification-sans-réplication.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/BIO4558_uOttawa_lab_manual/06-anova_mult.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labo_BIO4558.pdf", "Labo_BIO4558.epub", "Labo_BIO4558.mobi"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
